
IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='a.bovo') DROP LOGIN [a.bovo] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='a.bovo') DROP SCHEMA [a.bovo]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='a.bovo' AND type_desc='SQL_USER') DROP USER [a.bovo]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='a.bovo') CREATE LOGIN [a.bovo] WITH PASSWORD=N'uruguay', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [a.bovo] FOR LOGIN [a.bovo]
ALTER ROLE [Metodo98] ADD MEMBER [a.bovo]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='a.cichellero') DROP LOGIN [a.cichellero] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='a.cichellero') DROP SCHEMA [a.cichellero]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='a.cichellero' AND type_desc='SQL_USER') DROP USER [a.cichellero]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='a.cichellero') CREATE LOGIN [a.cichellero] WITH PASSWORD=N'A03aud14', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [a.cichellero] FOR LOGIN [a.cichellero]
ALTER ROLE [Metodo98] ADD MEMBER [a.cichellero]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='a.norbiato') DROP LOGIN [a.norbiato] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='a.norbiato') DROP SCHEMA [a.norbiato]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='a.norbiato' AND type_desc='SQL_USER') DROP USER [a.norbiato]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='a.norbiato') CREATE LOGIN [a.norbiato] WITH PASSWORD=N'Asf0512Y', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [a.norbiato] FOR LOGIN [a.norbiato]
ALTER ROLE [Metodo98] ADD MEMBER [a.norbiato]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='a.scarpulla') DROP LOGIN [a.scarpulla] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='a.scarpulla') DROP SCHEMA [a.scarpulla]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='a.scarpulla' AND type_desc='SQL_USER') DROP USER [a.scarpulla]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='a.scarpulla') CREATE LOGIN [a.scarpulla] WITH PASSWORD=N'ventus', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [a.scarpulla] FOR LOGIN [a.scarpulla]
ALTER ROLE [Metodo98] ADD MEMBER [a.scarpulla]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='a.zarantonello') DROP LOGIN [a.zarantonello] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='a.zarantonello') DROP SCHEMA [a.zarantonello]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='a.zarantonello' AND type_desc='SQL_USER') DROP USER [a.zarantonello]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='a.zarantonello') CREATE LOGIN [a.zarantonello] WITH PASSWORD=N'j4-UxeSp', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [a.zarantonello] FOR LOGIN [a.zarantonello]
ALTER ROLE [Metodo98] ADD MEMBER [a.zarantonello]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='a.zilio') DROP LOGIN [a.zilio] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='a.zilio') DROP SCHEMA [a.zilio]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='a.zilio' AND type_desc='SQL_USER') DROP USER [a.zilio]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='a.zilio') CREATE LOGIN [a.zilio] WITH PASSWORD=N'pz0608uac', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [a.zilio] FOR LOGIN [a.zilio]
ALTER ROLE [Metodo98] ADD MEMBER [a.zilio]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='c.cenci') DROP LOGIN [c.cenci] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='c.cenci') DROP SCHEMA [c.cenci]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='c.cenci' AND type_desc='SQL_USER') DROP USER [c.cenci]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='c.cenci') CREATE LOGIN [c.cenci] WITH PASSWORD=N'berber', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [c.cenci] FOR LOGIN [c.cenci]
ALTER ROLE [Metodo98] ADD MEMBER [c.cenci]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='c.moroni') DROP LOGIN [c.moroni] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='c.moroni') DROP SCHEMA [c.moroni]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='c.moroni' AND type_desc='SQL_USER') DROP USER [c.moroni]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='c.moroni') CREATE LOGIN [c.moroni] WITH PASSWORD=N'c.moroni', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [c.moroni] FOR LOGIN [c.moroni]
ALTER ROLE [Metodo98] ADD MEMBER [c.moroni]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='c.raschietti') DROP LOGIN [c.raschietti] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='c.raschietti') DROP SCHEMA [c.raschietti]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='c.raschietti' AND type_desc='SQL_USER') DROP USER [c.raschietti]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='c.raschietti') CREATE LOGIN [c.raschietti] WITH PASSWORD=N'C313ciMB', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [c.raschietti] FOR LOGIN [c.raschietti]
ALTER ROLE [Metodo98] ADD MEMBER [c.raschietti]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='c.tozzi') DROP LOGIN [c.tozzi] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='c.tozzi') DROP SCHEMA [c.tozzi]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='c.tozzi' AND type_desc='SQL_USER') DROP USER [c.tozzi]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='c.tozzi') CREATE LOGIN [c.tozzi] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [c.tozzi] FOR LOGIN [c.tozzi]
ALTER ROLE [Metodo98] ADD MEMBER [c.tozzi]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='c.zampieri') DROP LOGIN [c.zampieri] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='c.zampieri') DROP SCHEMA [c.zampieri]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='c.zampieri' AND type_desc='SQL_USER') DROP USER [c.zampieri]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='c.zampieri') CREATE LOGIN [c.zampieri] WITH PASSWORD=N'Raffaella', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [c.zampieri] FOR LOGIN [c.zampieri]
ALTER ROLE [Metodo98] ADD MEMBER [c.zampieri]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='camcea') DROP LOGIN [camcea] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='camcea') DROP SCHEMA [camcea]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='camcea' AND type_desc='SQL_USER') DROP USER [camcea]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='camcea') CREATE LOGIN [camcea] WITH PASSWORD=N'pa04cc11', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [camcea] FOR LOGIN [camcea]
ALTER ROLE [Metodo98] ADD MEMBER [camcea]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='cqcea1') DROP LOGIN [cqcea1] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='cqcea1') DROP SCHEMA [cqcea1]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='cqcea1' AND type_desc='SQL_USER') DROP USER [cqcea1]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='cqcea1') CREATE LOGIN [cqcea1] WITH PASSWORD=N'allegri', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [cqcea1] FOR LOGIN [cqcea1]
ALTER ROLE [Metodo98] ADD MEMBER [cqcea1]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='d.bassani') DROP LOGIN [d.bassani] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='d.bassani') DROP SCHEMA [d.bassani]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='d.bassani' AND type_desc='SQL_USER') DROP USER [d.bassani]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='d.bassani') CREATE LOGIN [d.bassani] WITH PASSWORD=N'db05yesok', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [d.bassani] FOR LOGIN [d.bassani]
ALTER ROLE [Metodo98] ADD MEMBER [d.bassani]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='d.dalbello') DROP LOGIN [d.dalbello] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='d.dalbello') DROP SCHEMA [d.dalbello]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='d.dalbello' AND type_desc='SQL_USER') DROP USER [d.dalbello]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='d.dalbello') CREATE LOGIN [d.dalbello] WITH PASSWORD=N'dodi00', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [d.dalbello] FOR LOGIN [d.dalbello]
ALTER ROLE [Metodo98] ADD MEMBER [d.dalbello]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='d.pavan') DROP LOGIN [d.pavan] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='d.pavan') DROP SCHEMA [d.pavan]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='d.pavan' AND type_desc='SQL_USER') DROP USER [d.pavan]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='d.pavan') CREATE LOGIN [d.pavan] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [d.pavan] FOR LOGIN [d.pavan]
ALTER ROLE [Metodo98] ADD MEMBER [d.pavan]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.carolo') DROP LOGIN [e.carolo] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='e.carolo') DROP SCHEMA [e.carolo]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='e.carolo' AND type_desc='SQL_USER') DROP USER [e.carolo]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.carolo') CREATE LOGIN [e.carolo] WITH PASSWORD=N'silvia', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [e.carolo] FOR LOGIN [e.carolo]
ALTER ROLE [Metodo98] ADD MEMBER [e.carolo]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.cestonaro') DROP LOGIN [e.cestonaro] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='e.cestonaro') DROP SCHEMA [e.cestonaro]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='e.cestonaro' AND type_desc='SQL_USER') DROP USER [e.cestonaro]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.cestonaro') CREATE LOGIN [e.cestonaro] WITH PASSWORD=N'sofiac', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [e.cestonaro] FOR LOGIN [e.cestonaro]
ALTER ROLE [Metodo98] ADD MEMBER [e.cestonaro]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.cinefra') DROP LOGIN [e.cinefra] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='e.cinefra') DROP SCHEMA [e.cinefra]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='e.cinefra' AND type_desc='SQL_USER') DROP USER [e.cinefra]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.cinefra') CREATE LOGIN [e.cinefra] WITH PASSWORD=N'sovizzo', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [e.cinefra] FOR LOGIN [e.cinefra]
ALTER ROLE [Metodo98] ADD MEMBER [e.cinefra]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.dagostini') DROP LOGIN [e.dagostini] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='e.dagostini') DROP SCHEMA [e.dagostini]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='e.dagostini' AND type_desc='SQL_USER') DROP USER [e.dagostini]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.dagostini') CREATE LOGIN [e.dagostini] WITH PASSWORD=N'', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [e.dagostini] FOR LOGIN [e.dagostini]
ALTER ROLE [Metodo98] ADD MEMBER [e.dagostini]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.rigon') DROP LOGIN [e.rigon] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='e.rigon') DROP SCHEMA [e.rigon]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='e.rigon' AND type_desc='SQL_USER') DROP USER [e.rigon]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.rigon') CREATE LOGIN [e.rigon] WITH PASSWORD=N'Michael', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [e.rigon] FOR LOGIN [e.rigon]
ALTER ROLE [Metodo98] ADD MEMBER [e.rigon]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.sartore') DROP LOGIN [e.sartore] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='e.sartore') DROP SCHEMA [e.sartore]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='e.sartore' AND type_desc='SQL_USER') DROP USER [e.sartore]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.sartore') CREATE LOGIN [e.sartore] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [e.sartore] FOR LOGIN [e.sartore]
ALTER ROLE [Metodo98] ADD MEMBER [e.sartore]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.targon') DROP LOGIN [e.targon] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='e.targon') DROP SCHEMA [e.targon]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='e.targon' AND type_desc='SQL_USER') DROP USER [e.targon]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.targon') CREATE LOGIN [e.targon] WITH PASSWORD=N'etmn08', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [e.targon] FOR LOGIN [e.targon]
ALTER ROLE [Metodo98] ADD MEMBER [e.targon]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.targon2') DROP LOGIN [e.targon2] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='e.targon2') DROP SCHEMA [e.targon2]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='e.targon2' AND type_desc='SQL_USER') DROP USER [e.targon2]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='e.targon2') CREATE LOGIN [e.targon2] WITH PASSWORD=N'etmn08', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [e.targon2] FOR LOGIN [e.targon2]
ALTER ROLE [Metodo98] ADD MEMBER [e.targon2]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='eletcea') DROP LOGIN [eletcea] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='eletcea') DROP SCHEMA [eletcea]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='eletcea' AND type_desc='SQL_USER') DROP USER [eletcea]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='eletcea') CREATE LOGIN [eletcea] WITH PASSWORD=N'pippo123', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [eletcea] FOR LOGIN [eletcea]
ALTER ROLE [Metodo98] ADD MEMBER [eletcea]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.baldo') DROP LOGIN [f.baldo] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='f.baldo') DROP SCHEMA [f.baldo]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='f.baldo' AND type_desc='SQL_USER') DROP USER [f.baldo]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.baldo') CREATE LOGIN [f.baldo] WITH PASSWORD=N'pePh-b5u', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [f.baldo] FOR LOGIN [f.baldo]
ALTER ROLE [Metodo98] ADD MEMBER [f.baldo]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.benatello') DROP LOGIN [f.benatello] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='f.benatello') DROP SCHEMA [f.benatello]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='f.benatello' AND type_desc='SQL_USER') DROP USER [f.benatello]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.benatello') CREATE LOGIN [f.benatello] WITH PASSWORD=N'Pra&4wuW', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [f.benatello] FOR LOGIN [f.benatello]
ALTER ROLE [Metodo98] ADD MEMBER [f.benatello]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.brazzarola') DROP LOGIN [f.brazzarola] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='f.brazzarola') DROP SCHEMA [f.brazzarola]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='f.brazzarola' AND type_desc='SQL_USER') DROP USER [f.brazzarola]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.brazzarola') CREATE LOGIN [f.brazzarola] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [f.brazzarola] FOR LOGIN [f.brazzarola]
ALTER ROLE [Metodo98] ADD MEMBER [f.brazzarola]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.carlotto') DROP LOGIN [f.carlotto] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='f.carlotto') DROP SCHEMA [f.carlotto]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='f.carlotto' AND type_desc='SQL_USER') DROP USER [f.carlotto]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.carlotto') CREATE LOGIN [f.carlotto] WITH PASSWORD=N'fc0910rc', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [f.carlotto] FOR LOGIN [f.carlotto]
ALTER ROLE [Metodo98] ADD MEMBER [f.carlotto]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.festival') DROP LOGIN [f.festival] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='f.festival') DROP SCHEMA [f.festival]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='f.festival' AND type_desc='SQL_USER') DROP USER [f.festival]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.festival') CREATE LOGIN [f.festival] WITH PASSWORD=N'f.festival', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [f.festival] FOR LOGIN [f.festival]
ALTER ROLE [Metodo98] ADD MEMBER [f.festival]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.lorenzi') DROP LOGIN [f.lorenzi] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='f.lorenzi') DROP SCHEMA [f.lorenzi]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='f.lorenzi' AND type_desc='SQL_USER') DROP USER [f.lorenzi]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.lorenzi') CREATE LOGIN [f.lorenzi] WITH PASSWORD=N'fl02tabc', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [f.lorenzi] FOR LOGIN [f.lorenzi]
ALTER ROLE [Metodo98] ADD MEMBER [f.lorenzi]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.masiero') DROP LOGIN [f.masiero] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='f.masiero') DROP SCHEMA [f.masiero]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='f.masiero' AND type_desc='SQL_USER') DROP USER [f.masiero]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.masiero') CREATE LOGIN [f.masiero] WITH PASSWORD=N'MacS12n!', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [f.masiero] FOR LOGIN [f.masiero]
ALTER ROLE [Metodo98] ADD MEMBER [f.masiero]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.mojentale') DROP LOGIN [f.mojentale] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='f.mojentale') DROP SCHEMA [f.mojentale]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='f.mojentale' AND type_desc='SQL_USER') DROP USER [f.mojentale]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.mojentale') CREATE LOGIN [f.mojentale] WITH PASSWORD=N'6uSt#fEj', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [f.mojentale] FOR LOGIN [f.mojentale]
ALTER ROLE [Metodo98] ADD MEMBER [f.mojentale]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.rossato') DROP LOGIN [f.rossato] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='f.rossato') DROP SCHEMA [f.rossato]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='f.rossato' AND type_desc='SQL_USER') DROP USER [f.rossato]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.rossato') CREATE LOGIN [f.rossato] WITH PASSWORD=N'cinquanta', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [f.rossato] FOR LOGIN [f.rossato]
ALTER ROLE [Metodo98] ADD MEMBER [f.rossato]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.simonetti') DROP LOGIN [f.simonetti] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='f.simonetti') DROP SCHEMA [f.simonetti]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='f.simonetti' AND type_desc='SQL_USER') DROP USER [f.simonetti]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.simonetti') CREATE LOGIN [f.simonetti] WITH PASSWORD=N'pru2Eduf', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [f.simonetti] FOR LOGIN [f.simonetti]
ALTER ROLE [Metodo98] ADD MEMBER [f.simonetti]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.valsecchi') DROP LOGIN [f.valsecchi] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='f.valsecchi') DROP SCHEMA [f.valsecchi]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='f.valsecchi' AND type_desc='SQL_USER') DROP USER [f.valsecchi]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.valsecchi') CREATE LOGIN [f.valsecchi] WITH PASSWORD=N'flores', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [f.valsecchi] FOR LOGIN [f.valsecchi]
ALTER ROLE [Metodo98] ADD MEMBER [f.valsecchi]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.zanin') DROP LOGIN [f.zanin] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='f.zanin') DROP SCHEMA [f.zanin]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='f.zanin' AND type_desc='SQL_USER') DROP USER [f.zanin]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='f.zanin') CREATE LOGIN [f.zanin] WITH PASSWORD=N'FZ0610us', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [f.zanin] FOR LOGIN [f.zanin]
ALTER ROLE [Metodo98] ADD MEMBER [f.zanin]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.bisognin') DROP LOGIN [g.bisognin] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='g.bisognin') DROP SCHEMA [g.bisognin]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='g.bisognin' AND type_desc='SQL_USER') DROP USER [g.bisognin]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.bisognin') CREATE LOGIN [g.bisognin] WITH PASSWORD=N'G14apdNC', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [g.bisognin] FOR LOGIN [g.bisognin]
ALTER ROLE [Metodo98] ADD MEMBER [g.bisognin]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.calgarotto') DROP LOGIN [g.calgarotto] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='g.calgarotto') DROP SCHEMA [g.calgarotto]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='g.calgarotto' AND type_desc='SQL_USER') DROP USER [g.calgarotto]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.calgarotto') CREATE LOGIN [g.calgarotto] WITH PASSWORD=N'Ye3AyEb+', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [g.calgarotto] FOR LOGIN [g.calgarotto]
ALTER ROLE [Metodo98] ADD MEMBER [g.calgarotto]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.castagna') DROP LOGIN [g.castagna] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='g.castagna') DROP SCHEMA [g.castagna]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='g.castagna' AND type_desc='SQL_USER') DROP USER [g.castagna]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.castagna') CREATE LOGIN [g.castagna] WITH PASSWORD=N'barbara', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [g.castagna] FOR LOGIN [g.castagna]
ALTER ROLE [Metodo98] ADD MEMBER [g.castagna]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.castrignano') DROP LOGIN [g.castrignano] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='g.castrignano') DROP SCHEMA [g.castrignano]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='g.castrignano' AND type_desc='SQL_USER') DROP USER [g.castrignano]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.castrignano') CREATE LOGIN [g.castrignano] WITH PASSWORD=N'giuliano', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [g.castrignano] FOR LOGIN [g.castrignano]
ALTER ROLE [Metodo98] ADD MEMBER [g.castrignano]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.ferrari') DROP LOGIN [g.ferrari] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='g.ferrari') DROP SCHEMA [g.ferrari]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='g.ferrari' AND type_desc='SQL_USER') DROP USER [g.ferrari]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.ferrari') CREATE LOGIN [g.ferrari] WITH PASSWORD=N'pippo3dici', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [g.ferrari] FOR LOGIN [g.ferrari]
ALTER ROLE [Metodo98] ADD MEMBER [g.ferrari]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.giuriato') DROP LOGIN [g.giuriato] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='g.giuriato') DROP SCHEMA [g.giuriato]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='g.giuriato' AND type_desc='SQL_USER') DROP USER [g.giuriato]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.giuriato') CREATE LOGIN [g.giuriato] WITH PASSWORD=N'g.giuriato', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [g.giuriato] FOR LOGIN [g.giuriato]
ALTER ROLE [Metodo98] ADD MEMBER [g.giuriato]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.peron') DROP LOGIN [g.peron] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='g.peron') DROP SCHEMA [g.peron]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='g.peron' AND type_desc='SQL_USER') DROP USER [g.peron]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.peron') CREATE LOGIN [g.peron] WITH PASSWORD=N'carota2', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [g.peron] FOR LOGIN [g.peron]
ALTER ROLE [Metodo98] ADD MEMBER [g.peron]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.visona') DROP LOGIN [g.visona] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='g.visona') DROP SCHEMA [g.visona]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='g.visona' AND type_desc='SQL_USER') DROP USER [g.visona]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='g.visona') CREATE LOGIN [g.visona] WITH PASSWORD=N'giulia', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [g.visona] FOR LOGIN [g.visona]
ALTER ROLE [Metodo98] ADD MEMBER [g.visona]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='gts') DROP LOGIN [gts] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='gts') DROP SCHEMA [gts]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='gts' AND type_desc='SQL_USER') DROP USER [gts]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='gts') CREATE LOGIN [gts] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [gts] FOR LOGIN [gts]
ALTER ROLE [Metodo98] ADD MEMBER [gts]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='i.baggio') DROP LOGIN [i.baggio] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='i.baggio') DROP SCHEMA [i.baggio]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='i.baggio' AND type_desc='SQL_USER') DROP USER [i.baggio]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='i.baggio') CREATE LOGIN [i.baggio] WITH PASSWORD=N'latina', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [i.baggio] FOR LOGIN [i.baggio]
ALTER ROLE [Metodo98] ADD MEMBER [i.baggio]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='i.bagiacchi') DROP LOGIN [i.bagiacchi] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='i.bagiacchi') DROP SCHEMA [i.bagiacchi]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='i.bagiacchi' AND type_desc='SQL_USER') DROP USER [i.bagiacchi]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='i.bagiacchi') CREATE LOGIN [i.bagiacchi] WITH PASSWORD=N'vpcecsbre003', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [i.bagiacchi] FOR LOGIN [i.bagiacchi]
ALTER ROLE [Metodo98] ADD MEMBER [i.bagiacchi]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='i.marra') DROP LOGIN [i.marra] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='i.marra') DROP SCHEMA [i.marra]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='i.marra' AND type_desc='SQL_USER') DROP USER [i.marra]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='i.marra') CREATE LOGIN [i.marra] WITH PASSWORD=N'ilario', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [i.marra] FOR LOGIN [i.marra]
ALTER ROLE [Metodo98] ADD MEMBER [i.marra]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='i.rebellato') DROP LOGIN [i.rebellato] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='i.rebellato') DROP SCHEMA [i.rebellato]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='i.rebellato' AND type_desc='SQL_USER') DROP USER [i.rebellato]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='i.rebellato') CREATE LOGIN [i.rebellato] WITH PASSWORD=N'gaim9592', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [i.rebellato] FOR LOGIN [i.rebellato]
ALTER ROLE [Metodo98] ADD MEMBER [i.rebellato]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='i.vukadin') DROP LOGIN [i.vukadin] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='i.vukadin') DROP SCHEMA [i.vukadin]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='i.vukadin' AND type_desc='SQL_USER') DROP USER [i.vukadin]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='i.vukadin') CREATE LOGIN [i.vukadin] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [i.vukadin] FOR LOGIN [i.vukadin]
ALTER ROLE [Metodo98] ADD MEMBER [i.vukadin]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='l.battaglia') DROP LOGIN [l.battaglia] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='l.battaglia') DROP SCHEMA [l.battaglia]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='l.battaglia' AND type_desc='SQL_USER') DROP USER [l.battaglia]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='l.battaglia') CREATE LOGIN [l.battaglia] WITH PASSWORD=N'angela', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [l.battaglia] FOR LOGIN [l.battaglia]
ALTER ROLE [Metodo98] ADD MEMBER [l.battaglia]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='l.crosta') DROP LOGIN [l.crosta] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='l.crosta') DROP SCHEMA [l.crosta]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='l.crosta' AND type_desc='SQL_USER') DROP USER [l.crosta]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='l.crosta') CREATE LOGIN [l.crosta] WITH PASSWORD=N'LsA6mop!', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [l.crosta] FOR LOGIN [l.crosta]
ALTER ROLE [Metodo98] ADD MEMBER [l.crosta]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='l.dipietra') DROP LOGIN [l.dipietra] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='l.dipietra') DROP SCHEMA [l.dipietra]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='l.dipietra' AND type_desc='SQL_USER') DROP USER [l.dipietra]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='l.dipietra') CREATE LOGIN [l.dipietra] WITH PASSWORD=N'ldp0708slm', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [l.dipietra] FOR LOGIN [l.dipietra]
ALTER ROLE [Metodo98] ADD MEMBER [l.dipietra]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='l.montagna') DROP LOGIN [l.montagna] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='l.montagna') DROP SCHEMA [l.montagna]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='l.montagna' AND type_desc='SQL_USER') DROP USER [l.montagna]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='l.montagna') CREATE LOGIN [l.montagna] WITH PASSWORD=N'edilkamin', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [l.montagna] FOR LOGIN [l.montagna]
ALTER ROLE [Metodo98] ADD MEMBER [l.montagna]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='l.piva') DROP LOGIN [l.piva] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='l.piva') DROP SCHEMA [l.piva]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='l.piva' AND type_desc='SQL_USER') DROP USER [l.piva]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='l.piva') CREATE LOGIN [l.piva] WITH PASSWORD=N'lsdt0709', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [l.piva] FOR LOGIN [l.piva]
ALTER ROLE [Metodo98] ADD MEMBER [l.piva]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='l.schenato') DROP LOGIN [l.schenato] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='l.schenato') DROP SCHEMA [l.schenato]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='l.schenato' AND type_desc='SQL_USER') DROP USER [l.schenato]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='l.schenato') CREATE LOGIN [l.schenato] WITH PASSWORD=N'andrea', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [l.schenato] FOR LOGIN [l.schenato]
ALTER ROLE [Metodo98] ADD MEMBER [l.schenato]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='Luciano') DROP LOGIN [Luciano] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='Luciano') DROP SCHEMA [Luciano]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='Luciano' AND type_desc='SQL_USER') DROP USER [Luciano]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='Luciano') CREATE LOGIN [Luciano] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [Luciano] FOR LOGIN [Luciano]
ALTER ROLE [Metodo98] ADD MEMBER [Luciano]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.aravecchia') DROP LOGIN [m.aravecchia] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.aravecchia') DROP SCHEMA [m.aravecchia]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.aravecchia' AND type_desc='SQL_USER') DROP USER [m.aravecchia]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.aravecchia') CREATE LOGIN [m.aravecchia] WITH PASSWORD=N'bed6verA', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.aravecchia] FOR LOGIN [m.aravecchia]
ALTER ROLE [Metodo98] ADD MEMBER [m.aravecchia]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.brunelli') DROP LOGIN [m.brunelli] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.brunelli') DROP SCHEMA [m.brunelli]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.brunelli' AND type_desc='SQL_USER') DROP USER [m.brunelli]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.brunelli') CREATE LOGIN [m.brunelli] WITH PASSWORD=N'mb0608pmbc', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.brunelli] FOR LOGIN [m.brunelli]
ALTER ROLE [Metodo98] ADD MEMBER [m.brunelli]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.caderbe') DROP LOGIN [m.caderbe] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.caderbe') DROP SCHEMA [m.caderbe]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.caderbe' AND type_desc='SQL_USER') DROP USER [m.caderbe]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.caderbe') CREATE LOGIN [m.caderbe] WITH PASSWORD=N'cr5xE&Ej', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.caderbe] FOR LOGIN [m.caderbe]
ALTER ROLE [Metodo98] ADD MEMBER [m.caderbe]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.colombara') DROP LOGIN [m.colombara] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.colombara') DROP SCHEMA [m.colombara]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.colombara' AND type_desc='SQL_USER') DROP USER [m.colombara]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.colombara') CREATE LOGIN [m.colombara] WITH PASSWORD=N'm10Met', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.colombara] FOR LOGIN [m.colombara]
ALTER ROLE [Metodo98] ADD MEMBER [m.colombara]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.cozzuol') DROP LOGIN [m.cozzuol] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.cozzuol') DROP SCHEMA [m.cozzuol]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.cozzuol' AND type_desc='SQL_USER') DROP USER [m.cozzuol]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.cozzuol') CREATE LOGIN [m.cozzuol] WITH PASSWORD=N'Mus1110C', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.cozzuol] FOR LOGIN [m.cozzuol]
ALTER ROLE [Metodo98] ADD MEMBER [m.cozzuol]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.dalmaso') DROP LOGIN [m.dalmaso] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.dalmaso') DROP SCHEMA [m.dalmaso]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.dalmaso' AND type_desc='SQL_USER') DROP USER [m.dalmaso]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.dalmaso') CREATE LOGIN [m.dalmaso] WITH PASSWORD=N'qebu6+aF', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.dalmaso] FOR LOGIN [m.dalmaso]
ALTER ROLE [Metodo98] ADD MEMBER [m.dalmaso]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.frasson') DROP LOGIN [m.frasson] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.frasson') DROP SCHEMA [m.frasson]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.frasson' AND type_desc='SQL_USER') DROP USER [m.frasson]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.frasson') CREATE LOGIN [m.frasson] WITH PASSWORD=N'frs941', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.frasson] FOR LOGIN [m.frasson]
ALTER ROLE [Metodo98] ADD MEMBER [m.frasson]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.milan') DROP LOGIN [m.milan] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.milan') DROP SCHEMA [m.milan]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.milan' AND type_desc='SQL_USER') DROP USER [m.milan]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.milan') CREATE LOGIN [m.milan] WITH PASSWORD=N'M0311udB', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.milan] FOR LOGIN [m.milan]
ALTER ROLE [Metodo98] ADD MEMBER [m.milan]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.moscon') DROP LOGIN [m.moscon] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.moscon') DROP SCHEMA [m.moscon]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.moscon' AND type_desc='SQL_USER') DROP USER [m.moscon]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.moscon') CREATE LOGIN [m.moscon] WITH PASSWORD=N'mosconm', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.moscon] FOR LOGIN [m.moscon]
ALTER ROLE [Metodo98] ADD MEMBER [m.moscon]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.panozzo') DROP LOGIN [m.panozzo] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.panozzo') DROP SCHEMA [m.panozzo]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.panozzo' AND type_desc='SQL_USER') DROP USER [m.panozzo]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.panozzo') CREATE LOGIN [m.panozzo] WITH PASSWORD=N'annaleo', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.panozzo] FOR LOGIN [m.panozzo]
ALTER ROLE [Metodo98] ADD MEMBER [m.panozzo]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.sartor') DROP LOGIN [m.sartor] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.sartor') DROP SCHEMA [m.sartor]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.sartor' AND type_desc='SQL_USER') DROP USER [m.sartor]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.sartor') CREATE LOGIN [m.sartor] WITH PASSWORD=N'samsam', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.sartor] FOR LOGIN [m.sartor]
ALTER ROLE [Metodo98] ADD MEMBER [m.sartor]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.sbalchiero') DROP LOGIN [m.sbalchiero] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.sbalchiero') DROP SCHEMA [m.sbalchiero]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.sbalchiero' AND type_desc='SQL_USER') DROP USER [m.sbalchiero]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.sbalchiero') CREATE LOGIN [m.sbalchiero] WITH PASSWORD=N'mry0708trctrc', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.sbalchiero] FOR LOGIN [m.sbalchiero]
ALTER ROLE [Metodo98] ADD MEMBER [m.sbalchiero]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.signore') DROP LOGIN [m.signore] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.signore') DROP SCHEMA [m.signore]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.signore' AND type_desc='SQL_USER') DROP USER [m.signore]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.signore') CREATE LOGIN [m.signore] WITH PASSWORD=N'Marco2009', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.signore] FOR LOGIN [m.signore]
ALTER ROLE [Metodo98] ADD MEMBER [m.signore]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.tognato') DROP LOGIN [m.tognato] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.tognato') DROP SCHEMA [m.tognato]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.tognato' AND type_desc='SQL_USER') DROP USER [m.tognato]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.tognato') CREATE LOGIN [m.tognato] WITH PASSWORD=N'd0608muc', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.tognato] FOR LOGIN [m.tognato]
ALTER ROLE [Metodo98] ADD MEMBER [m.tognato]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.trentin') DROP LOGIN [m.trentin] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.trentin') DROP SCHEMA [m.trentin]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.trentin' AND type_desc='SQL_USER') DROP USER [m.trentin]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.trentin') CREATE LOGIN [m.trentin] WITH PASSWORD=N'SOLUZIONI', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.trentin] FOR LOGIN [m.trentin]
ALTER ROLE [Metodo98] ADD MEMBER [m.trentin]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.zanin') DROP LOGIN [m.zanin] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='m.zanin') DROP SCHEMA [m.zanin]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='m.zanin' AND type_desc='SQL_USER') DROP USER [m.zanin]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='m.zanin') CREATE LOGIN [m.zanin] WITH PASSWORD=N'Md14engV', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [m.zanin] FOR LOGIN [m.zanin]
ALTER ROLE [Metodo98] ADD MEMBER [m.zanin]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='magaccettazione') DROP LOGIN [magaccettazione] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='magaccettazione') DROP SCHEMA [magaccettazione]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='magaccettazione' AND type_desc='SQL_USER') DROP USER [magaccettazione]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='magaccettazione') CREATE LOGIN [magaccettazione] WITH PASSWORD=N'mg08ctds1', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [magaccettazione] FOR LOGIN [magaccettazione]
ALTER ROLE [Metodo98] ADD MEMBER [magaccettazione]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='magcea1') DROP LOGIN [magcea1] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='magcea1') DROP SCHEMA [magcea1]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='magcea1' AND type_desc='SQL_USER') DROP USER [magcea1]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='magcea1') CREATE LOGIN [magcea1] WITH PASSWORD=N'mg08ctds1', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [magcea1] FOR LOGIN [magcea1]
ALTER ROLE [Metodo98] ADD MEMBER [magcea1]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='magcea2') DROP LOGIN [magcea2] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='magcea2') DROP SCHEMA [magcea2]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='magcea2' AND type_desc='SQL_USER') DROP USER [magcea2]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='magcea2') CREATE LOGIN [magcea2] WITH PASSWORD=N'mg08ctds1', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [magcea2] FOR LOGIN [magcea2]
ALTER ROLE [Metodo98] ADD MEMBER [magcea2]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='magcea3') DROP LOGIN [magcea3] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='magcea3') DROP SCHEMA [magcea3]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='magcea3' AND type_desc='SQL_USER') DROP USER [magcea3]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='magcea3') CREATE LOGIN [magcea3] WITH PASSWORD=N'mg08ctds1', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [magcea3] FOR LOGIN [magcea3]
ALTER ROLE [Metodo98] ADD MEMBER [magcea3]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='magcea4') DROP LOGIN [magcea4] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='magcea4') DROP SCHEMA [magcea4]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='magcea4' AND type_desc='SQL_USER') DROP USER [magcea4]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='magcea4') CREATE LOGIN [magcea4] WITH PASSWORD=N'mg08ctds1', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [magcea4] FOR LOGIN [magcea4]
ALTER ROLE [Metodo98] ADD MEMBER [magcea4]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='magcea5') DROP LOGIN [magcea5] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='magcea5') DROP SCHEMA [magcea5]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='magcea5' AND type_desc='SQL_USER') DROP USER [magcea5]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='magcea5') CREATE LOGIN [magcea5] WITH PASSWORD=N'mg08ctds1', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [magcea5] FOR LOGIN [magcea5]
ALTER ROLE [Metodo98] ADD MEMBER [magcea5]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='n.creazzo') DROP LOGIN [n.creazzo] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='n.creazzo') DROP SCHEMA [n.creazzo]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='n.creazzo' AND type_desc='SQL_USER') DROP USER [n.creazzo]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='n.creazzo') CREATE LOGIN [n.creazzo] WITH PASSWORD=N'nicolasette', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [n.creazzo] FOR LOGIN [n.creazzo]
ALTER ROLE [Metodo98] ADD MEMBER [n.creazzo]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='n.galvan') DROP LOGIN [n.galvan] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='n.galvan') DROP SCHEMA [n.galvan]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='n.galvan' AND type_desc='SQL_USER') DROP USER [n.galvan]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='n.galvan') CREATE LOGIN [n.galvan] WITH PASSWORD=N'NG0210aua', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [n.galvan] FOR LOGIN [n.galvan]
ALTER ROLE [Metodo98] ADD MEMBER [n.galvan]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='o.bonazzo') DROP LOGIN [o.bonazzo] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='o.bonazzo') DROP SCHEMA [o.bonazzo]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='o.bonazzo' AND type_desc='SQL_USER') DROP USER [o.bonazzo]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='o.bonazzo') CREATE LOGIN [o.bonazzo] WITH PASSWORD=N'giada6', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [o.bonazzo] FOR LOGIN [o.bonazzo]
ALTER ROLE [Metodo98] ADD MEMBER [o.bonazzo]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='p.mirtuono') DROP LOGIN [p.mirtuono] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='p.mirtuono') DROP SCHEMA [p.mirtuono]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='p.mirtuono' AND type_desc='SQL_USER') DROP USER [p.mirtuono]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='p.mirtuono') CREATE LOGIN [p.mirtuono] WITH PASSWORD=N'Bici247$', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [p.mirtuono] FOR LOGIN [p.mirtuono]
ALTER ROLE [Metodo98] ADD MEMBER [p.mirtuono]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='p.savio') DROP LOGIN [p.savio] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='p.savio') DROP SCHEMA [p.savio]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='p.savio' AND type_desc='SQL_USER') DROP USER [p.savio]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='p.savio') CREATE LOGIN [p.savio] WITH PASSWORD=N'P14ut08S!', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [p.savio] FOR LOGIN [p.savio]
ALTER ROLE [Metodo98] ADD MEMBER [p.savio]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='p.zoppelletto') DROP LOGIN [p.zoppelletto] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='p.zoppelletto') DROP SCHEMA [p.zoppelletto]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='p.zoppelletto' AND type_desc='SQL_USER') DROP USER [p.zoppelletto]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='p.zoppelletto') CREATE LOGIN [p.zoppelletto] WITH PASSWORD=N'p.zoppelletto', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [p.zoppelletto] FOR LOGIN [p.zoppelletto]
ALTER ROLE [Metodo98] ADD MEMBER [p.zoppelletto]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea1') DROP LOGIN [prdcea1] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='prdcea1') DROP SCHEMA [prdcea1]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='prdcea1' AND type_desc='SQL_USER') DROP USER [prdcea1]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea1') CREATE LOGIN [prdcea1] WITH PASSWORD=N'pippo123', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [prdcea1] FOR LOGIN [prdcea1]
ALTER ROLE [Metodo98] ADD MEMBER [prdcea1]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea2') DROP LOGIN [prdcea2] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='prdcea2') DROP SCHEMA [prdcea2]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='prdcea2' AND type_desc='SQL_USER') DROP USER [prdcea2]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea2') CREATE LOGIN [prdcea2] WITH PASSWORD=N'pippo123', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [prdcea2] FOR LOGIN [prdcea2]
ALTER ROLE [Metodo98] ADD MEMBER [prdcea2]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea3') DROP LOGIN [prdcea3] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='prdcea3') DROP SCHEMA [prdcea3]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='prdcea3' AND type_desc='SQL_USER') DROP USER [prdcea3]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea3') CREATE LOGIN [prdcea3] WITH PASSWORD=N'pippo123', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [prdcea3] FOR LOGIN [prdcea3]
ALTER ROLE [Metodo98] ADD MEMBER [prdcea3]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea4') DROP LOGIN [prdcea4] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='prdcea4') DROP SCHEMA [prdcea4]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='prdcea4' AND type_desc='SQL_USER') DROP USER [prdcea4]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea4') CREATE LOGIN [prdcea4] WITH PASSWORD=N'pippo123', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [prdcea4] FOR LOGIN [prdcea4]
ALTER ROLE [Metodo98] ADD MEMBER [prdcea4]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea5') DROP LOGIN [prdcea5] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='prdcea5') DROP SCHEMA [prdcea5]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='prdcea5' AND type_desc='SQL_USER') DROP USER [prdcea5]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea5') CREATE LOGIN [prdcea5] WITH PASSWORD=N'pippo123', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [prdcea5] FOR LOGIN [prdcea5]
ALTER ROLE [Metodo98] ADD MEMBER [prdcea5]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea6') DROP LOGIN [prdcea6] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='prdcea6') DROP SCHEMA [prdcea6]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='prdcea6' AND type_desc='SQL_USER') DROP USER [prdcea6]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea6') CREATE LOGIN [prdcea6] WITH PASSWORD=N'pippo123', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [prdcea6] FOR LOGIN [prdcea6]
ALTER ROLE [Metodo98] ADD MEMBER [prdcea6]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea7') DROP LOGIN [prdcea7] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='prdcea7') DROP SCHEMA [prdcea7]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='prdcea7' AND type_desc='SQL_USER') DROP USER [prdcea7]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea7') CREATE LOGIN [prdcea7] WITH PASSWORD=N'pippo123', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [prdcea7] FOR LOGIN [prdcea7]
ALTER ROLE [Metodo98] ADD MEMBER [prdcea7]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea8') DROP LOGIN [prdcea8] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='prdcea8') DROP SCHEMA [prdcea8]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='prdcea8' AND type_desc='SQL_USER') DROP USER [prdcea8]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='prdcea8') CREATE LOGIN [prdcea8] WITH PASSWORD=N'pippo123', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [prdcea8] FOR LOGIN [prdcea8]
ALTER ROLE [Metodo98] ADD MEMBER [prdcea8]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='r.cortese') DROP LOGIN [r.cortese] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='r.cortese') DROP SCHEMA [r.cortese]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='r.cortese' AND type_desc='SQL_USER') DROP USER [r.cortese]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='r.cortese') CREATE LOGIN [r.cortese] WITH PASSWORD=N'ROSETTA', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [r.cortese] FOR LOGIN [r.cortese]
ALTER ROLE [Metodo98] ADD MEMBER [r.cortese]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='r.mastrotto') DROP LOGIN [r.mastrotto] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='r.mastrotto') DROP SCHEMA [r.mastrotto]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='r.mastrotto' AND type_desc='SQL_USER') DROP USER [r.mastrotto]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='r.mastrotto') CREATE LOGIN [r.mastrotto] WITH PASSWORD=N'nP813es4', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [r.mastrotto] FOR LOGIN [r.mastrotto]
ALTER ROLE [Metodo98] ADD MEMBER [r.mastrotto]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='r.palma') DROP LOGIN [r.palma] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='r.palma') DROP SCHEMA [r.palma]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='r.palma' AND type_desc='SQL_USER') DROP USER [r.palma]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='r.palma') CREATE LOGIN [r.palma] WITH PASSWORD=N'alberto', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [r.palma] FOR LOGIN [r.palma]
ALTER ROLE [Metodo98] ADD MEMBER [r.palma]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='r.rossato') DROP LOGIN [r.rossato] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='r.rossato') DROP SCHEMA [r.rossato]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='r.rossato' AND type_desc='SQL_USER') DROP USER [r.rossato]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='r.rossato') CREATE LOGIN [r.rossato] WITH PASSWORD=N'1990paolo', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [r.rossato] FOR LOGIN [r.rossato]
ALTER ROLE [Metodo98] ADD MEMBER [r.rossato]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='s.battistella') DROP LOGIN [s.battistella] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='s.battistella') DROP SCHEMA [s.battistella]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='s.battistella' AND type_desc='SQL_USER') DROP USER [s.battistella]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='s.battistella') CREATE LOGIN [s.battistella] WITH PASSWORD=N's.battistella', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [s.battistella] FOR LOGIN [s.battistella]
ALTER ROLE [Metodo98] ADD MEMBER [s.battistella]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='s.campanella') DROP LOGIN [s.campanella] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='s.campanella') DROP SCHEMA [s.campanella]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='s.campanella' AND type_desc='SQL_USER') DROP USER [s.campanella]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='s.campanella') CREATE LOGIN [s.campanella] WITH PASSWORD=N'SC0110sbc', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [s.campanella] FOR LOGIN [s.campanella]
ALTER ROLE [Metodo98] ADD MEMBER [s.campanella]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='s.fontana') DROP LOGIN [s.fontana] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='s.fontana') DROP SCHEMA [s.fontana]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='s.fontana' AND type_desc='SQL_USER') DROP USER [s.fontana]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='s.fontana') CREATE LOGIN [s.fontana] WITH PASSWORD=N'sf0708gdp', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [s.fontana] FOR LOGIN [s.fontana]
ALTER ROLE [Metodo98] ADD MEMBER [s.fontana]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='s.tolio') DROP LOGIN [s.tolio] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='s.tolio') DROP SCHEMA [s.tolio]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='s.tolio' AND type_desc='SQL_USER') DROP USER [s.tolio]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='s.tolio') CREATE LOGIN [s.tolio] WITH PASSWORD=N'teron1977', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [s.tolio] FOR LOGIN [s.tolio]
ALTER ROLE [Metodo98] ADD MEMBER [s.tolio]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='schedulatore') DROP LOGIN [schedulatore] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='schedulatore') DROP SCHEMA [schedulatore]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='schedulatore' AND type_desc='SQL_USER') DROP USER [schedulatore]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='schedulatore') CREATE LOGIN [schedulatore] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [schedulatore] FOR LOGIN [schedulatore]
ALTER ROLE [Metodo98] ADD MEMBER [schedulatore]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='t.lanaro') DROP LOGIN [t.lanaro] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='t.lanaro') DROP SCHEMA [t.lanaro]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='t.lanaro' AND type_desc='SQL_USER') DROP USER [t.lanaro]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='t.lanaro') CREATE LOGIN [t.lanaro] WITH PASSWORD=N'tiziano', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [t.lanaro] FOR LOGIN [t.lanaro]
ALTER ROLE [Metodo98] ADD MEMBER [t.lanaro]


IF EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='v.pistininzi') DROP LOGIN [v.pistininzi] 
IF EXISTS(SELECT 1 FROM sys.schemas WHERE name='v.pistininzi') DROP SCHEMA [v.pistininzi]
IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name='v.pistininzi' AND type_desc='SQL_USER') DROP USER [v.pistininzi]
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='v.pistininzi') CREATE LOGIN [v.pistininzi] WITH PASSWORD=N'Vd11lucB', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
CREATE USER [v.pistininzi] FOR LOGIN [v.pistininzi]
ALTER ROLE [Metodo98] ADD MEMBER [v.pistininzi]


