/*DEFINIZIONE ACCESSI TOTALE ALLE CAUSALI DI MAGAZZINO PER CAUSALI NON DEFINITE*/
INSERT INTO ACCESSICAUSMAG
SELECT CM.CODICE, TA.USERID, 1, 'INPUT', CURRENT_TIMESTAMP
FROM TABCAUSALIMAG CM, TABUTENTI TA
WHERE CODICE NOT IN (SELECT DISTINCT CODCAUMAG FROM ACCESSICAUSMAG)