
-- BREVETTI CEA: RICERCA PROBLEMI MOVIMENTI CONSUNTIVAZIONE
--
-- QUESTA VISTA IDENTIFICA LE BOLLE DI LAVORAZIONE A FRONTE DELLE QUALI E' STATA INSERITA
-- ALMENO UNA NOTA CON APICE, QUINDI POTENZIALE OGGETTO DI ERRORE
CREATE VIEW BCEA_BOLLELAV_CONAPICE AS
SELECT DISTINCT TC.ANNOBOLLA, TC.NUMEROBOLLA 
	FROM 
		TDA_DETTFEEDBACK_CONSUNTIVO TC
		INNER JOIN TDA_FEEDBACK TF ON TC.RIFPROGRESSIVO = TF.PROGRESSIVO
	WHERE 
		TF.NOTELAV LIKE '%''%'
GO
		
-- PER OGNI BOLLA DI LAVORAZIONE CON POTENZIALI ERRORI VERIFICO QUALI 
-- HANNO FEEDBACK DI INIZIO IN SOSPESO
-- QUESTE SONO LE BOLLE CHE CONTENGONO I POTENZIALI ERRORI PER IL DIPENDENTE CON LA DICHIARAZIONE PENDENTE

CREATE VIEW BCEA_BOLLELAV_DAVERIFICARE_CONS AS
SELECT DISTINCT BC.ANNOBOLLA, BC.NUMEROBOLLA , TC.DIPENDENTE
	FROM
		TDA_FEEDBACK TF
		INNER JOIN TDA_DETTFEEDBACK_CONSUNTIVO TC ON TF.PROGRESSIVO = TC.RIFPROGRESSIVO
		INNER JOIN BCEA_BOLLELAV_CONAPICE BC ON TC.ANNOBOLLA = BC.ANNOBOLLA AND TC.NUMEROBOLLA = BC.NUMEROBOLLA
	WHERE
		TF.STATO = 3
		AND CAUSALE = 1
GO
		
-- QUESTI SONO LE COPPIE FEEDBACK INIZIO / FINE DA CONTROLLARE

SELECT BV.ANNOBOLLA, BV.NUMEROBOLLA, TC.DIPENDENTE, TF.DATAMODIFICA, TF.CAUSALE, TF.STATO  
	FROM 
		BCEA_BOLLELAV_DAVERIFICARE_CONS BV
		INNER JOIN TDA_DETTFEEDBACK_CONSUNTIVO TC ON BV.ANNOBOLLA = TC.ANNOBOLLA AND BV.NUMEROBOLLA = TC.NUMEROBOLLA
				   AND BV.DIPENDENTE = TC.DIPENDENTE
		INNER JOIN TDA_FEEDBACK TF ON TC.RIFPROGRESSIVO = TF.PROGRESSIVO
	WHERE
		TF.CAUSALE IN (1,2) 
	ORDER BY
		BV.ANNOBOLLA, BV.NUMEROBOLLA, TC.DIPENDENTE, TF.DATAMODIFICA

		
-- QUESTI SONO I MOVIMENTI DI CONSUNTIVAZIONE DA VERIFICARE 
-- (ALCUNI VANNO ESCLUSI, IN BASE ALLA CAUSALE)

SELECT SA.progressivo, sa.esercizio, sa.annobolla, sa.numerobolla, sa.codcausale, convert(real,sa.oremacchina)as oremacch, dl.dipendente 
	FROM
		BCEA_BOLLELAV_DAVERIFICARE_CONS BV
		INNER JOIN STORICOAVANZAMENTI SA ON BV.ANNOBOLLA = SA.ANNOBOLLA AND BV.NUMEROBOLLA = SA.NUMEROBOLLA
		INNER JOIN DIPENDENTIMOVIMENTO DL ON SA.PROGRESSIVO = DL.RIFPROGRESSIVO
		                                  AND DL.DIPENDENTE = BV.DIPENDENTE

-- QUESTI SONO I FEEDBACK DI INIZIO, ANCORA IN STATO 3, CHE POTENZIALMENTE
-- DOVREBBERO ESSERE CHIUSI PER NON GENERARE NUOVI ERRORI
-- SE SONO SEGUITI DA ALTRE DICHIARAZIONI SULLA STESSA BOLLA / DIPENDENTE, SICURAMENTE DEVONO ESSERE CHIUSI
-- (FORZARE STATO = 4)

SELECT 
	    ROW_NUMBER() OVER (PARTITION BY TC.ANNOBOLLA, TC.NUMEROBOLLA, TC.DIPENDENTE ORDER BY TC.ANNOBOLLA, TC.NUMEROBOLLA, TC.DIPENDENTE), 
		TC.ANNOBOLLA, TC.NUMEROBOLLA, TC.DIPENDENTE, TF.PROGRESSIVO, TF.DATAMODIFICA, TF.STATO  
	FROM 
		TDA_DETTFEEDBACK_CONSUNTIVO TC
		INNER JOIN TDA_FEEDBACK TF ON TC.RIFPROGRESSIVO = TF.PROGRESSIVO
	WHERE 
		TF.STATO <> 4
		AND TF.CAUSALE = 1
		AND TF.DATAMODIFICA < '17-02-2011'
ORDER BY TF.DATAMODIFICA ASC
--
-- CHIUSURA
--begin tran
--UPDATE TDA_FEEDBACK
--	SET TDA_FEEDBACK.STATO = 4
--FROM 
--		TDA_DETTFEEDBACK_CONSUNTIVO TC
--		INNER JOIN TDA_FEEDBACK TF ON TC.RIFPROGRESSIVO = TF.PROGRESSIVO
--	WHERE 
--		TF.STATO <> 4
--		AND TF.CAUSALE = 1
--		AND TF.DATAMODIFICA < '17-02-2011'
--commit tran
 CANCELLAZIONE VISTE

DROP VIEW BCEA_BOLLELAV_DAVERIFICARE_CONS
GO

DROP VIEW BCEA_BOLLELAV_CONAPICE
GO

