
-- INSERIMENTO MOVIMENTI RIPRESA A VALORE
-- DEFINIRE CAUSALE 90 RIPRESA A VALORE PRIMA DI LANCIARE LO SCRIPT

	DECLARE @VPROGRESSIVO DECIMAL(10)
	SET @VPROGRESSIVO = (SELECT ISNULL(MAX(PROGRESSIVO), 0) FROM STORICOMAG)

		INSERT STORICOMAG 	
				SELECT 
					((ROW_NUMBER() OVER(ORDER BY ARTICOLO) )+ @VPROGRESSIVO) AS [PROGRESSIVO],
					ARTICOLO			AS [CODART],
					'F   131'			AS [CODCLIFOR],
					90					AS [CODCAUSALE],
					'01/01/2009'		AS [DATAMOV],
					1					AS [QUANTITACARICO],
					1					AS [VALORECARICO],
					0					AS [QUANTITASCARICO],
					0					AS [VALORESCARICO],
					0					AS [GIACENZA],
					0					AS [ORDINATO],
					0					AS [IMPEGNATO],
					0					AS [GIACENZA2UM],
					0					AS [ORDINATO2UM],
					0					AS [IMPEGNATO2UM],
					QTA					AS [QTA1UM],
					QTA * AFC.FATTORE	AS [QTA2UM],
					0					AS [LISTINO],
					(VALORE * 1936.27)	AS [IMPORTOTOTLORDO],
					VALORE				AS [IMPORTOTOTLORDOVAL],
					VALORE				AS [IMPORTOTOTLORDOEURO],
					''					AS [SCONTO],
					(VALORE * 1936.27)	AS [IMPORTOTOTNETTO],
					VALORE				AS [IMPORTOTOTNETTOVAL],
					VALORE				AS [IMPORTOTOTNETTOEURO],
					95					AS [CODCAMBIO],
					0					AS [VALCAMBIO],
					''					AS [GENVENACQ],
					''					AS [IDDISTINTABASE],
					''					AS [NRIFDOC],
					NULL				AS [DATARIFDOC],
					''					AS [RIFERIMENTI],
					0					AS [DESTDIV],
					''					AS [NRIFPARTITA],
					''					AS [CODPAG],
					NULL				AS [PROGRCOLLEGATO],
					''					AS [CONTOCDCMOV],
					'100'				AS[CODDEPOSITO],
					''					AS [CODUBICAZIONE],
					''					AS [TIPODOC],
					0					AS [NUMERODOC],
					''					AS [BIS],
					NULL				AS [RIGADOC],
					NULL				AS [IDTESTA],
					''					AS [VARIANTE],
					0					AS [TIPOMOV],
					0					AS [RIGACOMP],
					2009				AS [ESERCIZIO],
					''					AS [CODCOMMESSA],
					'IMPORT'			AS [UTENTEMODIFICA],
					GETDATE()			AS [DATAMODIFICA],
					0					AS [ProgMovVBanco],
					'01/01/2009'		AS [DATADISP],
					0					AS [Reso],
					0					AS [RigaCauz],
					0					AS [SPESERIPMAG],
					0					AS [SPESERIPMAGVAL],
					0					AS[SPESERIPMAGEURO]
  FROM AS400_MOV_RIPRESAVAL ASM
		INNER JOIN ARTICOLIUMPREFERITE AUP ON ASM.ARTICOLO = AUP.CODART
		INNER JOIN ARTICOLIUMPREFERITE AU2 ON ASM.ARTICOLO = AU2.CODART
		INNER JOIN ARTICOLIFATTORICONVERSIONE AFC ON ASM.Articolo = AFC.CODART AND AUP.UM = AFC.UM1 and AU2.UM = AFC.UM2
  WHERE 
		AUP.TIPOUM = 1
		AND AU2.TIPOUM = 2