-- Brevetti cea 17/02/2011
-- Vista e query per la ricerca degli articoli con prelievi antecedenti i versamenti

DROP VIEW BCEA_PREL_VERS
GO

CREATE VIEW BCEA_PREL_VERS AS
SELECT  
	    SM.CODART, SM.ESERCIZIO, SM.DATAMOV, SUM(SM.CODCAUSALE) AS CODCAUSALE
	FROM 
		STORICOMAG SM
	WHERE 
		SM.CODCAUSALE IN (90,123, 122, 115, 128)
	GROUP BY 
		SM.CODART, SM.ESERCIZIO, SM.DATAMOV
GO

GRANT SELECT ON BCEA_PREL_VERS TO METODO98
GO

DROP VIEW BCEA_PREL_VERS_2
GO

CREATE VIEW BCEA_PREL_VERS_2 AS
SELECT 
	    ROW_NUMBER() OVER (PARTITION BY BV.CODART, BV.ESERCIZIO ORDER BY BV.CODART, BV.ESERCIZIO, BV.DATAMOV) AS IDMOV, 
	    BV.CODART, BV.ESERCIZIO, BV.DATAMOV, BV.CODCAUSALE
	FROM 
		BCEA_PREL_VERS BV
GO

GRANT SELECT ON BCEA_PREL_VERS_2 TO METODO98
GO


SELECT DISTINCT BV2.CODART, BV2.ESERCIZIO, BV2.DATAMOV, BV2.CODCAUSALE
	FROM BCEA_PREL_VERS_2 BV2
		INNER JOIN ANAGRAFICAARTICOLIPROD AAP ON BV2.CODART = AAP.CODICEART AND AAP.ESERCIZIO = 2011
WHERE
	BV2.IDMOV = 1 AND BV2.CODCAUSALE = 123 	AND AAP.PROVENIENZA = 1 
	AND BV2.ESERCIZIO > 2009
ORDER BY BV2.CODART, BV2.ESERCIZIO
