update anagraficaarticoli 
set descrestesa=
(select 
ltrim(rtrim((case when campo1 is null then '' else ltrim(rtrim(campo1)) end)))+' '+
ltrim(rtrim((case when campo2 is null then '' else ltrim(rtrim(campo2)) end)))+' '+
ltrim(rtrim((case when campo3 is null then '' else ltrim(rtrim(campo3)) end)))+' '+
ltrim(rtrim((case when campo4 is null then '' else ltrim(rtrim(campo4)) end)))+' '+
ltrim(rtrim((case when campo5 is null then '' else ltrim(rtrim(campo5)) end)))+' '+
ltrim(rtrim((case when campo6 is null then '' else ltrim(rtrim(campo6)) end)))+' '+
ltrim(rtrim((case when campo7 is null then '' else ltrim(rtrim(campo7)) end)))+' '+
ltrim(rtrim((case when campo8 is null then '' else ltrim(rtrim(campo8)) end)))+' '+
ltrim(rtrim((case when campo9 is null then '' else ltrim(rtrim(campo9)) end)))+' '+
ltrim(rtrim((case when campo10 is null then '' else ltrim(rtrim(campo10)) end)))+' '+
ltrim(rtrim((case when campo11 is null then '' else ltrim(rtrim(campo11)) end)))+' '+
ltrim(rtrim((case when campo12 is null then '' else ltrim(rtrim(campo12)) end)))+' '+
ltrim(rtrim((case when campo13 is null then '' else ltrim(rtrim(campo13)) end)))+' '+
ltrim(rtrim((case when campo14 is null then '' else ltrim(rtrim(campo14)) end)))+' '+
ltrim(rtrim((case when campo15 is null then '' else ltrim(rtrim(campo15)) end)))+' '+
ltrim(rtrim((case when campo16 is null then '' else ltrim(rtrim(campo16)) end)))+' '+
ltrim(rtrim((case when campo17 is null then '' else ltrim(rtrim(campo17)) end)))+' '+
ltrim(rtrim((case when campo18 is null then '' else ltrim(rtrim(campo18)) end)))+' '+
ltrim(rtrim((case when campo19 is null then '' else ltrim(rtrim(campo19)) end)))+' '+
ltrim(rtrim((case when campo20 is null then '' else ltrim(rtrim(campo20)) end)))+' '+
ltrim(rtrim((case when campo21 is null then '' else ltrim(rtrim(campo21)) end)))+' '+
ltrim(rtrim((case when campo22 is null then '' else ltrim(rtrim(campo22)) end)))+' '+
ltrim(rtrim((case when campo23 is null then '' else ltrim(rtrim(campo23)) end)))+' '+
ltrim(rtrim((case when campo24 is null then '' else ltrim(rtrim(campo24)) end)))+' '+
ltrim(rtrim((case when campo25 is null then '' else ltrim(rtrim(campo25)) end)))+' '+
ltrim(rtrim((case when campo26 is null then '' else ltrim(rtrim(campo26)) end)))+' '+
ltrim(rtrim((case when campo27 is null then '' else ltrim(rtrim(campo27)) end)))+' '+
ltrim(rtrim((case when campo28 is null then '' else ltrim(rtrim(campo28)) end)))+' '+
ltrim(rtrim((case when campo29 is null then '' else ltrim(rtrim(campo29)) end)))+' '+
ltrim(rtrim((case when campo30 is null then '' else ltrim(rtrim(campo30)) end)))+' '+
ltrim(rtrim((case when campo31 is null then '' else ltrim(rtrim(campo31)) end)))+' '+
ltrim(rtrim((case when campo32 is null then '' else ltrim(rtrim(campo32)) end)))+' '+
ltrim(rtrim((case when campo33 is null then '' else ltrim(rtrim(campo33)) end)))+' '+
ltrim(rtrim((case when campo34 is null then '' else ltrim(rtrim(campo34)) end)))+' '+
ltrim(rtrim((case when campo35 is null then '' else ltrim(rtrim(campo35)) end)))+' '+
ltrim(rtrim((case when campo36 is null then '' else ltrim(rtrim(campo36)) end)))+' '+
ltrim(rtrim((case when campo37 is null then '' else ltrim(rtrim(campo37)) end)))+' '+
ltrim(rtrim((case when campo38 is null then '' else ltrim(rtrim(campo38)) end)))+' '+
ltrim(rtrim((case when campo39 is null then '' else ltrim(rtrim(campo39)) end)))+' '+
ltrim(rtrim((case when campo40 is null then '' else ltrim(rtrim(campo40)) end)))+' '+
ltrim(rtrim((case when campo41 is null then '' else ltrim(rtrim(campo41)) end)))+' '+
ltrim(rtrim((case when campo42 is null then '' else ltrim(rtrim(campo42)) end)))+' '+
ltrim(rtrim((case when campo43 is null then '' else ltrim(rtrim(campo43)) end)))+' '+
ltrim(rtrim((case when campo44 is null then '' else ltrim(rtrim(campo44)) end)))+' '+
ltrim(rtrim((case when campo45 is null then '' else ltrim(rtrim(campo45)) end)))+' '+
ltrim(rtrim((case when campo46 is null then '' else ltrim(rtrim(campo46)) end)))+' '+
ltrim(rtrim((case when campo47 is null then '' else ltrim(rtrim(campo47)) end)))+' '+
ltrim(rtrim((case when campo48 is null then '' else ltrim(rtrim(campo48)) end)))+' '+
ltrim(rtrim((case when campo49 is null then '' else ltrim(rtrim(campo49)) end)))+' '+
ltrim(rtrim((case when campo50 is null then '' else ltrim(rtrim(campo50)) end)))+' '+
ltrim(rtrim((case when campo51 is null then '' else ltrim(rtrim(campo51)) end)))+' '+
ltrim(rtrim((case when campo52 is null then '' else ltrim(rtrim(campo52)) end)))+' '+
ltrim(rtrim((case when campo53 is null then '' else ltrim(rtrim(campo53)) end)))+' '+
ltrim(rtrim((case when campo54 is null then '' else ltrim(rtrim(campo54)) end)))+' '+
ltrim(rtrim((case when campo55 is null then '' else ltrim(rtrim(campo55)) end)))+' '+
ltrim(rtrim((case when campo56 is null then '' else ltrim(rtrim(campo56)) end)))+' '+
ltrim(rtrim((case when campo57 is null then '' else ltrim(rtrim(campo57)) end)))+' '+
ltrim(rtrim((case when campo58 is null then '' else ltrim(rtrim(campo58)) end)))+' '+
ltrim(rtrim((case when campo59 is null then '' else ltrim(rtrim(campo59)) end)))+' '+
ltrim(rtrim((case when campo60 is null then '' else ltrim(rtrim(campo60)) end)))+' '+
ltrim(rtrim((case when campo61 is null then '' else ltrim(rtrim(campo61)) end)))+' '+
ltrim(rtrim((case when campo62 is null then '' else ltrim(rtrim(campo62)) end)))+' '+
ltrim(rtrim((case when campo63 is null then '' else ltrim(rtrim(campo63)) end)))+' '+
ltrim(rtrim((case when campo64 is null then '' else ltrim(rtrim(campo64)) end)))+' '+
ltrim(rtrim((case when campo65 is null then '' else ltrim(rtrim(campo65)) end)))+' '+
ltrim(rtrim((case when campo66 is null then '' else ltrim(rtrim(campo66)) end)))+' '+
ltrim(rtrim((case when campo67 is null then '' else ltrim(rtrim(campo67)) end)))+' '+
ltrim(rtrim((case when campo68 is null then '' else ltrim(rtrim(campo68)) end)))+' '+
ltrim(rtrim((case when campo69 is null then '' else ltrim(rtrim(campo69)) end)))+' '+
ltrim(rtrim((case when campo70 is null then '' else ltrim(rtrim(campo70)) end)))+' '+
ltrim(rtrim((case when campo71 is null then '' else ltrim(rtrim(campo71)) end)))+' '+
ltrim(rtrim((case when campo72 is null then '' else ltrim(rtrim(campo72)) end)))+' '+
ltrim(rtrim((case when campo73 is null then '' else ltrim(rtrim(campo73)) end)))+' '+
ltrim(rtrim((case when campo74 is null then '' else ltrim(rtrim(campo74)) end)))+' '+
ltrim(rtrim((case when campo75 is null then '' else ltrim(rtrim(campo75)) end)))+' '+
ltrim(rtrim((case when campo76 is null then '' else ltrim(rtrim(campo76)) end)))+' '+
ltrim(rtrim((case when campo77 is null then '' else ltrim(rtrim(campo77)) end)))+' '+
ltrim(rtrim((case when campo78 is null then '' else ltrim(rtrim(campo78)) end)))+' '+
ltrim(rtrim((case when campo79 is null then '' else ltrim(rtrim(campo79)) end)))+' '+
ltrim(rtrim((case when campo80 is null then '' else ltrim(rtrim(campo80)) end)))+' '+
ltrim(rtrim((case when campo81 is null then '' else ltrim(rtrim(campo81)) end)))+' '+
ltrim(rtrim((case when campo82 is null then '' else ltrim(rtrim(campo82)) end)))+' '+
ltrim(rtrim((case when campo83 is null then '' else ltrim(rtrim(campo83)) end)))+' '+
ltrim(rtrim((case when campo84 is null then '' else ltrim(rtrim(campo84)) end)))+' '+
ltrim(rtrim((case when campo85 is null then '' else ltrim(rtrim(campo85)) end)))+' '+
ltrim(rtrim((case when campo86 is null then '' else ltrim(rtrim(campo86)) end)))+' '+
ltrim(rtrim((case when campo87 is null then '' else ltrim(rtrim(campo87)) end)))+' '+
ltrim(rtrim((case when campo88 is null then '' else ltrim(rtrim(campo88)) end)))+' '+
ltrim(rtrim((case when campo89 is null then '' else ltrim(rtrim(campo89)) end)))+' '+
ltrim(rtrim((case when campo90 is null then '' else ltrim(rtrim(campo90)) end)))+' '+
ltrim(rtrim((case when campo91 is null then '' else ltrim(rtrim(campo91)) end)))+' '+
ltrim(rtrim((case when campo92 is null then '' else ltrim(rtrim(campo92)) end)))+' '+
ltrim(rtrim((case when campo93 is null then '' else ltrim(rtrim(campo93)) end)))+' '+
ltrim(rtrim((case when campo94 is null then '' else ltrim(rtrim(campo94)) end)))+' '+
ltrim(rtrim((case when campo95 is null then '' else ltrim(rtrim(campo95)) end)))
from 
new_descrarticoli where codart=anagraficaarticoli.codice)