

-- ELSA 19 MARZO 2009
-- SELEZIONA LE SCRITTURA DI PRIMA NOTA CON COMPETENZA DIVERSA DAL MESE DI REGISTRAZIONE

SELECT 2 as MESENEW,cast(ANNO as varchar(4))+'02' as ANNOMESENEW,MESE,ANNO,ANNOMESE,* from COMPETENZEPN WHERE (select MONTH(datareg) from TESTECONTABILITA where PROGRESSIVO=NRREG)=2


-- AGGIORNA LE SCRITTURA DI PRIMA NOTA CON COMPETENZA DIVERSA DAL MESE DI REGISTRAZIONE
UPDATE COMPETENZEPN SET MESE=2,ANNOMESE=cast(ANNO as varchar(4))+'02' WHERE (select MONTH(datareg) from TESTECONTABILITA where PROGRESSIVO=NRREG)=2

