/*Modifica vista depositi in fase di pianificazione materiali*/
ALTER VIEW [dbo].[VISTADEPOSITIPROGPROD]
AS SELECT
	CODICE,DESCRIZIONE,(CASE WHEN PROPONIMRP=1 THEN 1 ELSE 0 END) AS DISPONIBILE,TIPODEPOSITO,DATAINIVALIDITA,DATAFINEVALIDITA
FROM
	ANAGRAFICADEPOSITI AD 
	INNER JOIN EXTRADEPOSITI ED
		ON AD.CODICE=ED.CODDEPOSITO
GO
