
DECLARE @VERSAMENTIDOPPI AS TABLE
(RIFTESTA DECIMAL(10,0), RIFRIGA INT, NRMOVIMENTI INT, QTAMOVGESTIONE DECIMAL(19,6), QTAVERSATA DECIMAL(19,6))

INSERT INTO @VERSAMENTIDOPPI
SELECT RIFTESTA, RIFRIGA, COUNT(RIFTESTA) AS NRMOVIMENTI, QTAMOVGESTIONE, SUM(QTAMOVGESTIONE)
FROM STORICOMOVORDPROD SMOP
LEFT OUTER JOIN RIGHEORDPROD ROP
	ON SMOP.RIFTESTA=ROP.IDTESTA
	AND SMOP.RIFRIGA=ROP.IDRIGA
WHERE --ROP.CODICEORD='OP1'
--AND 
SMOP.QTAMOVGESTIONE <>0
GROUP BY RIFTESTA, RIFRIGA, QTAMOVGESTIONE
HAVING COUNT(RIFTESTA)>1
ORDER BY RIFTESTA, RIFRIGA

SELECT SMOP.NOTE, SMOP.DATAMODIFICA, ROP.CODART, SMOP.RIFPROGRESSIVO, TEMP.RIFTESTA, TEMP.RIFRIGA, TEMP.NRMOVIMENTI,
REPLACE(TEMP.QTAMOVGESTIONE,'.',',') AS QTAMOVGESTIONE, REPLACE(TEMP.QTAVERSATA,'.',',') AS QTAVERSATA, REPLACE(ROP.QTAGESTIONE,'.',',') AS QTAORDINE,
(SELECT TOP 1 'SI' FROM STORICOMAG WHERE CODART=ROP.CODART AND CODCAUSALE IN (200,201) AND DATAMOV>=SMP.DATAMOV) AS INVENTARIO
FROM STORICOMOVORDPROD SMOP
INNER JOIN @VERSAMENTIDOPPI TEMP
	ON SMOP.RIFTESTA=TEMP.RIFTESTA
	AND SMOP.RIFRIGA=TEMP.RIFRIGA
	AND SMOP.QTAMOVGESTIONE=TEMP.QTAMOVGESTIONE
LEFT OUTER JOIN RIGHEORDPROD ROP
	ON SMOP.RIFTESTA=ROP.IDTESTA
	AND SMOP.RIFRIGA=ROP.IDRIGA
LEFT OUTER JOIN STORICOMOVPROD SMP
	ON SMOP.RIFPROGRESSIVO=SMP.PROGRESSIVO
ORDER BY SMOP.RIFTESTA, SMOP.RIFRIGA
