select tiporecord, statoimpegnoas, *
from as400_impegniordprod_norm
where tiporecord='s' and (qtaimp-qtaprelevata>0)

--CONTROLLO IMPEGNI DA CHIUDERE
SELECT IOP.CODART, TEMP.CODART, IOP.IDIMPEGNO, TEMP.IDIMPEGNO, *
FROM IMPEGNIORDPROD IOP
INNER JOIN AS400_IMPEGNIMETODO TEMP
ON IOP.IDTESTA=TEMP.IDTESTA 
	AND IOP.IDRIGA=TEMP.IDRIGA 
	AND IOP.IDIMPEGNO=TEMP.IDIMPEGNO
WHERE TEMP.TIPORECORD='S'
AND IOP.STATOIMPEGNO <> 2
AND LEFT(IOP.NOTE,8) = 61609000
AND IOP.CODART<>TEMP.CODART


--UPDATE
UPDATE IMPEGNIORDPROD
SET STATOIMPEGNO=2
FROM IMPEGNIORDPROD IOP
RIGHT OUTER JOIN RIGHEORDPROD ROP
	ON IOP.IDTESTA=ROP.IDTESTA AND IOP.IDRIGA=ROP.IDRIGA
LEFT OUTER JOIN TESTEORDINIPROD TORP
	ON ROP.IDTESTA=TORP.PROGRESSIVO 
LEFT OUTER JOIN AS400_IMPEGNIMETODO TEMP
ON IOP.IDTESTA=TEMP.IDTESTACOMM 
	AND IOP.IDRIGA=TEMP.IDRIGACOMM 
	AND IOP.IDIMPEGNO=TEMP.IDIMPEGNO
WHERE TEMP.TIPORECORD='S'
AND STATOIMPEGNO <> 2
AND TEMP.NUMORD = 61609000


--CANCELLAZIONE IMPEGNI 
SELECT *
FROM IMPEGNIORDPROD IOP
LEFT OUTER JOIN STORICOMAG SM
ON IOP.IDTESTA=SM.IDTESTA AND IOP.IDRIGA=SM.RIGADOC AND IOP.IDIMPEGNO=SM.RIGACOMP
LEFT OUTER JOIN ANAGRAFICAARTICOLI AA
ON IOP.CODART=AA.CODICE
WHERE IOP.STATOIMPEGNO <>2
AND SM.PROGRESSIVO IS NULL
AND AA.AGGIORNAMAG = 1


--DELETE
--DELETE STORICMAG
FROM IMPEGNIORDPROD IOP
LEFT OUTER JOIN STORICOMAG SM
ON IOP.IDTESTA=SM.IDTESTA AND IOP.IDRIGA=SM.RIGADOC AND IOP.IDIMPEGNO=SM.RIGACOMP
LEFT OUTER JOIN ANAGRAFICAARTICOLI AA
ON IOP.CODART=AA.CODICE
WHERE IOP.STATOIMPEGNO <>2
AND SM.PROGRESSIVO IS NULL
AND AA.AGGIORNAMAG = 1


SELECT *
FROM IMPEGNIORDPROD














SELECT *
FROM TESTEORDINIPROD
WHERE PROGRESSIVO = 194


SELECT *
FROM AS400_IMPEGNIORDPROD_NORM
WHERE NUMORD =68575000 

select tiporecord, *
from AS400_IMPEGNIORDPROD_NORM
group by tiporecord

SELECT *
FROM IMPEGNIORDPROD