/*DELETE LISTINI*/
SELECT *
FROM TABLISTINI

SELECT DISTINCT(NRLISTINO)
FROM LISTINIARTICOLI
ORDER BY NRLISTINO

SELECT *
FROM LISTINIARTICOLI
WHERE NRLISTINO >= 99
ORDER BY NRLISTINO

DELETE LISTINIARTICOLI
WHERE NRLISTINO >= 99

/*DELETE PREZZI PARTICOLARI*/
SELECT *
FROM GESTIONEPREZZI

DELETE GESTIONEPREZZI

SELECT *
FROM GESTIONEPREZZIRIGHE

DELETE GESTIONEPREZZIRIGHE

/*DELETE STORICO PREZZI*/
SELECT *
FROM STORICOPREZZIARTICOLO
WHERE TIPOPREZZO = 'F'
ORDER BY DATAMODIFICA DESC

DELETE STORICOPREZZIARTICOLO

/*AZZERAMENTO LISTINO IN ANAGRAFICA LISTINI*/
SELECT LISTINO, *
FROM ANAGRAFICARISERVATICF
ORDER BY LISTINO DESC

UPDATE ANAGRAFICARISERVATICF
SET LISTINO = 0
WHERE LEFT(CODCONTO,1)='F'

/*DELETE LISTINIARTICOLI*/
SELECT *
FROM TABLISTINI
WHERE NRLISTINO > 10000

DELETE TABLISTINI
WHERE NRLISTINO > 10000

