/*2009/02/16 GR - Aggiunta campo extra depositi*/
ALTER TABLE EXTRADEPOSITI
ADD PROPONIMRP INT DEFAULT 0  NOT NULL 
GO

ALTER TABLE EXTRADEPOSITI
ADD CONSTRAINT PROPONIMRP_CHECK CHECK(PROPONIMRP In (0,1))
GO

INSERT INTO EXTRADEPOSITI
SELECT CODICE, 'INPUT', CURRENT_TIMESTAMP, 0
FROM ANAGRAFICADEPOSITI
GO