CREATE FUNCTION DBO.GR_FUNUBICAZDEFAULT
(
	@CODART VARCHAR(80),
	@CODDEPOSITO VARCHAR(10)
)
RETURNS VARCHAR
AS
BEGIN
	-- Declare the return variable here
	DECLARE @UBICAZIONE AS VARCHAR(10)

	-- Add the T-SQL statements to compute the return value here
	SELECT TOP 1 @UBICAZIONE=CODUBICAZIONE
	FROM UBICAZIONIARTICOLI
	WHERE CODICEART=@CODART
	AND CODDEPOSITO=@CODDEPOSITO
	ORDER BY NRRIGA

	-- Return the result of the function
	RETURN @UBICAZIONE

END
GO

GRANT EXECUTE ON DBO.GR_FUNUBICAZDEFAULT TO METODO98
GO
