SELECT ROP.CODART, AA.DESCRIZIONE
FROM TESTEORDINIPROD TORP
LEFT OUTER JOIN RIGHEORDPROD ROP
	ON TORP.PROGRESSIVO=ROP.IDTESTA
LEFT OUTER JOIN ANAGRAFICAARTICOLI AA
	ON ROP.CODART=AA.CODICE
WHERE AA.AGGIORNAMAG= 0
AND ROP.STATOORDINE<>3
GROUP BY CODART, DESCRIZIONE

SELECT ESERCIZIO,TIPOCOM, NUMEROCOM, ROP.CODART
FROM TESTEORDINIPROD TORP
LEFT OUTER JOIN RIGHEORDPROD ROP
	ON TORP.PROGRESSIVO=ROP.IDTESTA
LEFT OUTER JOIN ANAGRAFICAARTICOLI AA
	ON ROP.CODART=AA.CODICE
WHERE AA.AGGIORNAMAG= 0
AND ROP.STATOORDINE<>3
ORDER BY ESERCIZIO,TIPOCOM, NUMEROCOM

UPDATE ANAGRAFICAARTICOLI
SET AGGIORNAMAG=1
FROM TESTEORDINIPROD TORP
LEFT OUTER JOIN RIGHEORDPROD ROP
	ON TORP.PROGRESSIVO=ROP.IDTESTA
LEFT OUTER JOIN ANAGRAFICAARTICOLI AA
	ON ROP.CODART=AA.CODICE
WHERE AA.AGGIORNAMAG= 0
AND ROP.STATOORDINE<>3

