/*PROCEDURA DI AGGIORNAMENTO DATI RIORDINO ANAGRAFICA ARTICOLI*/

--PROVENIENZA 0 = ACQUISTO
SELECT *
FROM TABLOTTIRIORDINO TLR
	LEFT OUTER JOIN ANAGRAFICAARTICOLIPROD AAP
		ON TLR.CODART=AAP.CODICEART AND TLR.CODFOR=AAP.FORNPREFACQ AND ESERCIZIO = 2009
	WHERE TIPORIORD = 0
	AND FORNPREFACQ IS NOT NULL

BEGIN TRAN
	UPDATE TABLOTTIRIORDINO
	SET LOTTORIF=LOTTORIFACQ,
		QTAMINIMA=QMINRIORDACQ,
		QTAMASSIMA=QMAXRIORDACQ,
		QTADELTA=QDELTARIORDACQ,
		GGAPPROVV=TAPPROVVACQ,
		GGAPPRONT=TAPPRONTACQ,
		ARROTLOTTO=ARROTLOTTOACQ	
	FROM TABLOTTIRIORDINO TLR
	LEFT OUTER JOIN ANAGRAFICAARTICOLIPROD AAP
		ON TLR.CODART=AAP.CODICEART AND TLR.CODFOR=AAP.FORNPREFACQ AND ESERCIZIO = 2009
	WHERE TIPORIORD = 0
	AND FORNPREFACQ IS NOT NULL
COMMIT TRAN

