/*Aggiornamento */

--delete anagraficacommesse

--Copia anagrafica commesse da ditta effettiva
INSERT INTO ANAGRAFICACOMMESSE
SELECT *
FROM BRECEA.DBO.ANAGRAFICACOMMESSE

--Allineamento riferimento commessa cliente su righe ordini di produzione.

--Controllo riferimenti commessa cliente su anagrafica commesse.
SELECT *
FROM ANAGRAFICACOMMESSE

SELECT RIFCOMM, RIFERIMENTO, 'AS400 ' + LEFT(RIFCOMM,5), *
FROM ANAGRAFICACOMMESSE
WHERE RIFERIMENTO NOT LIKE '%AS400%' AND RIFCOMM LIKE 'Y%'

UPDATE ANAGRAFICACOMMESSE
SET RIFERIMENTO = 'AS400 ' + LEFT(RIFCOMM,5)
FROM ANAGRAFICACOMMESSE
WHERE RIFERIMENTO NOT LIKE '%AS400%' AND RIFCOMM LIKE 'Y%'

SELECT RIFCOMMCLI AS RIFCOMMCLI_ORD, RIFERIMENTO AS RIF_ANA_COMM, RIFCOMM AS RIFCOMMCLI_METODO
FROM RIGHEORDPROD ROP
LEFT OUTER JOIN ANAGRAFICACOMMESSE AC
	ON ROP.RIFCOMMCLI=RIGHT(AC.RIFERIMENTO,5)
WHERE RIFCOMMCLI <>'' AND ROP.UTENTEMODIFICA = 'IMPORT'
AND RIFERIMENTO IS NULL
GROUP BY RIFCOMMCLI,RIFERIMENTO, RIFCOMM
ORDER BY RIFCOMMCLI

UPDATE TESTEORDINIPROD
SET RIFCOMMCLI=RIFCOMM
FROM TESTEORDINIPROD TORP
LEFT OUTER JOIN ANAGRAFICACOMMESSE AC
	ON TORP.RIFCOMMCLI=RIGHT(AC.RIFERIMENTO,5)
WHERE RIFCOMMCLI <>'' AND TORP.UTENTEMODIFICA = 'IMPORT'

UPDATE RIGHEORDPROD
SET RIFCOMMCLI=RIFCOMM
FROM RIGHEORDPROD ROP
LEFT OUTER JOIN ANAGRAFICACOMMESSE AC
	ON ROP.RIFCOMMCLI=RIGHT(AC.RIFERIMENTO,5)
WHERE RIFCOMMCLI <>'' AND ROP.UTENTEMODIFICA = 'IMPORT'

UPDATE IMPEGNIORDPROD
SET RIFCOMMCLI=RIFCOMM
FROM IMPEGNIORDPROD IOP
LEFT OUTER JOIN ANAGRAFICACOMMESSE AC
	ON IOP.RIFCOMMCLI=RIGHT(AC.RIFERIMENTO,5)
WHERE RIFCOMMCLI <>'' AND IOP.UTENTEMODIFICA = 'IMPORT'


SELECT RIFERIMENTI, CODCOMMESSA,*
FROM STORICOMAG
WHERE TIPOMOV > 4