BEGIN TRAN

DELETE ACCESSICAUSMAG
GO

INSERT INTO ACCESSICAUSMAG
SELECT CODICE, USERID, 1, 'INPUT', CURRENT_TIMESTAMP 
FROM TABCAUSALIMAG, TABUTENTI

DELETE ACCESSICAUSMAG
WHERE NOMEUTENTE IN (SELECT USERID FROM TABUTENTI WHERE SUPERVISOR = 1)

COMMIT TRAN




