IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='ADMIN')
	CREATE LOGIN [ADMIN] WITH PASSWORD=N'metodo', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM1')
	CREATE LOGIN [TRM1] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM2')
	CREATE LOGIN [TRM2] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM3')
	CREATE LOGIN [TRM3] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM4')
	CREATE LOGIN [TRM4] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM5')
	CREATE LOGIN [TRM5] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM6')
	CREATE LOGIN [TRM6] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM7')
	CREATE LOGIN [TRM7] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM8')
	CREATE LOGIN [TRM8] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM9')
	CREATE LOGIN [TRM9] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM10')
	CREATE LOGIN [TRM10] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM11')
	CREATE LOGIN [TRM11] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM12')
	CREATE LOGIN [TRM12] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM13')
	CREATE LOGIN [TRM13] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM14')
	CREATE LOGIN [TRM14] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM15')
	CREATE LOGIN [TRM15] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM16')
	CREATE LOGIN [TRM16] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM17')
	CREATE LOGIN [TRM17] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM18')
	CREATE LOGIN [TRM18] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM19')
	CREATE LOGIN [TRM19] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM20')
	CREATE LOGIN [TRM20] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM21')
	CREATE LOGIN [TRM21] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM22')
	CREATE LOGIN [TRM22] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM23')
	CREATE LOGIN [TRM23] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM24')
	CREATE LOGIN [TRM24] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM25')
	CREATE LOGIN [TRM25] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM26')
	CREATE LOGIN [TRM26] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM27')
	CREATE LOGIN [TRM27] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM28')
	CREATE LOGIN [TRM28] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM29')
	CREATE LOGIN [TRM29] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM30')
	CREATE LOGIN [TRM30] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM31')
	CREATE LOGIN [TRM31] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM32')
	CREATE LOGIN [TRM32] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM33')
	CREATE LOGIN [TRM33] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM34')
	CREATE LOGIN [TRM34] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM35')
	CREATE LOGIN [TRM35] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM36')
	CREATE LOGIN [TRM36] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM37')
	CREATE LOGIN [TRM37] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM38')
	CREATE LOGIN [TRM38] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM39')
	CREATE LOGIN [TRM39] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM40')
	CREATE LOGIN [TRM40] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM41')
	CREATE LOGIN [TRM41] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM42')
	CREATE LOGIN [TRM42] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM43')
	CREATE LOGIN [TRM43] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM44')
	CREATE LOGIN [TRM44] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM45')
	CREATE LOGIN [TRM45] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM46')
	CREATE LOGIN [TRM46] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM47')
	CREATE LOGIN [TRM47] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM48')
	CREATE LOGIN [TRM48] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM49')
	CREATE LOGIN [TRM49] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM50')
	CREATE LOGIN [TRM50] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM51')
	CREATE LOGIN [TRM51] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM52')
	CREATE LOGIN [TRM52] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM53')
	CREATE LOGIN [TRM53] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM54')
	CREATE LOGIN [TRM54] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM55')
	CREATE LOGIN [TRM55] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM56')
	CREATE LOGIN [TRM56] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM57')
	CREATE LOGIN [TRM57] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM58')
	CREATE LOGIN [TRM58] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM59')
	CREATE LOGIN [TRM59] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM60')
	CREATE LOGIN [TRM60] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM61')
	CREATE LOGIN [TRM61] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM62')
	CREATE LOGIN [TRM62] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM63')
	CREATE LOGIN [TRM63] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM64')
	CREATE LOGIN [TRM64] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM65')
	CREATE LOGIN [TRM65] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM66')
	CREATE LOGIN [TRM66] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM67')
	CREATE LOGIN [TRM67] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM68')
	CREATE LOGIN [TRM68] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM69')
	CREATE LOGIN [TRM69] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM70')
	CREATE LOGIN [TRM70] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM71')
	CREATE LOGIN [TRM71] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM72')
	CREATE LOGIN [TRM72] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM73')
	CREATE LOGIN [TRM73] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM74')
	CREATE LOGIN [TRM74] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM75')
	CREATE LOGIN [TRM75] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM76')
	CREATE LOGIN [TRM76] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM77')
	CREATE LOGIN [TRM77] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM78')
	CREATE LOGIN [TRM78] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM79')
	CREATE LOGIN [TRM79] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM80')
	CREATE LOGIN [TRM80] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM81')
	CREATE LOGIN [TRM81] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM82')
	CREATE LOGIN [TRM82] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM83')
	CREATE LOGIN [TRM83] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM84')
	CREATE LOGIN [TRM84] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM85')
	CREATE LOGIN [TRM85] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM86')
	CREATE LOGIN [TRM86] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM87')
	CREATE LOGIN [TRM87] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM88')
	CREATE LOGIN [TRM88] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM89')
	CREATE LOGIN [TRM89] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM90')
	CREATE LOGIN [TRM90] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM91')
	CREATE LOGIN [TRM91] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM92')
	CREATE LOGIN [TRM92] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM93')
	CREATE LOGIN [TRM93] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM94')
	CREATE LOGIN [TRM94] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM95')
	CREATE LOGIN [TRM95] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM96')
	CREATE LOGIN [TRM96] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM97')
	CREATE LOGIN [TRM97] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM98')
	CREATE LOGIN [TRM98] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM99')
	CREATE LOGIN [TRM99] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM100')
	CREATE LOGIN [TRM100] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM101')
	CREATE LOGIN [TRM101] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM102')
	CREATE LOGIN [TRM102] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM103')
	CREATE LOGIN [TRM103] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM104')
	CREATE LOGIN [TRM104] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM105')
	CREATE LOGIN [TRM105] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM106')
	CREATE LOGIN [TRM106] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM107')
	CREATE LOGIN [TRM107] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM108')
	CREATE LOGIN [TRM108] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM109')
	CREATE LOGIN [TRM109] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM110')
	CREATE LOGIN [TRM110] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM111')
	CREATE LOGIN [TRM111] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM112')
	CREATE LOGIN [TRM112] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM113')
	CREATE LOGIN [TRM113] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM114')
	CREATE LOGIN [TRM114] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM115')
	CREATE LOGIN [TRM115] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM116')
	CREATE LOGIN [TRM116] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM117')
	CREATE LOGIN [TRM117] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM118')
	CREATE LOGIN [TRM118] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM119')
	CREATE LOGIN [TRM119] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM120')
	CREATE LOGIN [TRM120] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM121')
	CREATE LOGIN [TRM121] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM122')
	CREATE LOGIN [TRM122] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM123')
	CREATE LOGIN [TRM123] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM124')
	CREATE LOGIN [TRM124] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM125')
	CREATE LOGIN [TRM125] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM126')
	CREATE LOGIN [TRM126] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM127')
	CREATE LOGIN [TRM127] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM128')
	CREATE LOGIN [TRM128] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM129')
	CREATE LOGIN [TRM129] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM130')
	CREATE LOGIN [TRM130] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM131')
	CREATE LOGIN [TRM131] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM132')
	CREATE LOGIN [TRM132] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM133')
	CREATE LOGIN [TRM133] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM134')
	CREATE LOGIN [TRM134] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM135')
	CREATE LOGIN [TRM135] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM136')
	CREATE LOGIN [TRM136] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM137')
	CREATE LOGIN [TRM137] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM138')
	CREATE LOGIN [TRM138] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM139')
	CREATE LOGIN [TRM139] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM140')
	CREATE LOGIN [TRM140] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM141')
	CREATE LOGIN [TRM141] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM142')
	CREATE LOGIN [TRM142] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM143')
	CREATE LOGIN [TRM143] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM144')
	CREATE LOGIN [TRM144] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM145')
	CREATE LOGIN [TRM145] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM146')
	CREATE LOGIN [TRM146] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM147')
	CREATE LOGIN [TRM147] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM148')
	CREATE LOGIN [TRM148] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM149')
	CREATE LOGIN [TRM149] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM150')
	CREATE LOGIN [TRM150] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM151')
	CREATE LOGIN [TRM151] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM152')
	CREATE LOGIN [TRM152] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM153')
	CREATE LOGIN [TRM153] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM154')
	CREATE LOGIN [TRM154] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM155')
	CREATE LOGIN [TRM155] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM156')
	CREATE LOGIN [TRM156] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM157')
	CREATE LOGIN [TRM157] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM158')
	CREATE LOGIN [TRM158] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM159')
	CREATE LOGIN [TRM159] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM160')
	CREATE LOGIN [TRM160] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM161')
	CREATE LOGIN [TRM161] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM162')
	CREATE LOGIN [TRM162] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM163')
	CREATE LOGIN [TRM163] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM164')
	CREATE LOGIN [TRM164] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM165')
	CREATE LOGIN [TRM165] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM166')
	CREATE LOGIN [TRM166] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM167')
	CREATE LOGIN [TRM167] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM168')
	CREATE LOGIN [TRM168] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM169')
	CREATE LOGIN [TRM169] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM170')
	CREATE LOGIN [TRM170] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM171')
	CREATE LOGIN [TRM171] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM172')
	CREATE LOGIN [TRM172] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM173')
	CREATE LOGIN [TRM173] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM174')
	CREATE LOGIN [TRM174] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM175')
	CREATE LOGIN [TRM175] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM176')
	CREATE LOGIN [TRM176] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM177')
	CREATE LOGIN [TRM177] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM178')
	CREATE LOGIN [TRM178] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM179')
	CREATE LOGIN [TRM179] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM180')
	CREATE LOGIN [TRM180] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM181')
	CREATE LOGIN [TRM181] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM182')
	CREATE LOGIN [TRM182] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM183')
	CREATE LOGIN [TRM183] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM184')
	CREATE LOGIN [TRM184] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM185')
	CREATE LOGIN [TRM185] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM186')
	CREATE LOGIN [TRM186] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM187')
	CREATE LOGIN [TRM187] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM188')
	CREATE LOGIN [TRM188] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM189')
	CREATE LOGIN [TRM189] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM190')
	CREATE LOGIN [TRM190] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM191')
	CREATE LOGIN [TRM191] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM192')
	CREATE LOGIN [TRM192] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM193')
	CREATE LOGIN [TRM193] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM194')
	CREATE LOGIN [TRM194] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM195')
	CREATE LOGIN [TRM195] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM196')
	CREATE LOGIN [TRM196] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM197')
	CREATE LOGIN [TRM197] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM198')
	CREATE LOGIN [TRM198] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM199')
	CREATE LOGIN [TRM199] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='TRM200')
	CREATE LOGIN [TRM200] WITH PASSWORD=N'terminale', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

IF NOT EXISTS(SELECT 1 FROM DBO.SYSUSERS WHERE NAME ='Metodo98' AND ISSQLROLE=1)
EXEC sp_addrole N'Metodo98'

EXEC sp_revokedbaccess N'ADMIN'
EXEC sp_grantdbaccess N'ADMIN', N'ADMIN'
EXEC sp_addrolemember N'Metodo98', N'ADMIN'
GO

EXEC sp_revokedbaccess N'TRM1'
EXEC sp_grantdbaccess N'TRM1', N'TRM1'
EXEC sp_addrolemember N'Metodo98', N'TRM1'
GO

EXEC sp_revokedbaccess N'TRM2'
EXEC sp_grantdbaccess N'TRM2', N'TRM2'
EXEC sp_addrolemember N'Metodo98', N'TRM2'
GO

EXEC sp_revokedbaccess N'TRM3'
EXEC sp_grantdbaccess N'TRM3', N'TRM3'
EXEC sp_addrolemember N'Metodo98', N'TRM3'
GO

EXEC sp_revokedbaccess N'TRM4'
EXEC sp_grantdbaccess N'TRM4', N'TRM4'
EXEC sp_addrolemember N'Metodo98', N'TRM4'
GO

EXEC sp_revokedbaccess N'TRM5'
EXEC sp_grantdbaccess N'TRM5', N'TRM5'
EXEC sp_addrolemember N'Metodo98', N'TRM5'
GO

EXEC sp_revokedbaccess N'TRM6'
EXEC sp_grantdbaccess N'TRM6', N'TRM6'
EXEC sp_addrolemember N'Metodo98', N'TRM6'
GO

EXEC sp_revokedbaccess N'TRM7'
EXEC sp_grantdbaccess N'TRM7', N'TRM7'
EXEC sp_addrolemember N'Metodo98', N'TRM7'
GO

EXEC sp_revokedbaccess N'TRM8'
EXEC sp_grantdbaccess N'TRM8', N'TRM8'
EXEC sp_addrolemember N'Metodo98', N'TRM8'
GO

EXEC sp_revokedbaccess N'TRM9'
EXEC sp_grantdbaccess N'TRM9', N'TRM9'
EXEC sp_addrolemember N'Metodo98', N'TRM9'
GO

EXEC sp_revokedbaccess N'TRM10'
EXEC sp_grantdbaccess N'TRM10', N'TRM10'
EXEC sp_addrolemember N'Metodo98', N'TRM10'
GO

EXEC sp_revokedbaccess N'TRM11'
EXEC sp_grantdbaccess N'TRM11', N'TRM11'
EXEC sp_addrolemember N'Metodo98', N'TRM11'
GO

EXEC sp_revokedbaccess N'TRM12'
EXEC sp_grantdbaccess N'TRM12', N'TRM12'
EXEC sp_addrolemember N'Metodo98', N'TRM12'
GO

EXEC sp_revokedbaccess N'TRM13'
EXEC sp_grantdbaccess N'TRM13', N'TRM13'
EXEC sp_addrolemember N'Metodo98', N'TRM13'
GO

EXEC sp_revokedbaccess N'TRM14'
EXEC sp_grantdbaccess N'TRM14', N'TRM14'
EXEC sp_addrolemember N'Metodo98', N'TRM14'
GO

EXEC sp_revokedbaccess N'TRM15'
EXEC sp_grantdbaccess N'TRM15', N'TRM15'
EXEC sp_addrolemember N'Metodo98', N'TRM15'
GO

EXEC sp_revokedbaccess N'TRM16'
EXEC sp_grantdbaccess N'TRM16', N'TRM16'
EXEC sp_addrolemember N'Metodo98', N'TRM16'
GO

EXEC sp_revokedbaccess N'TRM17'
EXEC sp_grantdbaccess N'TRM17', N'TRM17'
EXEC sp_addrolemember N'Metodo98', N'TRM17'
GO

EXEC sp_revokedbaccess N'TRM18'
EXEC sp_grantdbaccess N'TRM18', N'TRM18'
EXEC sp_addrolemember N'Metodo98', N'TRM18'
GO

EXEC sp_revokedbaccess N'TRM19'
EXEC sp_grantdbaccess N'TRM19', N'TRM19'
EXEC sp_addrolemember N'Metodo98', N'TRM19'
GO

EXEC sp_revokedbaccess N'TRM20'
EXEC sp_grantdbaccess N'TRM20', N'TRM20'
EXEC sp_addrolemember N'Metodo98', N'TRM20'
GO

EXEC sp_revokedbaccess N'TRM21'
EXEC sp_grantdbaccess N'TRM21', N'TRM21'
EXEC sp_addrolemember N'Metodo98', N'TRM21'
GO

EXEC sp_revokedbaccess N'TRM22'
EXEC sp_grantdbaccess N'TRM22', N'TRM22'
EXEC sp_addrolemember N'Metodo98', N'TRM22'
GO

EXEC sp_revokedbaccess N'TRM23'
EXEC sp_grantdbaccess N'TRM23', N'TRM23'
EXEC sp_addrolemember N'Metodo98', N'TRM23'
GO

EXEC sp_revokedbaccess N'TRM24'
EXEC sp_grantdbaccess N'TRM24', N'TRM24'
EXEC sp_addrolemember N'Metodo98', N'TRM24'
GO

EXEC sp_revokedbaccess N'TRM25'
EXEC sp_grantdbaccess N'TRM25', N'TRM25'
EXEC sp_addrolemember N'Metodo98', N'TRM25'
GO

EXEC sp_revokedbaccess N'TRM26'
EXEC sp_grantdbaccess N'TRM26', N'TRM26'
EXEC sp_addrolemember N'Metodo98', N'TRM26'
GO

EXEC sp_revokedbaccess N'TRM27'
EXEC sp_grantdbaccess N'TRM27', N'TRM27'
EXEC sp_addrolemember N'Metodo98', N'TRM27'
GO

EXEC sp_revokedbaccess N'TRM28'
EXEC sp_grantdbaccess N'TRM28', N'TRM28'
EXEC sp_addrolemember N'Metodo98', N'TRM28'
GO

EXEC sp_revokedbaccess N'TRM29'
EXEC sp_grantdbaccess N'TRM29', N'TRM29'
EXEC sp_addrolemember N'Metodo98', N'TRM29'
GO

EXEC sp_revokedbaccess N'TRM30'
EXEC sp_grantdbaccess N'TRM30', N'TRM30'
EXEC sp_addrolemember N'Metodo98', N'TRM30'
GO

EXEC sp_revokedbaccess N'TRM31'
EXEC sp_grantdbaccess N'TRM31', N'TRM31'
EXEC sp_addrolemember N'Metodo98', N'TRM31'
GO

EXEC sp_revokedbaccess N'TRM32'
EXEC sp_grantdbaccess N'TRM32', N'TRM32'
EXEC sp_addrolemember N'Metodo98', N'TRM32'
GO

EXEC sp_revokedbaccess N'TRM33'
EXEC sp_grantdbaccess N'TRM33', N'TRM33'
EXEC sp_addrolemember N'Metodo98', N'TRM33'
GO

EXEC sp_revokedbaccess N'TRM34'
EXEC sp_grantdbaccess N'TRM34', N'TRM34'
EXEC sp_addrolemember N'Metodo98', N'TRM34'
GO

EXEC sp_revokedbaccess N'TRM35'
EXEC sp_grantdbaccess N'TRM35', N'TRM35'
EXEC sp_addrolemember N'Metodo98', N'TRM35'
GO

EXEC sp_revokedbaccess N'TRM36'
EXEC sp_grantdbaccess N'TRM36', N'TRM36'
EXEC sp_addrolemember N'Metodo98', N'TRM36'
GO

EXEC sp_revokedbaccess N'TRM37'
EXEC sp_grantdbaccess N'TRM37', N'TRM37'
EXEC sp_addrolemember N'Metodo98', N'TRM37'
GO

EXEC sp_revokedbaccess N'TRM38'
EXEC sp_grantdbaccess N'TRM38', N'TRM38'
EXEC sp_addrolemember N'Metodo98', N'TRM38'
GO

EXEC sp_revokedbaccess N'TRM39'
EXEC sp_grantdbaccess N'TRM39', N'TRM39'
EXEC sp_addrolemember N'Metodo98', N'TRM39'
GO

EXEC sp_revokedbaccess N'TRM40'
EXEC sp_grantdbaccess N'TRM40', N'TRM40'
EXEC sp_addrolemember N'Metodo98', N'TRM40'
GO

EXEC sp_revokedbaccess N'TRM41'
EXEC sp_grantdbaccess N'TRM41', N'TRM41'
EXEC sp_addrolemember N'Metodo98', N'TRM41'
GO

EXEC sp_revokedbaccess N'TRM42'
EXEC sp_grantdbaccess N'TRM42', N'TRM42'
EXEC sp_addrolemember N'Metodo98', N'TRM42'
GO

EXEC sp_revokedbaccess N'TRM43'
EXEC sp_grantdbaccess N'TRM43', N'TRM43'
EXEC sp_addrolemember N'Metodo98', N'TRM43'
GO

EXEC sp_revokedbaccess N'TRM44'
EXEC sp_grantdbaccess N'TRM44', N'TRM44'
EXEC sp_addrolemember N'Metodo98', N'TRM44'
GO

EXEC sp_revokedbaccess N'TRM45'
EXEC sp_grantdbaccess N'TRM45', N'TRM45'
EXEC sp_addrolemember N'Metodo98', N'TRM45'
GO

EXEC sp_revokedbaccess N'TRM46'
EXEC sp_grantdbaccess N'TRM46', N'TRM46'
EXEC sp_addrolemember N'Metodo98', N'TRM46'
GO

EXEC sp_revokedbaccess N'TRM47'
EXEC sp_grantdbaccess N'TRM47', N'TRM47'
EXEC sp_addrolemember N'Metodo98', N'TRM47'
GO

EXEC sp_revokedbaccess N'TRM48'
EXEC sp_grantdbaccess N'TRM48', N'TRM48'
EXEC sp_addrolemember N'Metodo98', N'TRM48'
GO

EXEC sp_revokedbaccess N'TRM49'
EXEC sp_grantdbaccess N'TRM49', N'TRM49'
EXEC sp_addrolemember N'Metodo98', N'TRM49'
GO

EXEC sp_revokedbaccess N'TRM50'
EXEC sp_grantdbaccess N'TRM50', N'TRM50'
EXEC sp_addrolemember N'Metodo98', N'TRM50'
GO

EXEC sp_revokedbaccess N'TRM51'
EXEC sp_grantdbaccess N'TRM51', N'TRM51'
EXEC sp_addrolemember N'Metodo98', N'TRM51'
GO

EXEC sp_revokedbaccess N'TRM52'
EXEC sp_grantdbaccess N'TRM52', N'TRM52'
EXEC sp_addrolemember N'Metodo98', N'TRM52'
GO

EXEC sp_revokedbaccess N'TRM53'
EXEC sp_grantdbaccess N'TRM53', N'TRM53'
EXEC sp_addrolemember N'Metodo98', N'TRM53'
GO

EXEC sp_revokedbaccess N'TRM54'
EXEC sp_grantdbaccess N'TRM54', N'TRM54'
EXEC sp_addrolemember N'Metodo98', N'TRM54'
GO

EXEC sp_revokedbaccess N'TRM55'
EXEC sp_grantdbaccess N'TRM55', N'TRM55'
EXEC sp_addrolemember N'Metodo98', N'TRM55'
GO

EXEC sp_revokedbaccess N'TRM56'
EXEC sp_grantdbaccess N'TRM56', N'TRM56'
EXEC sp_addrolemember N'Metodo98', N'TRM56'
GO

EXEC sp_revokedbaccess N'TRM57'
EXEC sp_grantdbaccess N'TRM57', N'TRM57'
EXEC sp_addrolemember N'Metodo98', N'TRM57'
GO

EXEC sp_revokedbaccess N'TRM58'
EXEC sp_grantdbaccess N'TRM58', N'TRM58'
EXEC sp_addrolemember N'Metodo98', N'TRM58'
GO

EXEC sp_revokedbaccess N'TRM59'
EXEC sp_grantdbaccess N'TRM59', N'TRM59'
EXEC sp_addrolemember N'Metodo98', N'TRM59'
GO

EXEC sp_revokedbaccess N'TRM60'
EXEC sp_grantdbaccess N'TRM60', N'TRM60'
EXEC sp_addrolemember N'Metodo98', N'TRM60'
GO

EXEC sp_revokedbaccess N'TRM61'
EXEC sp_grantdbaccess N'TRM61', N'TRM61'
EXEC sp_addrolemember N'Metodo98', N'TRM61'
GO

EXEC sp_revokedbaccess N'TRM62'
EXEC sp_grantdbaccess N'TRM62', N'TRM62'
EXEC sp_addrolemember N'Metodo98', N'TRM62'
GO

EXEC sp_revokedbaccess N'TRM63'
EXEC sp_grantdbaccess N'TRM63', N'TRM63'
EXEC sp_addrolemember N'Metodo98', N'TRM63'
GO

EXEC sp_revokedbaccess N'TRM64'
EXEC sp_grantdbaccess N'TRM64', N'TRM64'
EXEC sp_addrolemember N'Metodo98', N'TRM64'
GO

EXEC sp_revokedbaccess N'TRM65'
EXEC sp_grantdbaccess N'TRM65', N'TRM65'
EXEC sp_addrolemember N'Metodo98', N'TRM65'
GO

EXEC sp_revokedbaccess N'TRM66'
EXEC sp_grantdbaccess N'TRM66', N'TRM66'
EXEC sp_addrolemember N'Metodo98', N'TRM66'
GO

EXEC sp_revokedbaccess N'TRM67'
EXEC sp_grantdbaccess N'TRM67', N'TRM67'
EXEC sp_addrolemember N'Metodo98', N'TRM67'
GO

EXEC sp_revokedbaccess N'TRM68'
EXEC sp_grantdbaccess N'TRM68', N'TRM68'
EXEC sp_addrolemember N'Metodo98', N'TRM68'
GO

EXEC sp_revokedbaccess N'TRM69'
EXEC sp_grantdbaccess N'TRM69', N'TRM69'
EXEC sp_addrolemember N'Metodo98', N'TRM69'
GO

EXEC sp_revokedbaccess N'TRM70'
EXEC sp_grantdbaccess N'TRM70', N'TRM70'
EXEC sp_addrolemember N'Metodo98', N'TRM70'
GO

EXEC sp_revokedbaccess N'TRM71'
EXEC sp_grantdbaccess N'TRM71', N'TRM71'
EXEC sp_addrolemember N'Metodo98', N'TRM71'
GO

EXEC sp_revokedbaccess N'TRM72'
EXEC sp_grantdbaccess N'TRM72', N'TRM72'
EXEC sp_addrolemember N'Metodo98', N'TRM72'
GO

EXEC sp_revokedbaccess N'TRM73'
EXEC sp_grantdbaccess N'TRM73', N'TRM73'
EXEC sp_addrolemember N'Metodo98', N'TRM73'
GO

EXEC sp_revokedbaccess N'TRM74'
EXEC sp_grantdbaccess N'TRM74', N'TRM74'
EXEC sp_addrolemember N'Metodo98', N'TRM74'
GO

EXEC sp_revokedbaccess N'TRM75'
EXEC sp_grantdbaccess N'TRM75', N'TRM75'
EXEC sp_addrolemember N'Metodo98', N'TRM75'
GO

EXEC sp_revokedbaccess N'TRM76'
EXEC sp_grantdbaccess N'TRM76', N'TRM76'
EXEC sp_addrolemember N'Metodo98', N'TRM76'
GO

EXEC sp_revokedbaccess N'TRM77'
EXEC sp_grantdbaccess N'TRM77', N'TRM77'
EXEC sp_addrolemember N'Metodo98', N'TRM77'
GO

EXEC sp_revokedbaccess N'TRM78'
EXEC sp_grantdbaccess N'TRM78', N'TRM78'
EXEC sp_addrolemember N'Metodo98', N'TRM78'
GO

EXEC sp_revokedbaccess N'TRM79'
EXEC sp_grantdbaccess N'TRM79', N'TRM79'
EXEC sp_addrolemember N'Metodo98', N'TRM79'
GO

EXEC sp_revokedbaccess N'TRM80'
EXEC sp_grantdbaccess N'TRM80', N'TRM80'
EXEC sp_addrolemember N'Metodo98', N'TRM80'
GO

EXEC sp_revokedbaccess N'TRM81'
EXEC sp_grantdbaccess N'TRM81', N'TRM81'
EXEC sp_addrolemember N'Metodo98', N'TRM81'
GO

EXEC sp_revokedbaccess N'TRM82'
EXEC sp_grantdbaccess N'TRM82', N'TRM82'
EXEC sp_addrolemember N'Metodo98', N'TRM82'
GO

EXEC sp_revokedbaccess N'TRM83'
EXEC sp_grantdbaccess N'TRM83', N'TRM83'
EXEC sp_addrolemember N'Metodo98', N'TRM83'
GO

EXEC sp_revokedbaccess N'TRM84'
EXEC sp_grantdbaccess N'TRM84', N'TRM84'
EXEC sp_addrolemember N'Metodo98', N'TRM84'
GO

EXEC sp_revokedbaccess N'TRM85'
EXEC sp_grantdbaccess N'TRM85', N'TRM85'
EXEC sp_addrolemember N'Metodo98', N'TRM85'
GO

EXEC sp_revokedbaccess N'TRM86'
EXEC sp_grantdbaccess N'TRM86', N'TRM86'
EXEC sp_addrolemember N'Metodo98', N'TRM86'
GO

EXEC sp_revokedbaccess N'TRM87'
EXEC sp_grantdbaccess N'TRM87', N'TRM87'
EXEC sp_addrolemember N'Metodo98', N'TRM87'
GO

EXEC sp_revokedbaccess N'TRM88'
EXEC sp_grantdbaccess N'TRM88', N'TRM88'
EXEC sp_addrolemember N'Metodo98', N'TRM88'
GO

EXEC sp_revokedbaccess N'TRM89'
EXEC sp_grantdbaccess N'TRM89', N'TRM89'
EXEC sp_addrolemember N'Metodo98', N'TRM89'
GO

EXEC sp_revokedbaccess N'TRM90'
EXEC sp_grantdbaccess N'TRM90', N'TRM90'
EXEC sp_addrolemember N'Metodo98', N'TRM90'
GO

EXEC sp_revokedbaccess N'TRM91'
EXEC sp_grantdbaccess N'TRM91', N'TRM91'
EXEC sp_addrolemember N'Metodo98', N'TRM91'
GO

EXEC sp_revokedbaccess N'TRM92'
EXEC sp_grantdbaccess N'TRM92', N'TRM92'
EXEC sp_addrolemember N'Metodo98', N'TRM92'
GO

EXEC sp_revokedbaccess N'TRM93'
EXEC sp_grantdbaccess N'TRM93', N'TRM93'
EXEC sp_addrolemember N'Metodo98', N'TRM93'
GO

EXEC sp_revokedbaccess N'TRM94'
EXEC sp_grantdbaccess N'TRM94', N'TRM94'
EXEC sp_addrolemember N'Metodo98', N'TRM94'
GO

EXEC sp_revokedbaccess N'TRM95'
EXEC sp_grantdbaccess N'TRM95', N'TRM95'
EXEC sp_addrolemember N'Metodo98', N'TRM95'
GO

EXEC sp_revokedbaccess N'TRM96'
EXEC sp_grantdbaccess N'TRM96', N'TRM96'
EXEC sp_addrolemember N'Metodo98', N'TRM96'
GO

EXEC sp_revokedbaccess N'TRM97'
EXEC sp_grantdbaccess N'TRM97', N'TRM97'
EXEC sp_addrolemember N'Metodo98', N'TRM97'
GO

EXEC sp_revokedbaccess N'TRM98'
EXEC sp_grantdbaccess N'TRM98', N'TRM98'
EXEC sp_addrolemember N'Metodo98', N'TRM98'
GO

EXEC sp_revokedbaccess N'TRM99'
EXEC sp_grantdbaccess N'TRM99', N'TRM99'
EXEC sp_addrolemember N'Metodo98', N'TRM99'
GO

EXEC sp_revokedbaccess N'TRM100'
EXEC sp_grantdbaccess N'TRM100', N'TRM100'
EXEC sp_addrolemember N'Metodo98', N'TRM100'
GO

EXEC sp_revokedbaccess N'TRM101'
EXEC sp_grantdbaccess N'TRM101', N'TRM101'
EXEC sp_addrolemember N'Metodo98', N'TRM101'
GO

EXEC sp_revokedbaccess N'TRM102'
EXEC sp_grantdbaccess N'TRM102', N'TRM102'
EXEC sp_addrolemember N'Metodo98', N'TRM102'
GO

EXEC sp_revokedbaccess N'TRM103'
EXEC sp_grantdbaccess N'TRM103', N'TRM103'
EXEC sp_addrolemember N'Metodo98', N'TRM103'
GO

EXEC sp_revokedbaccess N'TRM104'
EXEC sp_grantdbaccess N'TRM104', N'TRM104'
EXEC sp_addrolemember N'Metodo98', N'TRM104'
GO

EXEC sp_revokedbaccess N'TRM105'
EXEC sp_grantdbaccess N'TRM105', N'TRM105'
EXEC sp_addrolemember N'Metodo98', N'TRM105'
GO

EXEC sp_revokedbaccess N'TRM106'
EXEC sp_grantdbaccess N'TRM106', N'TRM106'
EXEC sp_addrolemember N'Metodo98', N'TRM106'
GO

EXEC sp_revokedbaccess N'TRM107'
EXEC sp_grantdbaccess N'TRM107', N'TRM107'
EXEC sp_addrolemember N'Metodo98', N'TRM107'
GO

EXEC sp_revokedbaccess N'TRM108'
EXEC sp_grantdbaccess N'TRM108', N'TRM108'
EXEC sp_addrolemember N'Metodo98', N'TRM108'
GO

EXEC sp_revokedbaccess N'TRM109'
EXEC sp_grantdbaccess N'TRM109', N'TRM109'
EXEC sp_addrolemember N'Metodo98', N'TRM109'
GO

EXEC sp_revokedbaccess N'TRM110'
EXEC sp_grantdbaccess N'TRM110', N'TRM110'
EXEC sp_addrolemember N'Metodo98', N'TRM110'
GO

EXEC sp_revokedbaccess N'TRM111'
EXEC sp_grantdbaccess N'TRM111', N'TRM111'
EXEC sp_addrolemember N'Metodo98', N'TRM111'
GO

EXEC sp_revokedbaccess N'TRM112'
EXEC sp_grantdbaccess N'TRM112', N'TRM112'
EXEC sp_addrolemember N'Metodo98', N'TRM112'
GO

EXEC sp_revokedbaccess N'TRM113'
EXEC sp_grantdbaccess N'TRM113', N'TRM113'
EXEC sp_addrolemember N'Metodo98', N'TRM113'
GO

EXEC sp_revokedbaccess N'TRM114'
EXEC sp_grantdbaccess N'TRM114', N'TRM114'
EXEC sp_addrolemember N'Metodo98', N'TRM114'
GO

EXEC sp_revokedbaccess N'TRM115'
EXEC sp_grantdbaccess N'TRM115', N'TRM115'
EXEC sp_addrolemember N'Metodo98', N'TRM115'
GO

EXEC sp_revokedbaccess N'TRM116'
EXEC sp_grantdbaccess N'TRM116', N'TRM116'
EXEC sp_addrolemember N'Metodo98', N'TRM116'
GO

EXEC sp_revokedbaccess N'TRM117'
EXEC sp_grantdbaccess N'TRM117', N'TRM117'
EXEC sp_addrolemember N'Metodo98', N'TRM117'
GO

EXEC sp_revokedbaccess N'TRM118'
EXEC sp_grantdbaccess N'TRM118', N'TRM118'
EXEC sp_addrolemember N'Metodo98', N'TRM118'
GO

EXEC sp_revokedbaccess N'TRM119'
EXEC sp_grantdbaccess N'TRM119', N'TRM119'
EXEC sp_addrolemember N'Metodo98', N'TRM119'
GO

EXEC sp_revokedbaccess N'TRM120'
EXEC sp_grantdbaccess N'TRM120', N'TRM120'
EXEC sp_addrolemember N'Metodo98', N'TRM120'
GO

EXEC sp_revokedbaccess N'TRM121'
EXEC sp_grantdbaccess N'TRM121', N'TRM121'
EXEC sp_addrolemember N'Metodo98', N'TRM121'
GO

EXEC sp_revokedbaccess N'TRM122'
EXEC sp_grantdbaccess N'TRM122', N'TRM122'
EXEC sp_addrolemember N'Metodo98', N'TRM122'
GO

EXEC sp_revokedbaccess N'TRM123'
EXEC sp_grantdbaccess N'TRM123', N'TRM123'
EXEC sp_addrolemember N'Metodo98', N'TRM123'
GO

EXEC sp_revokedbaccess N'TRM124'
EXEC sp_grantdbaccess N'TRM124', N'TRM124'
EXEC sp_addrolemember N'Metodo98', N'TRM124'
GO

EXEC sp_revokedbaccess N'TRM125'
EXEC sp_grantdbaccess N'TRM125', N'TRM125'
EXEC sp_addrolemember N'Metodo98', N'TRM125'
GO

EXEC sp_revokedbaccess N'TRM126'
EXEC sp_grantdbaccess N'TRM126', N'TRM126'
EXEC sp_addrolemember N'Metodo98', N'TRM126'
GO

EXEC sp_revokedbaccess N'TRM127'
EXEC sp_grantdbaccess N'TRM127', N'TRM127'
EXEC sp_addrolemember N'Metodo98', N'TRM127'
GO

EXEC sp_revokedbaccess N'TRM128'
EXEC sp_grantdbaccess N'TRM128', N'TRM128'
EXEC sp_addrolemember N'Metodo98', N'TRM128'
GO

EXEC sp_revokedbaccess N'TRM129'
EXEC sp_grantdbaccess N'TRM129', N'TRM129'
EXEC sp_addrolemember N'Metodo98', N'TRM129'
GO

EXEC sp_revokedbaccess N'TRM130'
EXEC sp_grantdbaccess N'TRM130', N'TRM130'
EXEC sp_addrolemember N'Metodo98', N'TRM130'
GO

EXEC sp_revokedbaccess N'TRM131'
EXEC sp_grantdbaccess N'TRM131', N'TRM131'
EXEC sp_addrolemember N'Metodo98', N'TRM131'
GO

EXEC sp_revokedbaccess N'TRM132'
EXEC sp_grantdbaccess N'TRM132', N'TRM132'
EXEC sp_addrolemember N'Metodo98', N'TRM132'
GO

EXEC sp_revokedbaccess N'TRM133'
EXEC sp_grantdbaccess N'TRM133', N'TRM133'
EXEC sp_addrolemember N'Metodo98', N'TRM133'
GO

EXEC sp_revokedbaccess N'TRM134'
EXEC sp_grantdbaccess N'TRM134', N'TRM134'
EXEC sp_addrolemember N'Metodo98', N'TRM134'
GO

EXEC sp_revokedbaccess N'TRM135'
EXEC sp_grantdbaccess N'TRM135', N'TRM135'
EXEC sp_addrolemember N'Metodo98', N'TRM135'
GO

EXEC sp_revokedbaccess N'TRM136'
EXEC sp_grantdbaccess N'TRM136', N'TRM136'
EXEC sp_addrolemember N'Metodo98', N'TRM136'
GO

EXEC sp_revokedbaccess N'TRM137'
EXEC sp_grantdbaccess N'TRM137', N'TRM137'
EXEC sp_addrolemember N'Metodo98', N'TRM137'
GO

EXEC sp_revokedbaccess N'TRM138'
EXEC sp_grantdbaccess N'TRM138', N'TRM138'
EXEC sp_addrolemember N'Metodo98', N'TRM138'
GO

EXEC sp_revokedbaccess N'TRM139'
EXEC sp_grantdbaccess N'TRM139', N'TRM139'
EXEC sp_addrolemember N'Metodo98', N'TRM139'
GO

EXEC sp_revokedbaccess N'TRM140'
EXEC sp_grantdbaccess N'TRM140', N'TRM140'
EXEC sp_addrolemember N'Metodo98', N'TRM140'
GO

EXEC sp_revokedbaccess N'TRM141'
EXEC sp_grantdbaccess N'TRM141', N'TRM141'
EXEC sp_addrolemember N'Metodo98', N'TRM141'
GO

EXEC sp_revokedbaccess N'TRM142'
EXEC sp_grantdbaccess N'TRM142', N'TRM142'
EXEC sp_addrolemember N'Metodo98', N'TRM142'
GO

EXEC sp_revokedbaccess N'TRM143'
EXEC sp_grantdbaccess N'TRM143', N'TRM143'
EXEC sp_addrolemember N'Metodo98', N'TRM143'
GO

EXEC sp_revokedbaccess N'TRM144'
EXEC sp_grantdbaccess N'TRM144', N'TRM144'
EXEC sp_addrolemember N'Metodo98', N'TRM144'
GO

EXEC sp_revokedbaccess N'TRM145'
EXEC sp_grantdbaccess N'TRM145', N'TRM145'
EXEC sp_addrolemember N'Metodo98', N'TRM145'
GO

EXEC sp_revokedbaccess N'TRM146'
EXEC sp_grantdbaccess N'TRM146', N'TRM146'
EXEC sp_addrolemember N'Metodo98', N'TRM146'
GO

EXEC sp_revokedbaccess N'TRM147'
EXEC sp_grantdbaccess N'TRM147', N'TRM147'
EXEC sp_addrolemember N'Metodo98', N'TRM147'
GO

EXEC sp_revokedbaccess N'TRM148'
EXEC sp_grantdbaccess N'TRM148', N'TRM148'
EXEC sp_addrolemember N'Metodo98', N'TRM148'
GO

EXEC sp_revokedbaccess N'TRM149'
EXEC sp_grantdbaccess N'TRM149', N'TRM149'
EXEC sp_addrolemember N'Metodo98', N'TRM149'
GO

EXEC sp_revokedbaccess N'TRM150'
EXEC sp_grantdbaccess N'TRM150', N'TRM150'
EXEC sp_addrolemember N'Metodo98', N'TRM150'
GO

EXEC sp_revokedbaccess N'TRM151'
EXEC sp_grantdbaccess N'TRM151', N'TRM151'
EXEC sp_addrolemember N'Metodo98', N'TRM151'
GO

EXEC sp_revokedbaccess N'TRM152'
EXEC sp_grantdbaccess N'TRM152', N'TRM152'
EXEC sp_addrolemember N'Metodo98', N'TRM152'
GO

EXEC sp_revokedbaccess N'TRM153'
EXEC sp_grantdbaccess N'TRM153', N'TRM153'
EXEC sp_addrolemember N'Metodo98', N'TRM153'
GO

EXEC sp_revokedbaccess N'TRM154'
EXEC sp_grantdbaccess N'TRM154', N'TRM154'
EXEC sp_addrolemember N'Metodo98', N'TRM154'
GO

EXEC sp_revokedbaccess N'TRM155'
EXEC sp_grantdbaccess N'TRM155', N'TRM155'
EXEC sp_addrolemember N'Metodo98', N'TRM155'
GO

EXEC sp_revokedbaccess N'TRM156'
EXEC sp_grantdbaccess N'TRM156', N'TRM156'
EXEC sp_addrolemember N'Metodo98', N'TRM156'
GO

EXEC sp_revokedbaccess N'TRM157'
EXEC sp_grantdbaccess N'TRM157', N'TRM157'
EXEC sp_addrolemember N'Metodo98', N'TRM157'
GO

EXEC sp_revokedbaccess N'TRM158'
EXEC sp_grantdbaccess N'TRM158', N'TRM158'
EXEC sp_addrolemember N'Metodo98', N'TRM158'
GO

EXEC sp_revokedbaccess N'TRM159'
EXEC sp_grantdbaccess N'TRM159', N'TRM159'
EXEC sp_addrolemember N'Metodo98', N'TRM159'
GO

EXEC sp_revokedbaccess N'TRM160'
EXEC sp_grantdbaccess N'TRM160', N'TRM160'
EXEC sp_addrolemember N'Metodo98', N'TRM160'
GO

EXEC sp_revokedbaccess N'TRM161'
EXEC sp_grantdbaccess N'TRM161', N'TRM161'
EXEC sp_addrolemember N'Metodo98', N'TRM161'
GO

EXEC sp_revokedbaccess N'TRM162'
EXEC sp_grantdbaccess N'TRM162', N'TRM162'
EXEC sp_addrolemember N'Metodo98', N'TRM162'
GO

EXEC sp_revokedbaccess N'TRM163'
EXEC sp_grantdbaccess N'TRM163', N'TRM163'
EXEC sp_addrolemember N'Metodo98', N'TRM163'
GO

EXEC sp_revokedbaccess N'TRM164'
EXEC sp_grantdbaccess N'TRM164', N'TRM164'
EXEC sp_addrolemember N'Metodo98', N'TRM164'
GO

EXEC sp_revokedbaccess N'TRM165'
EXEC sp_grantdbaccess N'TRM165', N'TRM165'
EXEC sp_addrolemember N'Metodo98', N'TRM165'
GO

EXEC sp_revokedbaccess N'TRM166'
EXEC sp_grantdbaccess N'TRM166', N'TRM166'
EXEC sp_addrolemember N'Metodo98', N'TRM166'
GO

EXEC sp_revokedbaccess N'TRM167'
EXEC sp_grantdbaccess N'TRM167', N'TRM167'
EXEC sp_addrolemember N'Metodo98', N'TRM167'
GO

EXEC sp_revokedbaccess N'TRM168'
EXEC sp_grantdbaccess N'TRM168', N'TRM168'
EXEC sp_addrolemember N'Metodo98', N'TRM168'
GO

EXEC sp_revokedbaccess N'TRM169'
EXEC sp_grantdbaccess N'TRM169', N'TRM169'
EXEC sp_addrolemember N'Metodo98', N'TRM169'
GO

EXEC sp_revokedbaccess N'TRM170'
EXEC sp_grantdbaccess N'TRM170', N'TRM170'
EXEC sp_addrolemember N'Metodo98', N'TRM170'
GO

EXEC sp_revokedbaccess N'TRM171'
EXEC sp_grantdbaccess N'TRM171', N'TRM171'
EXEC sp_addrolemember N'Metodo98', N'TRM171'
GO

EXEC sp_revokedbaccess N'TRM172'
EXEC sp_grantdbaccess N'TRM172', N'TRM172'
EXEC sp_addrolemember N'Metodo98', N'TRM172'
GO

EXEC sp_revokedbaccess N'TRM173'
EXEC sp_grantdbaccess N'TRM173', N'TRM173'
EXEC sp_addrolemember N'Metodo98', N'TRM173'
GO

EXEC sp_revokedbaccess N'TRM174'
EXEC sp_grantdbaccess N'TRM174', N'TRM174'
EXEC sp_addrolemember N'Metodo98', N'TRM174'
GO

EXEC sp_revokedbaccess N'TRM175'
EXEC sp_grantdbaccess N'TRM175', N'TRM175'
EXEC sp_addrolemember N'Metodo98', N'TRM175'
GO

EXEC sp_revokedbaccess N'TRM176'
EXEC sp_grantdbaccess N'TRM176', N'TRM176'
EXEC sp_addrolemember N'Metodo98', N'TRM176'
GO

EXEC sp_revokedbaccess N'TRM177'
EXEC sp_grantdbaccess N'TRM177', N'TRM177'
EXEC sp_addrolemember N'Metodo98', N'TRM177'
GO

EXEC sp_revokedbaccess N'TRM178'
EXEC sp_grantdbaccess N'TRM178', N'TRM178'
EXEC sp_addrolemember N'Metodo98', N'TRM178'
GO

EXEC sp_revokedbaccess N'TRM179'
EXEC sp_grantdbaccess N'TRM179', N'TRM179'
EXEC sp_addrolemember N'Metodo98', N'TRM179'
GO

EXEC sp_revokedbaccess N'TRM180'
EXEC sp_grantdbaccess N'TRM180', N'TRM180'
EXEC sp_addrolemember N'Metodo98', N'TRM180'
GO

EXEC sp_revokedbaccess N'TRM181'
EXEC sp_grantdbaccess N'TRM181', N'TRM181'
EXEC sp_addrolemember N'Metodo98', N'TRM181'
GO

EXEC sp_revokedbaccess N'TRM182'
EXEC sp_grantdbaccess N'TRM182', N'TRM182'
EXEC sp_addrolemember N'Metodo98', N'TRM182'
GO

EXEC sp_revokedbaccess N'TRM183'
EXEC sp_grantdbaccess N'TRM183', N'TRM183'
EXEC sp_addrolemember N'Metodo98', N'TRM183'
GO

EXEC sp_revokedbaccess N'TRM184'
EXEC sp_grantdbaccess N'TRM184', N'TRM184'
EXEC sp_addrolemember N'Metodo98', N'TRM184'
GO

EXEC sp_revokedbaccess N'TRM185'
EXEC sp_grantdbaccess N'TRM185', N'TRM185'
EXEC sp_addrolemember N'Metodo98', N'TRM185'
GO

EXEC sp_revokedbaccess N'TRM186'
EXEC sp_grantdbaccess N'TRM186', N'TRM186'
EXEC sp_addrolemember N'Metodo98', N'TRM186'
GO

EXEC sp_revokedbaccess N'TRM187'
EXEC sp_grantdbaccess N'TRM187', N'TRM187'
EXEC sp_addrolemember N'Metodo98', N'TRM187'
GO

EXEC sp_revokedbaccess N'TRM188'
EXEC sp_grantdbaccess N'TRM188', N'TRM188'
EXEC sp_addrolemember N'Metodo98', N'TRM188'
GO

EXEC sp_revokedbaccess N'TRM189'
EXEC sp_grantdbaccess N'TRM189', N'TRM189'
EXEC sp_addrolemember N'Metodo98', N'TRM189'
GO

EXEC sp_revokedbaccess N'TRM190'
EXEC sp_grantdbaccess N'TRM190', N'TRM190'
EXEC sp_addrolemember N'Metodo98', N'TRM190'
GO

EXEC sp_revokedbaccess N'TRM191'
EXEC sp_grantdbaccess N'TRM191', N'TRM191'
EXEC sp_addrolemember N'Metodo98', N'TRM191'
GO

EXEC sp_revokedbaccess N'TRM192'
EXEC sp_grantdbaccess N'TRM192', N'TRM192'
EXEC sp_addrolemember N'Metodo98', N'TRM192'
GO

EXEC sp_revokedbaccess N'TRM193'
EXEC sp_grantdbaccess N'TRM193', N'TRM193'
EXEC sp_addrolemember N'Metodo98', N'TRM193'
GO

EXEC sp_revokedbaccess N'TRM194'
EXEC sp_grantdbaccess N'TRM194', N'TRM194'
EXEC sp_addrolemember N'Metodo98', N'TRM194'
GO

EXEC sp_revokedbaccess N'TRM195'
EXEC sp_grantdbaccess N'TRM195', N'TRM195'
EXEC sp_addrolemember N'Metodo98', N'TRM195'
GO

EXEC sp_revokedbaccess N'TRM196'
EXEC sp_grantdbaccess N'TRM196', N'TRM196'
EXEC sp_addrolemember N'Metodo98', N'TRM196'
GO

EXEC sp_revokedbaccess N'TRM197'
EXEC sp_grantdbaccess N'TRM197', N'TRM197'
EXEC sp_addrolemember N'Metodo98', N'TRM197'
GO

EXEC sp_revokedbaccess N'TRM198'
EXEC sp_grantdbaccess N'TRM198', N'TRM198'
EXEC sp_addrolemember N'Metodo98', N'TRM198'
GO

EXEC sp_revokedbaccess N'TRM199'
EXEC sp_grantdbaccess N'TRM199', N'TRM199'
EXEC sp_addrolemember N'Metodo98', N'TRM199'
GO

EXEC sp_revokedbaccess N'TRM200'
EXEC sp_grantdbaccess N'TRM200', N'TRM200'
EXEC sp_addrolemember N'Metodo98', N'TRM200'
GO

CREATE TABLE TABPROGRESSIVI (
	NOMETABELLA varchar (80) NOT NULL ,
	PROGR decimal(10, 0) NULL CONSTRAINT DF__TABPROGRE__PROGR__39237A9A DEFAULT (0),
	CONSTRAINT PK_TABPROGRESSIVI PRIMARY KEY  CLUSTERED
	(
		NOMETABELLA
	)  ON [PRIMARY]
)
GO

if EXISTS(select NAME from sysobjects where id=OBJECT_ID('NUOVOPROGRESSIVO') AND XTYPE='P')
	DROP PROCEDURE NUOVOPROGRESSIVO
GO
CREATE PROCEDURE NUOVOPROGRESSIVO(@PTABELLA VARCHAR(80), @PAGGIORNA INTEGER, @PPROG DECIMAL(10) OUTPUT) AS
BEGIN
  DECLARE @PP DECIMAL(10)
  SELECT @PP=-1
  IF @PAGGIORNA=0
    BEGIN
    DECLARE CUR_ICONT CURSOR FOR SELECT PROGR FROM TABPROGRESSIVI WHERE NOMETABELLA=@PTABELLA
      OPEN CUR_ICONT
      FETCH CUR_ICONT INTO @PP
      IF @@FETCH_STATUS<>0     SELECT @PP = 0
      SELECT @PPROG = @PP+1
      CLOSE CUR_ICONT
      DEALLOCATE CUR_ICONT
    END
  ELSE
    BEGIN
      DECLARE CUR_ICONT CURSOR FOR SELECT PROGR FROM TABPROGRESSIVI WHERE NOMETABELLA=@PTABELLA FOR UPDATE
      OPEN CUR_ICONT
      FETCH CUR_ICONT INTO @PP
      IF @@FETCH_STATUS<>0
        BEGIN
           CLOSE CUR_ICONT
           INSERT INTO TABPROGRESSIVI(NOMETABELLA) VALUES(@PTABELLA)
           OPEN CUR_ICONT
           FETCH CUR_ICONT INTO @PP
        END
      SELECT @PP=@PP+1
      UPDATE TABPROGRESSIVI SET  PROGR=@PP WHERE CURRENT OF CUR_ICONT
      SELECT @PPROG=@PP
      CLOSE CUR_ICONT
      DEALLOCATE CUR_ICONT
    END
END
GO
GRANT EXECUTE ON NUOVOPROGRESSIVO TO METODO98
GO

if EXISTS(select NAME from sysobjects where id=OBJECT_ID('CHIAVEPRIMARIA') AND XTYPE='P')
	DROP PROCEDURE CHIAVEPRIMARIA
GO
CREATE PROCEDURE.CHIAVEPRIMARIA @STRNOMETABELLA VARCHAR(128), @STRCAMPICHIAVE VARCHAR(200) OUTPUT AS
BEGIN
  DECLARE @STRRES VARCHAR(200)
  DECLARE @STRNOME VARCHAR(128)
  SET @STRRES=''
  DECLARE CURCOLONNE CURSOR FOR
		SELECT SYSCOLUMNS.NAME
		FROM (SYSCOLUMNS INNER JOIN
			SYSOBJECTS ON SYSCOLUMNS.ID = SYSOBJECTS.ID) INNER JOIN
			SYSINDEXKEYS ON SYSINDEXKEYS.ID = SYSOBJECTS.ID
		WHERE SYSOBJECTS.NAME = @STRNOMETABELLA AND
			SYSINDEXKEYS.INDID = 1 AND
			SYSINDEXKEYS.COLID = SYSCOLUMNS.COLID
  OPEN CURCOLONNE
  FETCH NEXT FROM CURCOLONNE INTO @STRNOME
  WHILE @@FETCH_STATUS = 0
    BEGIN
      IF @STRRES=''
        SET @STRRES=@STRNOME
      ELSE
        SET @STRRES=@STRRES + ';' + @STRNOME
      FETCH NEXT FROM CURCOLONNE INTO @STRNOME
   END
  SELECT @STRCAMPICHIAVE = @STRRES
  CLOSE CURCOLONNE
  DEALLOCATE CURCOLONNE
END
GRANT EXECUTE ON CHIAVEPRIMARIA TO METODO98
GO

/* Inizio modifiche per MetScheduler */

/* TABELLA OPERAZIONI */
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'OPERAZIONI') AND OBJECTPROPERTY(ID, N'ISUSERTABLE') = 1)
	DROP TABLE OPERAZIONI
GO
CREATE TABLE OPERAZIONI (
    IDOp decimal(5,0) NOT NULL ,
    NomeOp varchar (255) NULL ,
    Ditta varchar (255) NULL ,
    DescrOP varchar (255) NULL ,
    Quando smallint NULL ,
    NumMinuti smallint NULL ,
    CheGiorno smallint NULL ,
    TipoSched smallint NULL ,
    NumSett smallint NULL ,
    UTENTE varchar (80) NULL ,
    PASS varchar (80) NULL ,
    ESERCIZIO smallint NULL ,
    DataInizio datetime NOT NULL ,
    ORAINIZIO datetime NOT NULL ,
    Ricalcola smallint NULL ,
    Lun smallint NULL ,
    Mar smallint NULL ,
    Mer smallint NULL ,
    Gio smallint NULL ,
    Ven smallint NULL ,
    Sab smallint NULL ,
    Dom smallint NULL ,
    GENN smallint NULL ,
    FEBR smallint NULL ,
    MARZ smallint NULL ,
    APRI smallint NULL ,
    MAGG smallint NULL ,
    GIUG smallint NULL ,
    LUGL smallint NULL ,
    AGOS smallint NULL ,
    SETT smallint NULL ,
    OTTO smallint NULL ,
    NOVE smallint NULL ,
    DICE smallint NULL ,
    DescrSched varchar (255) NULL ,
    AutoExec smallint NULL,
    UTENTEMODIFICA varchar (25) NOT NULL ,
    DATAMODIFICA datetime NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE OPERAZIONI WITH NOCHECK ADD
    CONSTRAINT PK_OPERAZIONI PRIMARY KEY  CLUSTERED
    (IDOP)  ON [PRIMARY]
GO

ALTER TABLE OPERAZIONI WITH NOCHECK ADD
    CONSTRAINT DF_Operazioni_Ricalcola DEFAULT (0) FOR Ricalcola,
    CONSTRAINT DF_Operazioni_Lun DEFAULT (0) FOR Lun,
    CONSTRAINT DF_Operazioni_Mar DEFAULT (0) FOR Mar,
    CONSTRAINT DF_Operazioni_Mer DEFAULT (0) FOR Mer,
    CONSTRAINT DF_Operazioni_Gio DEFAULT (0) FOR Gio,
    CONSTRAINT DF_Operazioni_Ven DEFAULT (0) FOR Ven,
    CONSTRAINT DF_Operazioni_Sab DEFAULT (0) FOR Sab,
    CONSTRAINT DF_Operazioni_Dom DEFAULT (0) FOR Dom,
    CONSTRAINT DF_Operazioni_GENN DEFAULT (0) FOR GENN,
    CONSTRAINT DF_Operazioni_FEBR DEFAULT (0) FOR FEBR,
    CONSTRAINT DF_Operazioni_MARZ DEFAULT (0) FOR MARZ,
    CONSTRAINT DF_Operazioni_APRI DEFAULT (0) FOR APRI,
    CONSTRAINT DF_Operazioni_MAGG DEFAULT (0) FOR MAGG,
    CONSTRAINT DF_Operazioni_GIUG DEFAULT (0) FOR GIUG,
    CONSTRAINT DF_Operazioni_LUGL DEFAULT (0) FOR LUGL,
    CONSTRAINT DF_Operazioni_AGOS DEFAULT (0) FOR AGOS,
    CONSTRAINT DF_Operazioni_SETT DEFAULT (0) FOR SETT,
    CONSTRAINT DF_Operazioni_OTTO DEFAULT (0) FOR OTTO,
    CONSTRAINT DF_Operazioni_NOVE DEFAULT (0) FOR NOVE,
    CONSTRAINT DF_Operazioni_DICE DEFAULT (0) FOR DICE,
    CONSTRAINT DF_Operazioni_AUTOEXEC DEFAULT (0) FOR AUTOEXEC,
    CONSTRAINT CK_Operazioni_GENN CHECK (GENN = 0 or GENN = 1),
    CONSTRAINT CK_Operazioni_FEBR CHECK (FEBR = 0 or FEBR = 1),
    CONSTRAINT CK_Operazioni_MARZ CHECK (MARZ = 0 or MARZ = 1),
    CONSTRAINT CK_Operazioni_APRI CHECK (APRI = 0 or APRI = 1),
    CONSTRAINT CK_Operazioni_MAGG CHECK (MAGG = 0 or MAGG = 1),
    CONSTRAINT CK_Operazioni_GIUG CHECK (GIUG = 0 or GIUG = 1),
    CONSTRAINT CK_Operazioni_LUGL CHECK (LUGL = 0 or LUGL = 1),
    CONSTRAINT CK_Operazioni_AGOS CHECK (AGOS = 0 or AGOS = 1),
    CONSTRAINT CK_Operazioni_SETT CHECK (SETT = 0 or SETT = 1),
    CONSTRAINT CK_Operazioni_OTTO CHECK (OTTO = 0 or OTTO = 1),
    CONSTRAINT CK_Operazioni_NOVE CHECK (NOVE = 0 or NOVE = 1),
    CONSTRAINT CK_Operazioni_DICE CHECK (DICE = 0 or DICE = 1),
    CONSTRAINT CK_Operazioni_RICALCOLA CHECK (Ricalcola = 0 or Ricalcola = 1),
    CONSTRAINT CK_Operazioni_AUTOEXEC CHECK (AutoExec = 0 or AutoExec = 1),
    CONSTRAINT CK_Operazioni_Lun CHECK (Lun = 0 or Lun = 1),
    CONSTRAINT CK_Operazioni_Mar CHECK (Mar = 0 or Mar = 1),
    CONSTRAINT CK_Operazioni_Mer CHECK (Mer = 0 or Mer = 1),
    CONSTRAINT CK_Operazioni_Gio CHECK (Gio = 0 or Gio = 1),
    CONSTRAINT CK_Operazioni_Ven CHECK (Ven = 0 or Ven = 1),
    CONSTRAINT CK_Operazioni_Sab CHECK (Sab = 0 or Sab = 1),
    CONSTRAINT CK_Operazioni_Dom CHECK (Dom = 0 or Dom = 1)
GO
GRANT ALL ON OPERAZIONI TO METODO98
GO

/* TABELLA PAROPERAZIONI */
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'ParOperazioni') AND OBJECTPROPERTY(ID, N'ISUSERTABLE') = 1)
	DROP TABLE ParOperazioni
GO
CREATE TABLE ParOperazioni (
    IDOp decimal(5,0) NOT NULL ,
    IDPar smallint NOT NULL ,
    POSIZIONE decimal(5, 0) NULL ,
    FLAGRIGA smallint NULL ,
    NOMEPAR varchar (255) NULL ,
    Valore1 varchar (1000) NULL ,
    Tipo1 varchar (255) NULL ,
    Valore2 varchar (1000) NULL ,
    Tipo2 varchar (255) NULL ,
    Valore3 varchar (1000) NULL ,
    Tipo3 varchar (255) NULL ,
    Valore4 varchar (1000) NULL ,
    Tipo4 varchar (255) NULL ,
    Valore5 varchar (1000) NULL ,
    Tipo5 varchar (255) NULL ,
    UTENTEMODIFICA varchar (25) NOT NULL ,
    DATAMODIFICA datetime NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE ParOperazioni WITH NOCHECK ADD
    CONSTRAINT PK_ParOperazioni PRIMARY KEY  CLUSTERED
    (IDOP, IDPAR)  ON [PRIMARY]
GO
GRANT ALL ON PAROPERAZIONI TO METODO98
GO

/* TABELLA SCADOPERAZIONI */
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'SCADOPERAZIONI') AND OBJECTPROPERTY(ID, N'ISUSERTABLE') = 1)
	DROP TABLE SCADOPERAZIONI
GO
CREATE TABLE SCADOPERAZIONI (
    IDOp decimal(5,0) NOT NULL ,
    Ditta varchar (255) NULL ,
    PROSSIMAESECUZIONE datetime NOT NULL ,
    ULTIMAESECUZIONE datetime NULL ,
    STATO smallint NULL ,
    UTENTEMODIFICA varchar (25) NOT NULL ,
    DATAMODIFICA datetime NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE SCADOPERAZIONI WITH NOCHECK ADD
    CONSTRAINT PK_SCADOPERAZIONI PRIMARY KEY  CLUSTERED
    (IDOP)  ON [PRIMARY]
GO

ALTER TABLE SCADOPERAZIONI WITH NOCHECK ADD
  CONSTRAINT DF_SCADOPERAZIONI_stato DEFAULT (0) FOR STATO
GO
GRANT ALL ON SCADOPERAZIONI TO METODO98
GO

/* LOGOPERAZIONI */
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'LOGOPERAZIONI') AND OBJECTPROPERTY(ID, N'ISUSERTABLE') = 1)
	DROP TABLE LOGOPERAZIONI
GO
CREATE TABLE LOGOPERAZIONI (
    IDOP decimal(5,0) NOT NULL ,
    DATAOP datetime NOT NULL ,
    DITTA varchar (255) NULL ,
    ESITO smallint NULL ,
    LOGFILE varchar (255) NULL ,
    LETTO smallint NULL ,
    UTENTEMODIFICA varchar (25) NOT NULL ,
    DATAMODIFICA datetime NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE LOGOPERAZIONI WITH NOCHECK ADD
    CONSTRAINT PK_LOGOPERAZIONI PRIMARY KEY  CLUSTERED
    (IDOP, DATAOP)  ON [PRIMARY]
GO

ALTER TABLE LOGOPERAZIONI WITH NOCHECK ADD
  CONSTRAINT DF_LOGOPERAZIONI_letto DEFAULT (0) FOR letto
GO

GRANT ALL ON LOGOPERAZIONI TO METODO98
GO

/*  DELETE TRIGGER "TD_OPERAZIONI" FOR TABLE "OPERAZIONI"  */
CREATE TRIGGER TD_OPERAZIONI ON OPERAZIONI FOR DELETE AS
BEGIN
    DECLARE
       @NUMROWS  INT,
       @ERRNO    INT,
       @ERRMSG   VARCHAR(255)

    SELECT  @NUMROWS = @@ROWCOUNT
    IF @NUMROWS = 0
       RETURN

    /*  DELETE ALL CHILDREN IN "LOGOPERAZIONI"  */
    DELETE LOGOPERAZIONI
    FROM   LOGOPERAZIONI T2, DELETED T1
    WHERE  T2.IDOP = T1.IDOP

    /*  DELETE ALL CHILDREN IN "SCADENZE"  */
    DELETE SCADOPERAZIONI
    FROM   SCADOPERAZIONI T2, DELETED T1
    WHERE  T2.IDOP = T1.IDOP

    /*  DELETE ALL CHILDREN IN "PARAMETRI"  */
    DELETE PAROPERAZIONI
    FROM   PAROPERAZIONI T2, DELETED T1
    WHERE  T2.IDOP = T1.IDOP

    RETURN

/*  ERRORS HANDLING  */
ERROR:
    RAISERROR @ERRNO @ERRMSG
    ROLLBACK  TRANSACTION
END
GO

/* Sincronizzazione tabella progressivi */
IF EXISTS (SELECT * FROM TABPROGRESSIVI WHERE NOMETABELLA = 'OPERAZIONI')
	DELETE FROM TABPROGRESSIVI WHERE NOMETABELLA = 'OPERAZIONI'
GO

INSERT INTO TABPROGRESSIVI (NOMETABELLA, PROGR) VALUES ('OPERAZIONI', 0);
GO

/* Fine modifiche per MetScheduler */
