
--delete from TEMPLIVPROD_ARTICOLI

--INSERT INTO TEMPLIVPROD_ARTICOLI 
-- 	SELECT DISTINCT CODICE, 0, 'Z' FROM ANAGRAFICAARTICOLI
--	UNION
--	SELECT DISTINCT RIFARTICOLO, 0, 'Z' FROM DISTINTAARTCOMPOSTI

--UPDATE ANAGRAFICAARTICOLIPROD
--	SET LIVPRODPREC = LIVPRODUZIONE
--WHERE 
--	ESERCIZIO=2010

UPDATE TEMPLIVPROD_ARTICOLI 
		SET LIVPRODNUM = 1
	WHERE
		CODART IN 
		(SELECT CODCOMPONENTE FROM VISTALIVPRODCALC_LEGAMI TLL
			INNER JOIN TEMPLIVPROD_ARTICOLI TLP ON
			TLL.CODCOMPOSTO = TLP.CODART
			WHERE 
			TLP.LIVPRODNUM = 0)

