EXEC BRIO_CALCOLAPREZZOMPARTICOLI_2
GO
UPDATE STORICOMAG SET IMPORTOTOTLORDO=S.QTA1UM*BP.PREZZOMEDIO FROM STORICOMAG AS S INNER JOIN BRIO_PREZZIARTICOLIMP AS BP ON S.CODART=BP.CODART AND BP.ANNO=2010 AND BP.MESE=12 WHERE S.CODCAUSALE IN (200,201) AND DATAMOV='20101231' AND IMPORTOTOTLORDO=0
GO
UPDATE STORICOMAG SET IMPORTOTOTLORDOVAL=S.QTA1UM*BP.PREZZOMEDIO FROM STORICOMAG AS S INNER JOIN BRIO_PREZZIARTICOLIMP AS BP ON S.CODART=BP.CODART AND BP.ANNO=2010 AND BP.MESE=12 WHERE S.CODCAUSALE IN (200,201) AND DATAMOV='20101231' AND IMPORTOTOTLORDOVAL=0
GO
UPDATE STORICOMAG SET IMPORTOTOTLORDOEURO=S.QTA1UM*BP.PREZZOMEDIO FROM STORICOMAG AS S INNER JOIN BRIO_PREZZIARTICOLIMP AS BP ON S.CODART=BP.CODART AND BP.ANNO=2010 AND BP.MESE=12 WHERE S.CODCAUSALE IN (200,201) AND DATAMOV='20101231' AND IMPORTOTOTLORDOEURO=0
GO
UPDATE STORICOMAG SET IMPORTOTOTNETTO=S.QTA1UM*BP.PREZZOMEDIO FROM STORICOMAG AS S INNER JOIN BRIO_PREZZIARTICOLIMP AS BP ON S.CODART=BP.CODART AND BP.ANNO=2010 AND BP.MESE=12 WHERE S.CODCAUSALE IN (200,201) AND DATAMOV='20101231' AND IMPORTOTOTNETTO=0
GO
UPDATE STORICOMAG SET IMPORTOTOTNETTOVAL=S.QTA1UM*BP.PREZZOMEDIO FROM STORICOMAG AS S INNER JOIN BRIO_PREZZIARTICOLIMP AS BP ON S.CODART=BP.CODART AND BP.ANNO=2010 AND BP.MESE=12 WHERE S.CODCAUSALE IN (200,201) AND DATAMOV='20101231' AND IMPORTOTOTNETTOVAL=0
GO
UPDATE STORICOMAG SET IMPORTOTOTNETTOEURO=S.QTA1UM*BP.PREZZOMEDIO FROM STORICOMAG AS S INNER JOIN BRIO_PREZZIARTICOLIMP AS BP ON S.CODART=BP.CODART AND BP.ANNO=2010 AND BP.MESE=12 WHERE S.CODCAUSALE IN (200,201) AND DATAMOV='20101231' AND IMPORTOTOTNETTOEURO=0
GO


--TEST PRIMA DI ESEGUIRE
SELECT * FROM STORICOMAG AS S WHERE S.CODCAUSALE IN (200,201) AND datamov='20101231' AND importototlordo=0
SELECT * FROM STORICOMAG AS S WHERE S.CODCAUSALE IN (200,201) AND datamov='20101231' and codart='VY05A16'
SELECT * FROM BRIO_PREZZIARTICOLIMP AS BP WHERE anno=2010 AND mese=12 AND BP.CODART='VY05A16'