IF EXISTS (SELECT * 
	   FROM   sysobjects 
	   WHERE  name = N'LEGGICLIENTEINTESTATARIO')
	DROP FUNCTION LEGGICLIENTEINTESTATARIO
GO
CREATE FUNCTION LEGGICLIENTEINTESTATARIO
	(@IDTESTA int) RETURNS varchar(7)
AS
BEGIN
	DECLARE @CODCLIFOR AS varchar(7)
	
	DECLARE CUR_DOC CURSOR SCROLL SCROLL_LOCKS FOR	
	SELECT CODCLIFOR FROM TESTEDOCUMENTI WHERE PROGRESSIVO=@IDTESTA
	OPEN CUR_DOC
	FETCH NEXT FROM CUR_DOC INTO @CODCLIFOR
	IF @@FETCH_STATUS<>0 SELECT @CODCLIFOR = ''
 	CLOSE CUR_DOC
	DEALLOCATE CUR_DOC

	RETURN @CODCLIFOR
END
GO
GRANT EXECUTE ON LEGGICLIENTEINTESTATARIO TO METODO98
GO



IF EXISTS (SELECT * 
	   FROM   sysobjects 
	   WHERE  name = N'LEGGIULTIMOPREZZO')
	DROP FUNCTION LEGGIULTIMOPREZZO
GO
CREATE  FUNCTION LEGGIULTIMOPREZZO (@ARTICOLO VARCHAR(50), @DATA DATETIME)  
RETURNS DECIMAL(19,2)  AS
BEGIN 
	DECLARE @PREZZO AS DECIMAL(19,2)
	DECLARE @UMSTAT AS VARCHAR(3)

	-- DETERMINO L'UM STATISTICA DELL'ARTICOLO PASSATO
	DECLARE CUR_UM_STAT CURSOR SCROLL SCROLL_LOCKS FOR	
		SELECT UM FROM ARTICOLIUMPREFERITE WHERE TIPOUM=8 AND CODART=@ARTICOLO
	OPEN CUR_UM_STAT
	FETCH NEXT FROM CUR_UM_STAT INTO @UMSTAT
 	CLOSE CUR_UM_STAT
	DEALLOCATE CUR_UM_STAT

	-- DETERMINO IL COSTO ULTIMO RISPETTO ALLA DATA DOCUMENTO PASSATA
	DECLARE CUR_STORICO_PREZZI CURSOR SCROLL SCROLL_LOCKS FOR
		SELECT TOP 1 (PRZ.PREZZOEURO*FC.FATTORE) AS PREZZO
		FROM STORICOPREZZIARTICOLO PRZ LEFT OUTER JOIN ARTICOLIFATTORICONVERSIONE FC
			ON FC.CODART=PRZ.CODARTICOLO AND FC.UM2=PRZ.UM
		WHERE PRZ.CODARTICOLO=@ARTICOLO 
			AND PRZ.TIPOPREZZO = 'F'
			AND PRZ.DATA<=@DATA
			AND FC.UM1=@UMSTAT
		ORDER BY DATA DESC
	OPEN CUR_STORICO_PREZZI	
	FETCH NEXT FROM CUR_STORICO_PREZZI INTO @PREZZO
	IF @@FETCH_STATUS<>0 SELECT @PREZZO = 0

  	CLOSE CUR_STORICO_PREZZI
	DEALLOCATE CUR_STORICO_PREZZI 

	RETURN @PREZZO
END
GO
GRANT EXECUTE ON LEGGIULTIMOPREZZO TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOANAGRAFICAARTICOLI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOANAGRAFICAARTICOLI
GO
CREATE VIEW dbo.BRIOANAGRAFICAARTICOLI
AS
SELECT     *
FROM         dbo.ANAGRAFICAARTICOLI 
GO
GRANT SELECT ON BRIOANAGRAFICAARTICOLI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABGRUPPI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABGRUPPI
GO
CREATE VIEW dbo.BRIOVISTATABGRUPPI
AS
SELECT     *
FROM         dbo.TABGRUPPI 
GO
GRANT SELECT ON BRIOVISTATABGRUPPI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABCATEGORIE') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABCATEGORIE
GO
CREATE VIEW dbo.BRIOVISTATABCATEGORIE
AS
SELECT     *
FROM         dbo.TABCATEGORIE 
GO
GRANT SELECT ON BRIOVISTATABCATEGORIE TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABCATEGORIESTAT') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABCATEGORIESTAT
GO
CREATE VIEW dbo.BRIOVISTATABCATEGORIESTAT
AS
SELECT     *
FROM         dbo.TABCATEGORIESTAT
GO
GRANT SELECT ON BRIOVISTATABCATEGORIESTAT TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABZONE') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABZONE
GO
CREATE VIEW dbo.BRIOVISTATABZONE
AS
SELECT     *
FROM         dbo.TABZONE
GO
GRANT SELECT ON BRIOVISTATABZONE TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABSPEDIZ') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABSPEDIZ
GO
CREATE VIEW dbo.BRIOVISTATABSPEDIZ
AS
SELECT     *
FROM         dbo.TABSPEDIZ
GO
GRANT SELECT ON BRIOVISTATABSPEDIZ TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABMASTRI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABMASTRI
GO
CREATE VIEW dbo.BRIOVISTATABMASTRI
AS
SELECT     *
FROM         dbo.TABMASTRI
GO
GRANT SELECT ON BRIOVISTATABMASTRI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABNAZIONI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABNAZIONI
GO
CREATE VIEW dbo.BRIOVISTATABNAZIONI
AS
SELECT     *
FROM         dbo.TABNAZIONI
GO
GRANT SELECT ON BRIOVISTATABNAZIONI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABSETTORI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABSETTORI
GO
CREATE VIEW dbo.BRIOVISTATABSETTORI
AS
SELECT     *
FROM         dbo.TABSETTORI
GO
GRANT SELECT ON BRIOVISTATABSETTORI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTACATEGORIECF') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTACATEGORIECF
GO
CREATE VIEW dbo.BRIOVISTACATEGORIECF
AS
SELECT     *
FROM         dbo.CATEGORIECF
GO
GRANT SELECT ON BRIOVISTACATEGORIECF TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABPAGAMENTI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABPAGAMENTI
GO
CREATE VIEW dbo.BRIOVISTATABPAGAMENTI
AS
SELECT     *
FROM         dbo.TABPAGAMENTI
GO
GRANT SELECT ON BRIOVISTATABPAGAMENTI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTADESTINAZIONIDIVERSE') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTADESTINAZIONIDIVERSE
GO
CREATE VIEW dbo.BRIOVISTADESTINAZIONIDIVERSE
AS
SELECT     *
FROM         dbo.DESTINAZIONIDIVERSE
GO
GRANT SELECT ON BRIOVISTADESTINAZIONIDIVERSE TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABCAUSALIMAG') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABCAUSALIMAG
GO
CREATE VIEW dbo.BRIOVISTATABCAUSALIMAG
AS
SELECT     *
FROM         dbo.TABCAUSALIMAG
GO
GRANT SELECT ON BRIOVISTATABCAUSALIMAG TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAANAGRAFICAGENERICI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAANAGRAFICAGENERICI
GO
CREATE VIEW dbo.BRIOVISTAANAGRAFICAGENERICI
AS
SELECT     *
FROM         dbo.ANAGRAFICAGENERICI
GO
GRANT SELECT ON BRIOVISTAANAGRAFICAGENERICI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATIPIEFFETTI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATIPIEFFETTI
GO
CREATE VIEW dbo.BRIOVISTATIPIEFFETTI
AS
SELECT     *
FROM         dbo.TIPIEFFETTI
GO
GRANT SELECT ON BRIOVISTATIPIEFFETTI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAESITI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAESITI
GO
CREATE VIEW dbo.BRIOVISTAESITI
AS
SELECT     *
FROM         dbo.ESITI
GO
GRANT SELECT ON BRIOVISTAESITI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAANAGRAFICABANCHE') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAANAGRAFICABANCHE
GO
CREATE VIEW dbo.BRIOVISTAANAGRAFICABANCHE
AS
SELECT     *
FROM         dbo.ANAGRAFICABANCHE
GO
GRANT SELECT ON BRIOVISTAANAGRAFICABANCHE TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABCAMBI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABCAMBI
GO
CREATE VIEW dbo.BRIOVISTATABCAMBI
AS
SELECT     *
FROM         dbo.TABCAMBI
GO
GRANT SELECT ON BRIOVISTATABCAMBI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABELLAOPERAZIONI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABELLAOPERAZIONI
GO
CREATE VIEW dbo.BRIOVISTATABELLAOPERAZIONI
AS
select *
FROM TABELLAOPERAZIONI
GO
GRANT SELECT ON BRIOVISTATABELLAOPERAZIONI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABELLADIPENDENTI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABELLADIPENDENTI
GO
CREATE VIEW dbo.BRIOVISTATABELLADIPENDENTI
AS
select *
FROM TABELLADIPENDENTI
GO
GRANT SELECT ON BRIOVISTATABELLADIPENDENTI TO METODO98
GO





IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAPARAMETRICOMMPROD') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAPARAMETRICOMMPROD
GO
CREATE VIEW dbo.BRIOVISTAPARAMETRICOMMPROD
AS
SELECT     *
FROM         dbo.PARAMETRICOMMPROD
GO
GRANT SELECT ON BRIOVISTAPARAMETRICOMMPROD TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAPARAMETRIORDPROD') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAPARAMETRIORDPROD
GO
CREATE VIEW dbo.BRIOVISTAPARAMETRIORDPROD
AS
SELECT     *
FROM         dbo.PARAMETRIORDPROD
GO
GRANT SELECT ON BRIOVISTAPARAMETRIORDPROD TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAANAGRAFICAAGENTI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAANAGRAFICAAGENTI
GO
CREATE VIEW dbo.BRIOVISTAANAGRAFICAAGENTI
AS
SELECT     *
FROM         dbo.ANAGRAFICAAGENTI
GO
GRANT SELECT ON BRIOVISTAANAGRAFICAAGENTI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABCFG') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABCFG
GO
CREATE VIEW dbo.BRIOVISTATABCFG
AS
SELECT     *
FROM         dbo.TABCFG
GO
GRANT SELECT ON BRIOVISTATABCFG TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABRAGGRUPPAPREZZI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABRAGGRUPPAPREZZI
GO
CREATE VIEW dbo.BRIOVISTATABRAGGRUPPAPREZZI
AS
SELECT     *
FROM         dbo.TABRAGGRUPPAPREZZI
GO
GRANT SELECT ON BRIOVISTATABRAGGRUPPAPREZZI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABTIPOLOGIE') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABTIPOLOGIE
GO
CREATE VIEW dbo.BRIOVISTATABTIPOLOGIE
AS
SELECT     *
FROM         dbo.TABTIPOLOGIE
GO
GRANT SELECT ON BRIOVISTATABTIPOLOGIE TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABVARIANTI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABVARIANTI
GO
CREATE VIEW dbo.BRIOVISTATABVARIANTI
AS
SELECT     *
FROM         dbo.TABVARIANTI
GO
GRANT SELECT ON BRIOVISTATABVARIANTI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTACLI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTACLI
GO
CREATE VIEW BRIOVISTACLI
AS
SELECT     AF.TIPOCONTO, AF.CODCONTO, AF.CODMASTRO, AF.CAP, AF.LOCALITA, AF.PROVINCIA, AF.CODNAZIONE, AF.CODICEISO, 
		   RF.ESERCIZIO, RF.CODSETTORE, RF.CODZONA, RF.CODCATEGORIA, RF.CODSPED, RF.CODPAG,
               (SELECT CAB
                FROM   BANCAAPPCF
                WHERE  CODCONTO = RF.CODCONTO AND CODICE = BANCAANAGR) AS CAB,
               (SELECT ABI
                FROM   BANCAAPPCF
                WHERE  CODCONTO = RF.CODCONTO AND CODICE = BANCAANAGR) AS ABI,
               (SELECT CONTOCORRENTE
                FROM   BANCAAPPCF
                WHERE  CODCONTO = RF.CODCONTO AND CODICE = BANCAANAGR) AS CCDEBITORE, 
			RF.CODAGENTE1, RF.CODAGENTE2, RF.CODAGENTE3, 
            RF.DESTDIVMERCI, RF.FIDOEURO, RF.CODGRUPPOPREZZIPART, RF.CODGRUPPOPROVPART, 
			AF.DSCCONTO1, AF.CODREGIONE, TR.DESCRIZIONE AS REGIONE
FROM        dbo.ANAGRAFICACF AF 
			INNER JOIN dbo.ANAGRAFICARISERVATICF RF ON AF.CODCONTO = RF.CODCONTO
			LEFT OUTER JOIN TABREGIONI TR ON AF.CODREGIONE=TR.CODICE
WHERE     (RF.ESERCIZIO = (SELECT MAX(CODICE)FROM TABESERCIZI)) AND (AF.TIPOCONTO IN ('C'))
GO
GRANT SELECT ON BRIOVISTACLI TO METODO98
GO



IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTACLIFOR') AND TYPE = 'V')
   DROP VIEW dbo.BRIOVISTACLIFOR
GO
CREATE VIEW dbo.BRIOVISTACLIFOR
AS
SELECT		AF.TIPOCONTO, AF.CODCONTO, AF.CODMASTRO, AF.CAP, AF.LOCALITA, AF.PROVINCIA, AF.CODNAZIONE, AF.CODICEISO, RF.ESERCIZIO, 
            RF.CODSETTORE, RF.CODZONA, RF.CODCATEGORIA, RF.CODSPED, RF.CODPAG,
               (SELECT CAB
                FROM   BANCAAPPCF
                WHERE  CODCONTO = RF.CODCONTO AND CODICE = BANCAANAGR) AS CAB,
               (SELECT ABI
                FROM   BANCAAPPCF
                WHERE  CODCONTO = RF.CODCONTO AND CODICE = BANCAANAGR) AS ABI,
               (SELECT CONTOCORRENTE
                FROM   BANCAAPPCF
                WHERE  CODCONTO = RF.CODCONTO AND CODICE = BANCAANAGR) AS CCDEBITORE, 
			RF.CODAGENTE1, RF.CODAGENTE2, RF.CODAGENTE3, 
            RF.DESTDIVMERCI, RF.FIDOEURO, RF.CODGRUPPOPREZZIPART, RF.CODGRUPPOPROVPART, AF.DSCCONTO1,
			AF.CODREGIONE, TR.DESCRIZIONE AS REGIONE
FROM        dbo.ANAGRAFICACF AF 
			INNER JOIN dbo.ANAGRAFICARISERVATICF RF ON AF.CODCONTO = RF.CODCONTO
			LEFT OUTER JOIN TABREGIONI TR ON AF.CODREGIONE=TR.CODICE
WHERE		(RF.ESERCIZIO =(SELECT MAX(CODICE) FROM TABESERCIZI))
GO
GRANT SELECT ON BRIOVISTACLIFOR TO METODO98
GO



IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAVISTABOLLELAVORAZIONE ') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAVISTABOLLELAVORAZIONE 
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTABOLLELAVORAZIONE ') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTABOLLELAVORAZIONE 
GO
CREATE VIEW dbo.BRIOVISTABOLLELAVORAZIONE 
AS
SELECT
TESTACICLOORDINE.PROGRESSIVO,TESTACICLOORDINE.CODCICLO,(select VARESPLICITE from ANAGRAFICAARTICOLI where ANAGRAFICAARTICOLI.CODICE=TESTACICLOORDINE.CODCICLO) as VARESPLICITE,
TESTACICLOORDINE.VERSIONECICLO,TESTACICLOORDINE.DSCVERSIONE,TESTACICLOORDINE.STATOVERSIONE,TESTACICLOORDINE.VALIDITACICLO,TESTACICLOORDINE.VERSIONEDBA,
TESTACICLOORDINE.CICLOSTANDARD,TESTACICLOORDINE.NOTECICLO,TESTACICLOORDINE.UM AS UMRIF,TESTACICLOORDINE.QUANTITARIF,TESTACICLOORDINE.TIPOCICLO,
TESTACICLOORDINE.IDTESTACOMM,TESTACICLOORDINE.IDTESTACOMM as IDTESTA,TESTACICLOORDINE.IDRIGACOMM,TESTACICLOORDINE.IDRIGACOMM as IDRIGA,
RIGHECICLOORDINE.NUMEROFASE,RIGHECICLOORDINE.ANNOBOLLA,RIGHECICLOORDINE.NUMEROBOLLA,RIGHECICLOORDINE.TIPOFASE,RIGHECICLOORDINE.OPERAZIONE,
RIGHECICLOORDINE.DSCOPERAZIONE,RIGHECICLOORDINE.POSIZIONE,RIGHECICLOORDINE.POSIZIONE+1 as POSIZIONEFASESUCC,RIGHECICLOORDINE.POSIZIONE-1 as POSIZIONEFASEPREC,RIGHECICLOORDINE.TIPOOPERAZIONE,RIGHECICLOORDINE.STATOOPERAZIONE,RIGHECICLOORDINE.STATODOCUMENTAZIONE,
RIGHECICLOORDINE.CDLAVORO,(select DESCRIZIONE from TABELLACDLAVORO where RIGHECICLOORDINE.CDLAVORO=TABELLACDLAVORO.CODICE) "DSCCDLAVORO",
(select REPARTO from TABELLACDLAVORO where RIGHECICLOORDINE.CDLAVORO=TABELLACDLAVORO.CODICE) "CODREPARTO",RIGHECICLOORDINE.MACCHINA,
(select DESCRIZIONE from TABELLAMACCHINE where RIGHECICLOORDINE.MACCHINA=TABELLAMACCHINE.CODICE) "DSCMACCHINA",RIGHECICLOORDINE.UMTEMPOSETUP,
RIGHECICLOORDINE.UMTEMPOMACCHINA,RIGHECICLOORDINE.UMTEMPOUOMO,RIGHECICLOORDINE.UMTEMPOTOTALE,RIGHECICLOORDINE.FOGLIOISTRUZIONI,RIGHECICLOORDINE.ATTREZZATURA,
RIGHECICLOORDINE.STRUMENTICONTROLLO,RIGHECICLOORDINE.PIANOCONTROLLO,RIGHECICLOORDINE.NOTERIGA,RIGHECICLOORDINE.TEMPOPREVSETUP,RIGHECICLOORDINE.TEMPOPREVMACCHINA,
RIGHECICLOORDINE.TEMPOPREVUOMO,RIGHECICLOORDINE.TEMPOPREVDURATA,RIGHECICLOORDINE.TEMPOPREVMOV,RIGHECICLOORDINE.TEMPOPREVCODA,RIGHECICLOORDINE.TEMPOPREVATTRAV,
RIGHECICLOORDINE.TEMPOEFFSETUP,RIGHECICLOORDINE.TEMPOEFFMACCHINA,RIGHECICLOORDINE.TEMPOEFFUOMO,RIGHECICLOORDINE.TEMPOEFFDURATA,RIGHECICLOORDINE.OREPREVSETUP,
RIGHECICLOORDINE.OREPREVMACCHINA,RIGHECICLOORDINE.OREPREVUOMO,RIGHECICLOORDINE.OREPREVDURATA,RIGHECICLOORDINE.OREPREVMOV,RIGHECICLOORDINE.OREPREVCODA,
RIGHECICLOORDINE.OREPREVATTRAV,RIGHECICLOORDINE.OREEFFSETUP,RIGHECICLOORDINE.OREEFFMACCHINA,RIGHECICLOORDINE.OREEFFUOMO,RIGHECICLOORDINE.OREEFFDURATA,
RIGHECICLOORDINE.CP_ATTREZZAGGIO,RIGHECICLOORDINE.CP_MACCHINA,RIGHECICLOORDINE.CP_UOMO,RIGHECICLOORDINE.CP_INDVARIABILE,RIGHECICLOORDINE.CP_INDFISSO,
RIGHECICLOORDINE.CP_TOTESTERNI,RIGHECICLOORDINE.CC_ATTREZZAGGIO,RIGHECICLOORDINE.CC_MACCHINA,RIGHECICLOORDINE.CC_UOMO,RIGHECICLOORDINE.CC_INDVARIABILE,
RIGHECICLOORDINE.CC_INDFISSO,RIGHECICLOORDINE.CC_TOTESTERNI,RIGHECICLOORDINE.CP_EU_ATTREZZAGGIO,RIGHECICLOORDINE.CP_EU_MACCHINA,RIGHECICLOORDINE.CP_EU_UOMO,
RIGHECICLOORDINE.CP_EU_INDVARIABILE,RIGHECICLOORDINE.CP_EU_INDFISSO,RIGHECICLOORDINE.CP_EU_TOTESTERNI,RIGHECICLOORDINE.CC_EU_ATTREZZAGGIO,RIGHECICLOORDINE.CC_EU_MACCHINA,
RIGHECICLOORDINE.CC_EU_UOMO,RIGHECICLOORDINE.CC_EU_INDVARIABILE,RIGHECICLOORDINE.CC_EU_INDFISSO,RIGHECICLOORDINE.CC_EU_TOTESTERNI,RIGHECICLOORDINE.UMGEST,
RIGHECICLOORDINE.QTAPREVISTA,RIGHECICLOORDINE.QTAVERSATA,RIGHECICLOORDINE.QTASCARTATA,RIGHECICLOORDINE.QTATERZISTA,RIGHECICLOORDINE.QTAPRONTA,
RIGHECICLOORDINE.QTATRASFERITA,RIGHECICLOORDINE.QTALAVORATA,(CASE WHEN(RIGHECICLOORDINE.QTAPREVISTA=0) then 0 else (RIGHECICLOORDINE.QTAPREVISTAFASE/RIGHECICLOORDINE.QTAPREVISTA) end) as FCUMGESTFASE,
(CASE WHEN(RIGHECICLOORDINE.QTAPREVISTAFASE=0) then 0 else (RIGHECICLOORDINE.QTAPREVISTA/RIGHECICLOORDINE.QTAPREVISTAFASE) end) as FCUMFASEGEST,
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (RIGHECICLOORDINE.QTAPREVISTA-RIGHECICLOORDINE.QTATERZISTA) end) as QTADAORDINARE,
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (CASE WHEN (RIGHECICLOORDINE.QTAPREVISTA - RIGHECICLOORDINE.QTAVERSATA - RIGHECICLOORDINE.QTASCARTATA) < 0 THEN 0 ELSE (RIGHECICLOORDINE.QTAPREVISTA - RIGHECICLOORDINE.QTAVERSATA - RIGHECICLOORDINE.QTASCARTATA) END) end) AS QTARES,
RIGHECICLOORDINE.QTAPREVISTAFASE,RIGHECICLOORDINE.UMFASE,RIGHECICLOORDINE.DATAINIZIOOPSCHEDULATA,RIGHECICLOORDINE.ORAINIZIOOPSCHEDULATA,RIGHECICLOORDINE.DATAFINEOPSCHEDULATA,
RIGHECICLOORDINE.ORAFINEOPSCHEDULATA,RIGHECICLOORDINE.DATAINIZIOOPEFFETTIVA,RIGHECICLOORDINE.ORAINIZIOOPEFFETTIVA,RIGHECICLOORDINE.DATAFINEOPEFFETTIVA,RIGHECICLOORDINE.ORAFINEOPEFFETTIVA,
RIGHECICLOORDINE.VALORESOLOSE,RIGHECICLOORDINE.SEGMENTOSCHED,RIGHECICLOORDINE.SEGMENTOCONS,RIGHECICLOORDINE.FORNITOREASSEGNATO,RIGHECICLOORDINE.LISTINOTRASF,
(select DSCCONTO1 from ANAGRAFICACF where CODCONTO=RIGHECICLOORDINE.FORNITOREASSEGNATO) AS RAGSOCFORNITORE,TESTEORDINIPROD.ESERCIZIO,TESTEORDINIPROD.TIPOCOM,
TESTEORDINIPROD.NUMEROCOM,TESTEORDINIPROD.DATAEMISSIONE,RIGHEORDPROD.CODICEORD,RIGHEORDPROD.CODART,RIGHEORDPROD.DESCRIZIONEART,RIGHEORDPROD.UMGEST as UMGESTORD,
RIGHEORDPROD.QTAGESTIONE,RIGHEORDPROD.QTAGESTIONEVERS,RIGHEORDPROD.QTAGESTIONERES,RIGHEORDPROD.CODCLIDEST,RIGHEORDPROD.TIPOSCHEDULAZIONE,
RIGHEORDPROD.FASERILASCIO,RIGHEORDPROD.DATARILASCIO,RIGHEORDPROD.RIFCOMMCLI,RIGHEORDPROD.DEPOSITO,RIGHEORDPROD.UBICAZIONE,(SELECT TIPOORDINE FROM PARAMETRIORDPROD WHERE CODICEORD=CODICE) AS "TIPOORD",
RIGHEORDPROD.StatoLancio,(CASE WHEN RigheOrdProd.QtaGestioneRes = 0 THEN 100 else (CASE WHEN RigheOrdProd.QtaGestione <> 0 THEN RigheOrdProd.QtaGestioneVers/RigheOrdProd.QtaGestione * 100 ELSE 100 END) end) AS "AVANZQTAORD",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 100 else (CASE WHEN RigheOrdProd.QtaGestione <> 0 THEN RigheCicloOrdine.QtaVersata/RigheOrdProd.QtaGestione * 100 ELSE 100 END) end) AS "AVANZQTAFASE",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 100 else (CASE WHEN RigheCicloOrdine.OrePrevDurata <> 0 THEN RigheCicloOrdine.OreEffDurata/RigheCicloOrdine.OrePrevDurata*100 ELSE 100 END) end) AS "AVANZDURATAFASE",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 100 else (CASE WHEN (CP_ATTREZZAGGIO+CP_MACCHINA+CP_UOMO+CP_INDVARIABILE+CP_INDFISSO+CP_TOTESTERNI) <> 0 THEN ((CC_ATTREZZAGGIO+CC_MACCHINA+CC_UOMO+CC_INDVARIABILE+CC_INDFISSO+CC_TOTESTERNI)/(CP_ATTREZZAGGIO+CP_MACCHINA+CP_UOMO+CP_INDVARIABILE+CP_INDFISSO+CP_TOTESTERNI)*100) ELSE 100 END) end)AS "AVANZCOSTOTOT",
RIGHEORDPROD.DataInizioRich,RIGHEORDPROD.DataFineRich,(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 100 else (CASE WHEN (CP_ATTREZZAGGIO+CP_MACCHINA+CP_UOMO+CP_INDVARIABILE+CP_INDFISSO+CP_TOTESTERNI) <> 0 THEN (RigheCicloOrdine.CC_Attrezzaggio +RigheCicloOrdine.CC_Macchina + RigheCicloOrdine.CC_Uomo + RigheCicloOrdine.CC_IndVariabile + RigheCicloOrdine.CC_IndFisso + RigheCicloOrdine.CC_TotEsterni)/((CP_ATTREZZAGGIO+CP_MACCHINA+CP_UOMO+CP_INDVARIABILE+CP_INDFISSO+CP_TOTESTERNI) * 100)ELSE 0 END) END )AS "AVANZCOSTOFASE",
(CASE WHEN (CP_ATTREZZAGGIO+CP_MACCHINA+CP_UOMO+CP_INDVARIABILE+CP_INDFISSO+CP_TOTESTERNI) <> 0 THEN ((RigheCicloOrdine.CP_Attrezzaggio-RigheCicloOrdine.CC_Attrezzaggio)+(RigheCicloOrdine.CP_Macchina-RigheCicloOrdine.CC_Macchina)+(RigheCicloOrdine.CP_Uomo-RigheCicloOrdine.CC_Uomo)+(RigheCicloOrdine.CP_IndVariabile-RigheCicloOrdine.CC_IndVariabile)+(RigheCicloOrdine.CP_IndFisso-RigheCicloOrdine.CC_IndFisso)+(RigheCicloOrdine.CP_TotEsterni-RigheCicloOrdine.CC_TotEsterni))/(CP_ATTREZZAGGIO+CP_MACCHINA+CP_UOMO+CP_INDVARIABILE+CP_INDFISSO+CP_TOTESTERNI)* 100 ELSE 0 END) AS "SCARTOCOSTOTOT",
(CASE WHEN (CP_EU_ATTREZZAGGIO+CP_EU_MACCHINA+CP_EU_UOMO+CP_EU_INDVARIABILE+CP_EU_INDFISSO+CP_EU_TOTESTERNI) <> 0 THEN ((RigheCicloOrdine.CP_EU_Attrezzaggio-RigheCicloOrdine.CC_EU_Attrezzaggio)+(RigheCicloOrdine.CP_EU_Macchina-RigheCicloOrdine.CC_EU_Macchina)+(RigheCicloOrdine.CP_EU_Uomo-RigheCicloOrdine.CC_EU_Uomo)+(RigheCicloOrdine.CP_EU_IndVariabile-RigheCicloOrdine.CC_EU_IndVariabile)+(RigheCicloOrdine.CP_EU_IndFisso-RigheCicloOrdine.CC_EU_IndFisso)+(RigheCicloOrdine.CP_EU_TotEsterni-RigheCicloOrdine.CC_EU_TotEsterni))/(CP_EU_ATTREZZAGGIO+CP_EU_MACCHINA+CP_EU_UOMO+CP_EU_INDVARIABILE+CP_EU_INDFISSO+CP_EU_TOTESTERNI)* 100 ELSE 0 END) AS "SCARTOCOSTOTOT_EURO",
RigheCicloOrdine.CA_Attrezzaggio,RigheCicloOrdine.CA_Macchina,RigheCicloOrdine.CA_Uomo,RigheCicloOrdine.CA_IndVariabile,RigheCicloOrdine.OreEffMov,
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else(CASE WHEN (RigheCicloOrdine.CP_Attrezzaggio-RigheCicloOrdine.CC_Attrezzaggio) < 0 THEN 0 ELSE (RigheCicloOrdine.CP_Attrezzaggio-RigheCicloOrdine.CC_Attrezzaggio) END) END) AS "CR_ATTREZZAGGIO",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else(CASE WHEN (RigheCicloOrdine.CP_Macchina-RigheCicloOrdine.CC_Macchina) < 0 THEN 0 ELSE (RigheCicloOrdine.CP_Macchina-RigheCicloOrdine.CC_Macchina) END) END)  AS "CR_MACCHINA",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else(CASE WHEN (RigheCicloOrdine.CP_Uomo-RigheCicloOrdine.CC_Uomo) < 0 THEN 0 ELSE (RigheCicloOrdine.CP_Uomo-RigheCicloOrdine.CC_Uomo) END) END) AS "CR_UOMO",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else(CASE WHEN (RigheCicloOrdine.CP_IndVariabile-RigheCicloOrdine.CC_IndVariabile) < 0 THEN 0 ELSE (RigheCicloOrdine.CP_IndVariabile-RigheCicloOrdine.CC_IndVariabile) END) END) AS "CR_INDVARIABILE",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (CASE WHEN (RigheCicloOrdine.CP_IndFisso-RigheCicloOrdine.CC_IndFisso) < 0 THEN 0 ELSE (RigheCicloOrdine.CP_IndFisso-RigheCicloOrdine.CC_IndFisso) END) END) AS "CR_INDFISSO",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (CASE WHEN (RigheCicloOrdine.CP_TotEsterni-RigheCicloOrdine.CC_TotEsterni) < 0 THEN 0 ELSE (RigheCicloOrdine.CP_TotEsterni-RigheCicloOrdine.CC_TotEsterni) END) END)  AS "CR_TOTESTERNI",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (CASE WHEN (RigheCicloOrdine.CP_EU_Attrezzaggio-RigheCicloOrdine.CC_EU_Attrezzaggio) < 0 THEN 0 ELSE (RigheCicloOrdine.CP_EU_Attrezzaggio-RigheCicloOrdine.CC_EU_Attrezzaggio) END) END) AS "CR_EU_ATTREZZAGGIO",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (CASE WHEN (RigheCicloOrdine.CP_EU_Macchina-RigheCicloOrdine.CC_EU_Macchina) < 0 THEN 0 ELSE (RigheCicloOrdine.CP_EU_Macchina-RigheCicloOrdine.CC_EU_Macchina) END) END)  AS "CR_EU_MACCHINA",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (CASE WHEN (RigheCicloOrdine.CP_EU_Uomo-RigheCicloOrdine.CC_EU_Uomo) < 0 THEN 0 ELSE (RigheCicloOrdine.CP_EU_Uomo-RigheCicloOrdine.CC_EU_Uomo) END) END) AS "CR_EU_UOMO",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (CASE WHEN (RigheCicloOrdine.CP_EU_IndVariabile-RigheCicloOrdine.CC_EU_IndVariabile) < 0 THEN 0 ELSE (RigheCicloOrdine.CP_EU_IndVariabile-RigheCicloOrdine.CC_EU_IndVariabile) END) END) AS "CR_EU_INDVARIABILE",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (CASE WHEN (RigheCicloOrdine.CP_EU_IndFisso-RigheCicloOrdine.CC_EU_IndFisso) < 0 THEN 0 ELSE (RigheCicloOrdine.CP_EU_IndFisso-RigheCicloOrdine.CC_EU_IndFisso) END) END)  AS "CR_EU_INDFISSO",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (CASE WHEN (RigheCicloOrdine.CP_EU_TotEsterni-RigheCicloOrdine.CC_EU_TotEsterni) < 0 THEN 0 ELSE (RigheCicloOrdine.CP_EU_TotEsterni-RigheCicloOrdine.CC_EU_TotEsterni) END) END) AS "CR_EU_TOTESTERNI",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (CASE WHEN (RigheCicloOrdine.OrePrevSetup-RigheCicloOrdine.OreEffSetup) < 0 THEN 0 ELSE (RigheCicloOrdine.OrePrevSetup-RigheCicloOrdine.OreEffSetup) END) END) AS "ORERESSETUP",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (CASE WHEN (RigheCicloOrdine.OrePrevMacchina-RigheCicloOrdine.OreEffMacchina) < 0 THEN 0 ELSE (RigheCicloOrdine.OrePrevMacchina-RigheCicloOrdine.OreEffMacchina) END) END)  AS "ORERESMACCHINA",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (CASE WHEN (RigheCicloOrdine.OrePrevUomo-RigheCicloOrdine.OreEffUomo) < 0 THEN 0 ELSE (RigheCicloOrdine.OrePrevUomo-RigheCicloOrdine.OreEffUomo) END) END)  AS "ORERESUOMO",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (CASE WHEN (RigheCicloOrdine.OrePrevDurata-RigheCicloOrdine.OreEffDurata) < 0 THEN 0 ELSE (RigheCicloOrdine.OrePrevDurata-RigheCicloOrdine.OreEffDurata) END) END) AS "ORERESDURATA",
(CASE WHEN(RIGHECICLOORDINE.STATOOPERAZIONE=2) then 0 else (CASE WHEN (RigheCicloOrdine.OrePrevMov-RigheCicloOrdine.OreEffMov) < 0 THEN 0 ELSE (RigheCicloOrdine.OrePrevMov-RigheCicloOrdine.OreEffMov) END) END) AS "ORERESMOV",
(TesteOrdiniProd.TipoCom+'/'+CAST(TesteOrdiniProd.Esercizio AS VARCHAR)+'/'+RIGHT('0000000000'+CAST(TesteOrdiniProd.NumeroCom AS VARCHAR),10)+'/'+RIGHT('00000'+CAST(RigheOrdProd.IDRiga AS VARCHAR),5)) AS "RIFORDINE",
(CASE WHEN (RigheCicloOrdine.OrePrevDurata-RigheCicloOrdine.OreEffDurata) <> 0 THEN ((RigheCicloOrdine.OrePrevDurata-RigheCicloOrdine.OreEffDurata)-OrePrevDurata)/(RigheCicloOrdine.OrePrevDurata-RigheCicloOrdine.OreEffDurata)*100 ELSE 0 END) AS "AVANZDURATA",
(CASE WHEN RigheCicloOrdine.FornitoreAssegnato IS NULL THEN RigheOrdProd.CodForDest ELSE RigheCicloOrdine.FornitoreAssegnato END) AS "FornitoreFase",
RigheOrdProd.CodForDest,RIGHEORDPROD.PARTITAASSEGNATA,RIGHEORDPROD.PARTITAVINCOLATA

FROM
	TESTACICLOORDINE,RIGHECICLOORDINE,TESTEORDINIPROD,RIGHEORDPROD
WHERE
	(TESTACICLOORDINE.PROGRESSIVO=RIGHECICLOORDINE.PROGRESSIVO)
	and (TESTACICLOORDINE.IDTESTACOMM=TESTEORDINIPROD.PROGRESSIVO)
	and (TESTACICLOORDINE.IDTESTACOMM=RIGHEORDPROD.IDTESTA and TESTACICLOORDINE.IDRIGACOMM=RIGHEORDPROD.IDRIGA)

GO
GRANT SELECT ON BRIOVISTABOLLELAVORAZIONE  TO METODO98
GO


IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTACONSEGNE') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTACONSEGNE
GO
CREATE VIEW dbo.BRIOVISTACONSEGNE
AS
SELECT				 YEAR(TD.DATADOC) AS ANNODOC, MONTH(TD.DATADOC) AS MESE, STR(MONTH(TD.DATADOC), 2, 0) + ' - ' + DATENAME(MM, TD.DATADOC) AS MESEDOC, 
					 {fn WEEK(TD.DATADOC)} AS SETTDOC, DAY(TD.DATADOC) AS GIORNODOC, 
					 TD.TIPODOC + ' - ' + PARAMETRIDOC.DESCRIZIONE AS TIPODOC, TD.NUMERODOC, TD.DATADOC, TD.CODCLIFOR, TD.CODCAMBIO,
				     RD.IDRIGA AS PROGRIGADOC, RD.TIPORIGA, RD.CODART, RD.DATACONSEGNA,
                     YEAR(RD.DATACONSEGNA) AS ANNOCONS, STR(MONTH(RD.DATACONSEGNA), 2, 0) + ' - ' + DATENAME(MM, RD.DATACONSEGNA) AS MESECONS,
                     RD.RIFCOMMCLI, RD.NOMECOMMESSAPROD, RD.CODDEPOSITO, RD.QTAGEST * FC.FATTORE * TD.SEGNO AS QTASTAT, 
                     RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS QTASTATRES, RD.TOTNETTORIGAEURO * TD.SEGNO AS TOTNETTORIGAEURO, 
	                 RD.TOTNETTORIGA * TD.SEGNO AS TOTNETTORIGADIVISA, 
                     RD.TOTNETTORIGAEURORES * TD.SEGNO AS TOTNETTORIGAEURORES, dbo.PARAMETRIDOC.TIPO,
                                               (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8) AS UMSTATART, TD.INCIDENZASCONTI, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END AS TOTNETTISSIMO, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGA * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGA * TD.SEGNO END AS TOTNETTISSIMODIVISA, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END AS TOTNETTISSIMORES, 
					  dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGEST * FC.FATTORE * TD.SEGNO AS TOTCOSTOEURO, 
                      (CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END) - dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGEST * FC.FATTORE * TD.SEGNO AS MARGNETTISSIMO, 
					  dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS TOTCOSTOEURORES, 
                      (CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END) - dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS MARGNETTISSIMORES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO - dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGEST * FC.FATTORE * TD.SEGNO AS MARGNETTO, 
					  RD.TOTNETTORIGAEURORES * TD.SEGNO - dbo.LEGGIULTIMOPREZZO(RD.CODART,TD.DATADOC) * RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS MARGNETTORES
FROM         dbo.TESTEDOCUMENTI TD INNER JOIN
                      dbo.RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA INNER JOIN
                      dbo.PARAMETRIDOC ON dbo.PARAMETRIDOC.CODICE = TD.TIPODOC AND dbo.PARAMETRIDOC.TIPO IN ('B','O','F') AND 
                      dbo.PARAMETRIDOC.CLIFOR = 'C' INNER JOIN
                      dbo.ARTICOLIFATTORICONVERSIONE FC ON RD.CODART = FC.CODART AND FC.UM1 = RD.UMGEST
WHERE     (FC.UM2 =
                          (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8))
GO
GRANT SELECT ON BRIOVISTACONSEGNE TO METODO98
GO







IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTACONSEGNEF') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTACONSEGNEF
GO
CREATE VIEW dbo.BRIOVISTACONSEGNEF
AS
SELECT				  YEAR(TD.DATADOC) AS ANNODOC, STR(MONTH(TD.DATADOC), 2, 0) + ' - ' + DATENAME(MM, TD.DATADOC) AS MESEDOC, 
					  {fn WEEK(TD.DATADOC)} AS SETTDOC, DAY(TD.DATADOC) AS GIORNODOC, 
					  TD.TIPODOC + ' - ' + PARAMETRIDOC.DESCRIZIONE AS TIPODOC, TD.NUMERODOC, TD.DATADOC, TD.CODCLIFOR, TD.CODCAMBIO,RD.IDRIGA AS PROGRIGADOC, 
                      RD.TIPORIGA, RD.CODART, RD.DATACONSEGNA, YEAR(RD.DATACONSEGNA) AS ANNOCONS, STR(MONTH(RD.DATACONSEGNA), 2, 0) 
                      + ' - ' + DATENAME(MM, RD.DATACONSEGNA) AS MESECONS, RD.RIFCOMMCLI, RD.NOMECOMMESSAPROD, RD.CODDEPOSITO, 
                      RD.QTAGEST * FC.FATTORE * TD.SEGNO AS QTASTAT, RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS QTASTATRES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO AS TOTNETTORIGAEURO, 
                      RD.TOTNETTORIGA * TD.SEGNO AS TOTNETTORIGADIVISA,
					  RD.TOTNETTORIGAEURORES * TD.SEGNO AS TOTNETTORIGAEURORES, 
                      dbo.PARAMETRIDOC.TIPO,
                          (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8) AS UMSTATART, TD.INCIDENZASCONTI, 
                      CASE WHEN RD.TIPODOC='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END AS TOTNETTISSIMO, 
                      CASE WHEN RD.TIPODOC='O' THEN RD.TOTNETTORIGA * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGA * TD.SEGNO END AS TOTNETTISSIMODIVISA, 
                      CASE WHEN RD.TIPODOC='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END AS TOTNETTISSIMORES
FROM            dbo.TESTEDOCUMENTI TD INNER JOIN
                      dbo.RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA INNER JOIN
                      dbo.PARAMETRIDOC ON dbo.PARAMETRIDOC.CODICE = TD.TIPODOC AND dbo.PARAMETRIDOC.TIPO IN ('B', 'O','F') AND 
                      dbo.PARAMETRIDOC.CLIFOR = 'F' INNER JOIN
                      dbo.ARTICOLIFATTORICONVERSIONE FC ON RD.CODART = FC.CODART AND FC.UM1 = RD.UMGEST
WHERE     (FC.UM2 =
                          (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8))
GO
GRANT SELECT ON BRIOVISTACONSEGNEF TO METODO98
GO


IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAMOVCONT') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAMOVCONT
GO
CREATE VIEW BRIOVISTAMOVCONT
AS
SELECT  RCONT.NRREG, 
		RCONT.NRRIGA, 
		TCONT.PROGRESSIVO, 
		TCONT.ESERCIZIO, 
		TCONT.DATAREG, 
		TCONT.NRRIFER, 
		TCONT.PROVVISORIO, 
		TCONT.MOVIVA, 
        TCONT.CAUSALE, 
		TCONT.MESEPLAFOND, 
		TCONT.DESCRIZIONE, 
		TCONT.APPUNTI, 
		TCONT.TOTDOCLIRE, 
		TCONT.TOTDOCVALUTA, 
		TCONT.TOTDOCEURO,
		TCONT.NRGIORNALE, 
		TCONT.IDTESTADOC, 
		RCONT.DATARIF, 
		RCONT.NRRIF, 
		RCONT.NRPARTITA, 
		RCONT.CONTO, 
		RCONT.SEGNO, 
		RCONT.IMPORTO, 
        RCONT.IMPORTOVALUTA, 
		RCONT.IMPORTOEURO, 
		RCONT.VALORECAMBIO, 
		RCONT.DESCRIZIONE AS DESCRIZIONERIGHE, 
		RCONT.DATAVALUTA, 
		RCONT.CPARTITA, 
        RCONT.RIGACAUSALE, 
		RCONT.CODCOMMESSA, 
		RCONT.CODCAMBIO,
        (SELECT TOP (1) NUMDOC FROM dbo.RIGHEIVA WHERE (NRREG = TCONT.PROGRESSIVO) AND (TIPOREGISTRO = TCONT.MOVIVA)) AS NUMDOC,
        (SELECT TOP (1) DATADOC FROM dbo.RIGHEIVA AS RIGHEIVA_1 WHERE(NRREG = TCONT.PROGRESSIVO) AND (TIPOREGISTRO = TCONT.MOVIVA)) AS DATADOC, CAUCONT.DESCRIZIONE AS DescrCauCont, 
                      dbo.TABCFG.DSCCONTO1, (CASE WHEN RCONT.SEGNO = 0 THEN RCONT.IMPORTO ELSE 0 END) AS DARE, 
                      (CASE WHEN RCONT.SEGNO = 0 THEN RCONT.IMPORTOEURO ELSE 0 END) AS DAREEURO, 
                      (CASE WHEN RCONT.SEGNO = 0 THEN RCONT.IMPORTOVALUTA ELSE 0 END) AS DAREVALUTA, (CASE WHEN RCONT.SEGNO = 1 THEN RCONT.IMPORTO ELSE 0 END)
                       AS AVERE, (CASE WHEN RCONT.SEGNO = 1 THEN RCONT.IMPORTOEURO ELSE 0 END) AS AVEREEURO, 
                      (CASE WHEN RCONT.SEGNO = 1 THEN RCONT.IMPORTOVALUTA ELSE 0 END) AS AVEREVALUTA, 
                      SUBSTRING('01-GEN02-FEB03-MAR04-APR05-MAG06-GIU07-LUG08-AGO09-SET10-OTT11-NOV12-DIC', (MONTH(TCONT.DATAREG) - 1) * 6 + 1, 6) AS Mese
FROM        dbo.RIGHECONTABILITA AS RCONT LEFT OUTER JOIN 
			dbo.TESTECONTABILITA AS TCONT ON RCONT.NRREG = TCONT.PROGRESSIVO INNER JOIN
			dbo.CAUSALICONTABILI AS CAUCONT ON TCONT.CAUSALE = CAUCONT.CODICECAUSALE INNER JOIN
            dbo.TABCFG ON RCONT.CONTO = dbo.TABCFG.CODCONTO
WHERE     (TCONT.CAUSALE <>
                          (SELECT     CAUSCONTAP
                            FROM          dbo.TABVINCOLIGIC AS GIC
                            WHERE      (ESERCIZIO = TCONT.ESERCIZIO))) AND (TCONT.CAUSALE <>
                          (SELECT     CAUSCONTCH
                            FROM          dbo.TABVINCOLIGIC AS GIC
                            WHERE      (ESERCIZIO = TCONT.ESERCIZIO)))
GO
GRANT SELECT ON BRIOVISTAMOVCONT TO METODO98
GO


IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAFATTCLIENTE') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAFATTCLIENTE
GO
CREATE VIEW dbo.BRIOVISTAFATTCLIENTE
AS
SELECT				  YEAR(TD.DATADOC) AS ANNODOC,MONTH(TD.DATADOC) AS MESE, STR(MONTH(TD.DATADOC), 2, 0) + ' - ' + DATENAME(MM, TD.DATADOC) AS MESEDOC, 
					  { fn WEEK(TD.DATADOC)} AS SETTDOC, DAY(TD.DATADOC) AS GIORNODOC, 
					  TD.TIPODOC + ' - ' + PARAMETRIDOC.DESCRIZIONE AS TIPODOC, TD.NUMERODOC, TD.DATADOC, TD.CODCLIFOR, TD.CODAGENTE1, TD.CODAGENTE2, TD.CODAGENTE3, 
					  TD.NUMDESTDIVERSAMERCI, TD.RAGSOCDDM, TD.PROVINCIADDM, TD.LOCALITADDM,
                      RD.IDRIGA AS PROGRIGADOC, RD.TIPORIGA, RD.CODART, RD.DATACONSEGNA, RD.RIFCOMMCLI, RD.NOMECOMMESSAPROD, 
                      RD.CODDEPOSITO, RD.QTAGEST * FC.FATTORE * TD.SEGNO AS QTASTAT, RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS QTASTATRES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO AS TOTNETTORIGAEURO, 
					  RD.TOTNETTORIGA * TD.SEGNO AS TOTNETTORIGADIVISA,
					  RD.TOTNETTORIGAEURORES * TD.SEGNO AS TOTNETTORIGAEURORES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * (CAST(REPLACE(TD.PRCPROVVFINALEAG1,',','.') as decimal(9,4))) / 100 + RD.TOTPROVVAGEURO1 * TD.SEGNO AS TOTPROVVAG1EURO, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * (CAST(REPLACE(TD.PRCPROVVFINALEAG2,',','.') as decimal(9,4)))/ 100 + RD.TOTPROVVAGEURO2 * TD.SEGNO AS TOTPROVVAG2EURO, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * (CAST(REPLACE(TD.PRCPROVVFINALEAG3,',','.') as decimal(9,4))) / 100 + RD.TOTPROVVAGEURO3 * TD.SEGNO AS TOTPROVVAG3EURO,
                          (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8) AS UMSTATART, TD.INCIDENZASCONTI, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END AS TOTNETTISSIMO, 
					  CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGA * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGA * TD.SEGNO END AS TOTNETTISSIMODIVISA,
					  TD.CODCAMBIO, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END AS TOTNETTISSIMORES, dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC) 
                      * RD.QTAGEST * FC.FATTORE * TD.SEGNO AS TOTCOSTOEURO, 
                      (CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END) - dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGEST * FC.FATTORE * TD.SEGNO AS MARGNETTISSIMO, 
					  dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS TOTCOSTOEURORES, 
                      (CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END) - dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS MARGNETTISSIMORES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO - dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGEST * FC.FATTORE * TD.SEGNO AS MARGNETTO, 
					  RD.TOTNETTORIGAEURORES * TD.SEGNO - dbo.LEGGIULTIMOPREZZO(RD.CODART,TD.DATADOC) * RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS MARGNETTORES,
					  dbo.LEGGICLIENTEINTESTATARIO(RD.IDTESTARP) AS CLIENTEBOLLA
FROM         dbo.TESTEDOCUMENTI TD INNER JOIN
                      dbo.RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA INNER JOIN
                      dbo.PARAMETRIDOC ON dbo.PARAMETRIDOC.CODICE = TD.TIPODOC AND dbo.PARAMETRIDOC.TIPO IN ('F', 'N') AND 
                      dbo.PARAMETRIDOC.CLIFOR = 'C' INNER JOIN
                      dbo.ARTICOLIFATTORICONVERSIONE FC ON RD.CODART = FC.CODART AND FC.UM1 = RD.UMGEST
WHERE     (FC.UM2 =
                          (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8))
GO
GRANT SELECT ON BRIOVISTAFATTCLIENTE TO METODO98
GO


IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTABOLLECLIENTE') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTABOLLECLIENTE
GO
CREATE VIEW dbo.BRIOVISTABOLLECLIENTE
AS
SELECT     YEAR(TD.DATADOC) AS ANNODOC, MONTH(TD.DATADOC) AS MESE,STR(MONTH(TD.DATADOC), 2, 0) + ' - ' + DATENAME(MM, TD.DATADOC) AS MESEDOC, { fn WEEK(TD.DATADOC) 
                      } AS SETTDOC, DAY(TD.DATADOC) AS GIORNODOC, TD.TIPODOC + ' - ' + PARAMETRIDOC.DESCRIZIONE AS TIPODOC, TD.NUMERODOC, TD.DATADOC, TD.CODCLIFOR, TD.CODAGENTE1, 
                      TD.CODAGENTE2, TD.CODAGENTE3, TD.NUMDESTDIVERSAMERCI, TD.RAGSOCDDM, TD.PROVINCIADDM, TD.LOCALITADDM, TD.CODCAMBIO,
                      RD.IDRIGA AS PROGRIGADOC, RD.TIPORIGA, RD.CODART, RD.DATACONSEGNA, RD.RIFCOMMCLI, RD.NOMECOMMESSAPROD, RD.CODDEPOSITO, 
                      RD.QTAGEST * FC.FATTORE * TD.SEGNO AS QTASTAT, RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS QTASTATRES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO AS TOTNETTORIGAEURO,
					  RD.TOTNETTORIGA * TD.SEGNO AS TOTNETTORIGADIVISA,
					  RD.TOTNETTORIGAEURORES * TD.SEGNO AS TOTNETTORIGAEURORES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * CAST(REPLACE(TD.PRCPROVVFINALEAG1, ',', '.') AS decimal(9, 4)) 
                      / 100 + RD.TOTPROVVAGEURO1 * TD.SEGNO AS TOTPROVVAG1EURO, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * CAST(REPLACE(TD.PRCPROVVFINALEAG2, ',', '.') AS decimal(9, 4)) 
                      / 100 + RD.TOTPROVVAGEURO2 * TD.SEGNO AS TOTPROVVAG2EURO, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * CAST(REPLACE(TD.PRCPROVVFINALEAG3, ',', '.') AS decimal(9, 4)) 
                      / 100 + RD.TOTPROVVAGEURO3 * TD.SEGNO AS TOTPROVVAG3EURO,
                          (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8) AS UMSTATART, TD.INCIDENZASCONTI, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END  AS TOTNETTISSIMO, 
					  CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGA * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGA * TD.SEGNO  END AS TOTNETTISSIMODIVISA, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END AS TOTNETTISSIMORES, 
					  dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGEST * FC.FATTORE * TD.SEGNO AS TOTCOSTOEURO, 
                      (CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END) - dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGEST * FC.FATTORE * TD.SEGNO AS MARGNETTISSIMO, 
					  dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS TOTCOSTOEURORES, 
                      (CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END) - dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS MARGNETTISSIMORES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO - dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGEST * FC.FATTORE * TD.SEGNO AS MARGNETTO, 
					  RD.TOTNETTORIGAEURORES * TD.SEGNO - dbo.LEGGIULTIMOPREZZO(RD.CODART,TD.DATADOC) * RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS MARGNETTORES, 
					  dbo.LEGGICLIENTEINTESTATARIO(RD.IDTESTARP)AS CLIENTEBOLLA, 
					  TD.CODCFFATT
FROM         dbo.TESTEDOCUMENTI TD INNER JOIN
                      dbo.RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA INNER JOIN
                      dbo.PARAMETRIDOC ON dbo.PARAMETRIDOC.CODICE = TD.TIPODOC AND dbo.PARAMETRIDOC.TIPO IN ('B') AND 
                      dbo.PARAMETRIDOC.CLIFOR = 'C' INNER JOIN
                      dbo.ARTICOLIFATTORICONVERSIONE FC ON RD.CODART = FC.CODART AND FC.UM1 = RD.UMGEST
WHERE     (FC.UM2 =
                          (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8))
GO
GRANT SELECT ON BRIOVISTABOLLECLIENTE TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTABOLLEFORNITORE') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTABOLLEFORNITORE
GO
CREATE VIEW dbo.BRIOVISTABOLLEFORNITORE
AS
SELECT     YEAR(TD.DATADOC) AS ANNODOC, MONTH(TD.DATADOC) AS MESE,STR(MONTH(TD.DATADOC), 2, 0) + ' - ' + DATENAME(MM, TD.DATADOC) AS MESEDOC, { fn WEEK(TD.DATADOC) 
                      } AS SETTDOC, DAY(TD.DATADOC) AS GIORNODOC, TD.TIPODOC + ' - ' + PARAMETRIDOC.DESCRIZIONE AS TIPODOC, TD.NUMERODOC, TD.DATADOC, TD.CODCLIFOR, TD.CODAGENTE1, 
                      TD.CODAGENTE2, TD.CODAGENTE3, TD.NUMDESTDIVERSAMERCI, TD.RAGSOCDDM, TD.PROVINCIADDM, TD.LOCALITADDM, TD.CODCAMBIO,
                      RD.IDRIGA AS PROGRIGADOC, RD.TIPORIGA, RD.CODART, RD.DATACONSEGNA, RD.RIFCOMMCLI, RD.NOMECOMMESSAPROD, RD.CODDEPOSITO, 
                      RD.QTAGEST * FC.FATTORE * TD.SEGNO AS QTASTAT, RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS QTASTATRES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO AS TOTNETTORIGAEURO,
					  RD.TOTNETTORIGA * TD.SEGNO AS TOTNETTORIGADIVISA,
					  RD.TOTNETTORIGAEURORES * TD.SEGNO AS TOTNETTORIGAEURORES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * CAST(REPLACE(TD.PRCPROVVFINALEAG1, ',', '.') AS decimal(9, 4)) 
                      / 100 + RD.TOTPROVVAGEURO1 * TD.SEGNO AS TOTPROVVAG1EURO, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * CAST(REPLACE(TD.PRCPROVVFINALEAG2, ',', '.') AS decimal(9, 4)) 
                      / 100 + RD.TOTPROVVAGEURO2 * TD.SEGNO AS TOTPROVVAG2EURO, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * CAST(REPLACE(TD.PRCPROVVFINALEAG3, ',', '.') AS decimal(9, 4)) 
                      / 100 + RD.TOTPROVVAGEURO3 * TD.SEGNO AS TOTPROVVAG3EURO,
                          (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8) AS UMSTATART, TD.INCIDENZASCONTI, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END  AS TOTNETTISSIMO, 
					  CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGA * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGA * TD.SEGNO  END AS TOTNETTISSIMODIVISA, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END AS TOTNETTISSIMORES, 
					  dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGEST * FC.FATTORE * TD.SEGNO AS TOTCOSTOEURO, 
                      (CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END) - dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGEST * FC.FATTORE * TD.SEGNO AS MARGNETTISSIMO, 
					  dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS TOTCOSTOEURORES, 
                      (CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END) - dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS MARGNETTISSIMORES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO - dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGEST * FC.FATTORE * TD.SEGNO AS MARGNETTO, 
					  RD.TOTNETTORIGAEURORES * TD.SEGNO - dbo.LEGGIULTIMOPREZZO(RD.CODART,TD.DATADOC) * RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS MARGNETTORES, 
					  dbo.LEGGICLIENTEINTESTATARIO(RD.IDTESTARP)AS CLIENTEBOLLA, 
					  TD.CODCFFATT
FROM         dbo.TESTEDOCUMENTI TD INNER JOIN
                      dbo.RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA INNER JOIN
                      dbo.PARAMETRIDOC ON dbo.PARAMETRIDOC.CODICE = TD.TIPODOC AND dbo.PARAMETRIDOC.TIPO IN ('B') AND 
                      dbo.PARAMETRIDOC.CLIFOR = 'F' INNER JOIN
                      dbo.ARTICOLIFATTORICONVERSIONE FC ON RD.CODART = FC.CODART AND FC.UM1 = RD.UMGEST
WHERE     (FC.UM2 =
                          (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8))
GO
GRANT SELECT ON BRIOVISTABOLLEFORNITORE TO METODO98
GO


IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAFATTFORNITORE') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAFATTFORNITORE
GO
CREATE VIEW dbo.BRIOVISTAFATTFORNITORE
AS
SELECT     YEAR(TD.DATADOC) AS ANNODOC, MONTH(TD.DATADOC) AS MESE,STR(MONTH(TD.DATADOC), 2, 0) + ' - ' + DATENAME(MM, TD.DATADOC) AS MESEDOC, { fn WEEK(TD.DATADOC) 
                      } AS SETTDOC, DAY(TD.DATADOC) AS GIORNODOC, TD.TIPODOC + ' - ' + PARAMETRIDOC.DESCRIZIONE AS TIPODOC, TD.NUMERODOC, TD.DATADOC, TD.CODCLIFOR,TD.CODCAMBIO, RD.IDRIGA AS PROGRIGADOC, RD.TIPORIGA, RD.CODART, RD.DATACONSEGNA, RD.RIFCOMMCLI, 
                      RD.NOMECOMMESSAPROD, RD.CODDEPOSITO, RD.QTAGEST * FC.FATTORE * TD.SEGNO AS QTASTAT, 
                      RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS QTASTATRES, RD.TOTNETTORIGAEURO * TD.SEGNO AS TOTNETTORIGAEURO, 
					  RD.TOTNETTORIGA * TD.SEGNO AS TOTNETTORIGADIVISA,
                      RD.TOTNETTORIGAEURORES * TD.SEGNO AS TOTNETTORIGAEURORES, 
                      (SELECT UM FROM  ARTICOLIUMPREFERITE UMP  WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8) AS UMSTATART, TD.INCIDENZASCONTI, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END AS TOTNETTISSIMO, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGA * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGA * TD.SEGNO END AS TOTNETTISSIMODIVISA, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END AS TOTNETTISSIMORES
FROM         dbo.TESTEDOCUMENTI TD INNER JOIN
                      dbo.RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA INNER JOIN
                      dbo.PARAMETRIDOC ON dbo.PARAMETRIDOC.CODICE = TD.TIPODOC AND dbo.PARAMETRIDOC.TIPO IN ('F', 'N') AND 
                      dbo.PARAMETRIDOC.CLIFOR = 'F' INNER JOIN
                      dbo.ARTICOLIFATTORICONVERSIONE FC ON RD.CODART = FC.CODART AND FC.UM1 = RD.UMGEST
WHERE     (FC.UM2 =
                          (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8))
GO                            
GRANT SELECT ON BRIOVISTAFATTFORNITORE TO METODO98
GO                           
                            
                            
IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAFOR') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAFOR
GO
CREATE VIEW dbo.BRIOVISTAFOR
AS
SELECT		AF.TIPOCONTO, AF.CODCONTO, AF.DSCCONTO1, AF.DSCCONTO2, AF.CODMASTRO, AF.INDIRIZZO, AF.CAP, AF.LOCALITA, AF.PROVINCIA, 
			AF.TELEFONO, AF.FAX, AF.TELEX, AF.CODFISCALE, AF.PARTITAIVA, AF.CODNAZIONE, AF.CODICEISO, AF.CODLINGUA, AF.NOTE, AF.UTENTEMODIFICA, 
			AF.DATAMODIFICA, RF.ESERCIZIO, RF.CODSETTORE, RF.CODZONA, RF.CODCATEGORIA, RF.CODSPED, RF.PRCTRASPORTO, RF.INOLTROTRASP, 
			RF.CODPAG, RF.MESEESCL1, RF.GGESCL1, RF.MESEESCL2, RF.GGESCL2,
               (SELECT CAB
                FROM   BANCAAPPCF
                WHERE  CODCONTO = RF.CODCONTO AND CODICE = BANCAANAGR) AS CAB,
               (SELECT ABI
                FROM   BANCAAPPCF
                WHERE  CODCONTO = RF.CODCONTO AND CODICE = BANCAANAGR) AS ABI,
               (SELECT CONTOCORRENTE
                FROM   BANCAAPPCF
                WHERE  CODCONTO = RF.CODCONTO AND CODICE = BANCAANAGR) AS CCDEBITORE, 
			RF.CODBANCA, RF.BANCAANAGR, RF.CODAGENTE1, 
            RF.CODAGENTE2, RF.CODAGENTE3, RF.PROVV1, RF.PROVV2, RF.PROVV3, RF.SCONTO1, RF.CODIVA, RF.DICHESIVA, RF.LISTINO, RF.CODCAMBIO, 
            RF.DESTDIVMERCI, RF.DESTDIVDOCUMENTI, RF.SPESEDOCUM, RF.SPESEEFFETTO, RF.SPESETRASPORTO, RF.SPESEIMBALLO, RF.FIDO, 
            RF.FIDOEURO, RF.PORTO, RF.TRASPACURA, RF.APPLSCONTORIGA, RF.APPLSCONTOFINALE, RF.CODCONTOFATT, RF.FATTFINEMESE, 
            RF.NONRAGGRUPPDOC, RF.CODDEPOSITO, RF.CODDEPOSITOCOLL, RF.CODDEPCOMP, RF.CODDEPCOMPCOLL, RF.RIVIVAOMAGGI, 
            RF.NRCONTROPCONT, RF.USAPRZPRVPART, RF.CODDEBITORE, RF.NOTE1, RF.STATOCONTABILITA, RF.STATOMAGAZZINO, RF.STATOORDINI, 
            RF.STATOBOLLE, RF.STATOFATTURE, RF.STATONOTEACCREDITO, RF.STATOALTRO, RF.CODGRUPPOPREZZIPART, RF.CODGRUPPOPROVPART, 
            RF.RAGGSCADENZE, AF.CODREGIONE, TR.DESCRIZIONE AS REGIONE

FROM    dbo.ANAGRAFICACF AF 
		INNER JOIN dbo.ANAGRAFICARISERVATICF RF ON AF.CODCONTO = RF.CODCONTO
		LEFT OUTER JOIN TABREGIONI TR ON AF.CODREGIONE=TR.CODICE
WHERE   (RF.ESERCIZIO =(SELECT MAX(CODICE) FROM TABESERCIZI)) AND (AF.TIPOCONTO IN ('F'))
GO
GRANT SELECT ON BRIOVISTAFOR TO METODO98
GO 




IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('BRIOVISTAORDINICLIENTI') AND TYPE = 'V')
    DROP VIEW BRIOVISTAORDINICLIENTI
GO
CREATE VIEW BRIOVISTAORDINICLIENTI
AS
SELECT				  YEAR(TD.DATADOC) AS ANNODOC, MONTH(TD.DATADOC) AS MESE,STR(MONTH(TD.DATADOC), 2, 0) + ' - ' + DATENAME(MM, TD.DATADOC) AS MESEDOC, 
					  { fn WEEK(TD.DATADOC)} AS SETTDOC, DAY(TD.DATADOC) AS GIORNODOC, 
					  YEAR(RD.DATACONSEGNA) AS ANNOCONS, STR(MONTH(RD.DATACONSEGNA), 2, 0)+ ' - ' + DATENAME(MM, RD.DATACONSEGNA) AS MESECONS, 
					  { fn WEEK(RD.DATACONSEGNA) } AS SETTCONS, DAY(RD.DATACONSEGNA) AS GIORNOCONS, 
					  TD.TIPODOC + ' - ' + PARAMETRIDOC.DESCRIZIONE AS TIPODOC, TD.NUMERODOC, TD.DATADOC, TD.CODCLIFOR, TD.CODAGENTE1, TD.CODAGENTE2, TD.CODAGENTE3, 
                      TD.CODCFFATT, RD.IDRIGA AS PROGRIGADOC, RD.TIPORIGA, RD.CODART, RD.DATACONSEGNA, RD.RIFCOMMCLI, RD.NOMECOMMESSAPROD, 
                      RD.CODDEPOSITO, 
					  TD.CODCAMBIO,
					  RD.QTAGEST * FC.FATTORE * TD.SEGNO AS QTASTAT,
					  RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS QTASTATRES,                      
	                  RD.TOTNETTORIGAEURO * TD.SEGNO AS TOTNETTORIGAEURO,
					  RD.TOTNETTORIGA * TD.SEGNO AS TOTNETTORIGADIVISA,
                      RD.TOTNETTORIGAEURORES * TD.SEGNO AS TOTNETTORIGAEURORES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * (CAST(REPLACE(TD.PRCPROVVFINALEAG1,',','.') as decimal(9,4))) / 100 + RD.TOTPROVVAGEURO1 * TD.SEGNO AS TOTPROVVAG1EURO, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * (CAST(REPLACE(TD.PRCPROVVFINALEAG2,',','.') as decimal(9,4)))/ 100 + RD.TOTPROVVAGEURO2 * TD.SEGNO AS TOTPROVVAG2EURO, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * (CAST(REPLACE(TD.PRCPROVVFINALEAG3,',','.') as decimal(9,4))) / 100 + RD.TOTPROVVAGEURO3 * TD.SEGNO AS TOTPROVVAG3EURO,
					  (SELECT UM FROM ARTICOLIUMPREFERITE UMP WHERE UMP.CODART=RD.CODART AND UMP.TIPOUM = 8) AS UMSTATART,                       
                      TD.INCIDENZASCONTI, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END AS TOTNETTISSIMO, 
					  CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGA * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGA * TD.SEGNO END AS TOTNETTISSIMODIVISA,
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END AS TOTNETTISSIMORES,
					  (DBO.LEGGIULTIMOPREZZO(RD.CODART,TD.DATADOC) * RD.QTAGEST * FC.FATTORE * TD.SEGNO) AS TOTCOSTOEURO,			
					  (CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END)-(DBO.LEGGIULTIMOPREZZO(RD.CODART,TD.DATADOC) * RD.QTAGEST * FC.FATTORE * TD.SEGNO) AS MARGNETTISSIMO,
					  (DBO.LEGGIULTIMOPREZZO(RD.CODART,TD.DATADOC) * RD.QTAGESTRES * FC.FATTORE * TD.SEGNO) AS TOTCOSTOEURORES,
					  (CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END)-(DBO.LEGGIULTIMOPREZZO(RD.CODART,TD.DATADOC) * RD.QTAGESTRES * FC.FATTORE * TD.SEGNO) AS MARGNETTISSIMORES,
					  (RD.TOTNETTORIGAEURO * TD.SEGNO)-(DBO.LEGGIULTIMOPREZZO(RD.CODART,TD.DATADOC) * RD.QTAGEST * FC.FATTORE * TD.SEGNO) AS MARGNETTO,
					  (RD.TOTNETTORIGAEURORES * TD.SEGNO)-(DBO.LEGGIULTIMOPREZZO(RD.CODART,TD.DATADOC) * RD.QTAGESTRES * FC.FATTORE * TD.SEGNO) AS MARGNETTORES

FROM         (((TESTEDOCUMENTI TD INNER JOIN RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA) INNER JOIN
                      PARAMETRIDOC ON dbo.PARAMETRIDOC.CODICE = TD.TIPODOC AND dbo.PARAMETRIDOC.TIPO = 'O' AND dbo.PARAMETRIDOC.CLIFOR = 'C')
			INNER JOIN ARTICOLIFATTORICONVERSIONE FC ON RD.CODART = FC.CODART and FC.UM1 = RD.UMGEST)
WHERE
	FC.UM2 = (SELECT UM FROM ARTICOLIUMPREFERITE UMP WHERE UMP.CODART=RD.CODART AND UMP.TIPOUM = 8)


GO
GRANT SELECT ON BRIOVISTAORDINICLIENTI TO METODO98
GO 







IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAORDINIFORNITORI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAORDINIFORNITORI
GO
CREATE VIEW dbo.BRIOVISTAORDINIFORNITORI
AS
SELECT				  YEAR(TD.DATADOC) AS ANNODOC, STR(MONTH(TD.DATADOC), 2, 0) + ' - ' + DATENAME(MM, TD.DATADOC) AS MESEDOC, 
					  {fn WEEK(TD.DATADOC)} AS SETTDOC, DAY(TD.DATADOC) AS GIORNODOC, YEAR(RD.DATACONSEGNA) AS ANNOCONS, 
					  STR(MONTH(RD.DATACONSEGNA), 2, 0)+ ' - ' + DATENAME(MM, RD.DATACONSEGNA) AS MESECONS, 
					  {fn WEEK(RD.DATACONSEGNA) } AS SETTCONS, DAY(RD.DATACONSEGNA)AS GIORNOCONS, 
					  TD.TIPODOC + ' - ' + PARAMETRIDOC.DESCRIZIONE AS TIPODOC, TD.NUMERODOC, TD.DATADOC, TD.CODCLIFOR, TD.CODCAMBIO,
                      RD.IDRIGA AS PROGRIGADOC, RD.TIPORIGA, RD.CODART, RD.DATACONSEGNA, RD.RIFCOMMCLI, RD.NOMECOMMESSAPROD, 
                      RD.CODDEPOSITO, RD.QTAGEST * FC.FATTORE * TD.SEGNO AS QTASTAT, RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS QTASTATRES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO AS TOTNETTORIGAEURO, 
                      RD.TOTNETTORIGA * TD.SEGNO AS TOTNETTORIGADIVISA,
					  RD.TOTNETTORIGAEURORES * TD.SEGNO AS TOTNETTORIGAEURORES, 
                            (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8) AS UMSTATART, TD.INCIDENZASCONTI, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END AS TOTNETTISSIMO, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGA * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGA * TD.SEGNO END AS TOTNETTISSIMODIVISA, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END AS TOTNETTISSIMORES
FROM		dbo.TESTEDOCUMENTI TD INNER JOIN
                      dbo.RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA INNER JOIN
                      dbo.PARAMETRIDOC ON dbo.PARAMETRIDOC.CODICE = TD.TIPODOC AND dbo.PARAMETRIDOC.TIPO = 'O' AND 
                      dbo.PARAMETRIDOC.CLIFOR = 'F' INNER JOIN
                      dbo.ARTICOLIFATTORICONVERSIONE FC ON RD.CODART = FC.CODART AND FC.UM1 = RD.UMGEST
WHERE     (FC.UM2 =
                          (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8))

GO
GRANT SELECT ON BRIOVISTAORDINIFORNITORI TO METODO98
GO 





IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAORDINIPRODUZIONE') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAORDINIPRODUZIONE
GO
CREATE VIEW dbo.BRIOVISTAORDINIPRODUZIONE
AS
SELECT     TESTEORDINIPROD.TIPOCOM, TESTEORDINIPROD.TIPOCOM + '/' + cast(TESTEORDINIPROD.ESERCIZIO AS varchar) 
                      + '/' + RIGHT('0000000000' + cast(TESTEORDINIPROD.NUMEROCOM AS varchar), 10) + '/' + RIGHT('00000' + cast(RIGHEORDPROD.IDRIGA AS varchar),
                       5) AS RIFORDINE, TESTEORDINIPROD.NUMEROCOM, TESTEORDINIPROD.ESERCIZIO, TESTEORDINIPROD.STATOBLOCCATO, TESTEORDINIPROD.DATAEMISSIONE,
                      (CASE WHEN TESTEORDINIPROD.STATOCHIUSO=0 THEN 'Aperto' ELSE 'Chiuso' END) AS STATOCHIUSO, 
RIGHEORDPROD.IDTESTA, 
RIGHEORDPROD.IDRIGA, 
RIGHEORDPROD.CODICEORD,
                          (CASE WHEN (SELECT     TIPOORDINE
                            FROM          PARAMETRIORDPROD
                            WHERE      PARAMETRIORDPROD.CODICE = RIGHEORDPROD.CODICEORD)=0 THEN 'Ordine produzione interna' ELSE (CASE WHEN(SELECT     TIPOORDINE
                            FROM          PARAMETRIORDPROD
                            WHERE      PARAMETRIORDPROD.CODICE = RIGHEORDPROD.CODICEORD)=1 THEN 'Ordine conto lavoro attivo' ELSE 'Ordine conto lavoro passivo' END) END) AS TIPOORD, RIGHEORDPROD.CODART AS CODARTORD,
RIGHEORDPROD.DESCRIZIONEART, 
RIGHEORDPROD.VERSIONEDBA, 
RIGHEORDPROD.VERSIONECICLO, 
RIGHEORDPROD.UMGEST, 
RIGHEORDPROD.UM1MAG AS UMBASE,
RIGHEORDPROD.QTAGESTIONE, 
RIGHEORDPROD.QTAGESTIONEVERS, 
RIGHEORDPROD.QTAGESTIONERES, 
RIGHEORDPROD.QTAPREZZO, 
RIGHEORDPROD.UMPREZZO, 
RIGHEORDPROD.QTA1MAG, 
(RIGHEORDPROD.QTAGESTIONEVERS*(CASE WHEN(RIGHEORDPROD.QTAGESTIONE=0) THEN 0 ELSE(
				RIGHEORDPROD.QTA1MAG/RIGHEORDPROD.QTAGESTIONE) END
			       )) AS QTA1MAGVERS,
RIGHEORDPROD.QTA2MAG, 
RIGHEORDPROD.QTA1MAGRES, 
RIGHEORDPROD.QTA2MAGRES, 
RIGHEORDPROD.QTASCARTO, 
RIGHEORDPROD.UMSCARTO, 
                      (CASE WHEN RIGHEORDPROD.QTAGESTIONE <> 0 THEN RIGHEORDPROD.QTAGESTIONEVERS / RIGHEORDPROD.QTAGESTIONE * 100 ELSE 0 END) 
                      AS AVANZQTA, 
                      (CASE WHEN RIGHEORDPROD.COSTOTOTORDPREV <> 0 THEN RIGHEORDPROD.COSTOTOTORDEFF / RIGHEORDPROD.COSTOTOTORDPREV * 100 ELSE
                       0 END) AS AVANZCOSTI,
RIGHEORDPROD.RIFCOMMCLI,
RIGHEORDPROD.UM1MAG AS UM1, 
RIGHEORDPROD.UM2MAG AS UM2,
RIGHEORDPROD.CODCLIDEST,
RIGHEORDPROD.PARTITAASSEGNATA, 
RIGHEORDPROD.CODFORDEST,
RIGHEORDPROD.DATAEMISSIONE AS DATAEMISSIONEORD,
YEAR(RIGHEORDPROD.DATAEMISSIONE) AS ANNOORD,
STR(MONTH(RIGHEORDPROD.DATAEMISSIONE), 2, 0) + ' - ' + DATENAME(MM, RIGHEORDPROD.DATAEMISSIONE) AS MESEORD,
(CASE WHEN RIGHEORDPROD.STATOORDINE=0 THEN 'Aperto' ELSE (CASE WHEN RIGHEORDPROD.STATOORDINE=1 THEN 'Prelevato' ELSE (CASE WHEN RIGHEORDPROD.STATOORDINE=2 THEN 'Versato' ELSE 'Chiuso' END) END) END) AS STATOORDINE  , 
(CASE WHEN RIGHEORDPROD.FASERILASCIO=0 THEN 'Emesso' ELSE (CASE WHEN RIGHEORDPROD.FASERILASCIO=1 THEN 'Lanciato' ELSE 'Chiuso' END) END) AS FASERILASCIO,
RIGHEORDPROD.DATARILASCIO,
YEAR(RIGHEORDPROD.DATARILASCIO) AS ANNORILASCIO,
STR(MONTH(RIGHEORDPROD.DATARILASCIO), 2, 0) + ' - ' + DATENAME(MM, RIGHEORDPROD.DATARILASCIO) AS MESERILASCIO,
RIGHEORDPROD.DATAINIZIOSCHED, 
RIGHEORDPROD.DATAFINESCHED,
RIGHEORDPROD.DATAINIZIORICH, 
YEAR(RIGHEORDPROD.DATAINIZIORICH) AS ANNOINIZIORICH,
STR(MONTH(RIGHEORDPROD.DATAINIZIORICH), 2, 0) + ' - ' + DATENAME(MM, RIGHEORDPROD.DATAINIZIORICH) AS MESEINIZIORICH,
RIGHEORDPROD.DATAFINERICH,
YEAR(RIGHEORDPROD.DATAFINERICH) AS ANNOFINERICH,
STR(MONTH(RIGHEORDPROD.DATAFINERICH), 2, 0) + ' - ' + DATENAME(MM, RIGHEORDPROD.DATAFINERICH) AS MESEFINERICH,
RIGHEORDPROD.DATAINIZIOEFF,
YEAR(RIGHEORDPROD.DATAINIZIOEFF) AS ANNOINIZIOEFF,
STR(MONTH(RIGHEORDPROD.DATAINIZIOEFF), 2, 0) + ' - ' + DATENAME(MM, RIGHEORDPROD.DATAINIZIOEFF) AS MESEINIZIOEFF, 
RIGHEORDPROD.DATAFINEEFF,
YEAR(RIGHEORDPROD.DATAFINEEFF) AS ANNOFINEEFF,
STR(MONTH(RIGHEORDPROD.DATAFINEEFF), 2, 0) + ' - ' + DATENAME(MM, RIGHEORDPROD.DATAFINEEFF) AS MESEFINEEFF,
RIGHEORDPROD.DATAULTATTIVITA, 
RIGHEORDPROD.DEPOSITO, 
RIGHEORDPROD.CONTOCDC, 
RIGHEORDPROD.VALOREPRIORITA, 
RIGHEORDPROD.COSTOMATPREV, 
RIGHEORDPROD.COSTOLAVINTPREV, 
RIGHEORDPROD.COSTOLAVESTPREV, 
RIGHEORDPROD.COSTOINDPREV, 
RIGHEORDPROD.COSTOUNITORDPREV, 
RIGHEORDPROD.COSTOTOTORDPREV, 
RIGHEORDPROD.COSTOMATPREVEURO,               
RIGHEORDPROD.COSTOLAVINTPREVEURO, 
RIGHEORDPROD.COSTOLAVESTPREVEURO, 
RIGHEORDPROD.COSTOINDPREVEURO, 
RIGHEORDPROD.COSTOUNITORDPREVEURO, 
RIGHEORDPROD.COSTOTOTORDPREVEURO, 
RIGHEORDPROD.COSTOMATEFF, 
RIGHEORDPROD.COSTOLAVINTEFF, 
RIGHEORDPROD.COSTOLAVESTEFF, 
RIGHEORDPROD.COSTOINDEFF, 
RIGHEORDPROD.COSTOUNITORDEFF, 
RIGHEORDPROD.COSTOTOTORDEFF, 
RIGHEORDPROD.COSTOMATEFFEURO, 
RIGHEORDPROD.COSTOLAVINTEFFEURO, 
RIGHEORDPROD.COSTOLAVESTEFFEURO, 
RIGHEORDPROD.COSTOINDEFFEURO, 
RIGHEORDPROD.COSTOUNITORDEFFEURO, 
RIGHEORDPROD.COSTOTOTORDEFFEURO, 
VISTAANAGRAFICAARTICOLI.GRUPPO, 
VISTAANAGRAFICAARTICOLI.CATEGORIA, 
VISTAANAGRAFICAARTICOLI.VARESPLICITE, 
VISTAANAGRAFICAARTICOLI.TIPOGESTIONE, 
RIGHEORDPROD.STATOLANCIO, 
RIGHEORDPROD.DATALANCIO
FROM         (TESTEORDINIPROD LEFT OUTER JOIN
                      (RIGHEORDPROD LEFT OUTER JOIN
                      VISTAANAGRAFICAARTICOLI ON VISTAANAGRAFICAARTICOLI.CODICE = RIGHEORDPROD.CODART) ON 
                      TESTEORDINIPROD.PROGRESSIVO = RIGHEORDPROD.IDTESTA)
GO
GRANT SELECT ON BRIOVISTAORDINIPRODUZIONE TO METODO98
GO 






IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTASCADENZEALL') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTASCADENZEALL
GO
CREATE VIEW dbo.BRIOVISTASCADENZEALL
AS
SELECT     TIPOSCADENZA = 1, TS .ESERCIZIO, TS .ANNODOC, STR(MONTH(TS.DATAFATTURA), 2, 0) + ' - ' + DATENAME(MM, TS.DATAFATTURA) AS MESEDOC,{ fn WEEK(TS.DATAFATTURA) 
                      } AS SETTDOC, TS .TIPODOC, TS .NUMDOC, TS .NUMRIF, TS .DATAFATTURA, TS .NUMEROPROT, 
                      TS .TIPOEFFETTO, TS .ESITO, SUBSTRING('Attivi Passivi', (1 - SCADATTPASS) * 7 + 1, 7) AS DESSCADATTPASS,
                      TS .DATASCADENZA,
                      YEAR(TS.DATASCADENZA) AS ANNOSCAD,
                      STR(MONTH(TS.DATASCADENZA), 2, 0) + ' - ' + DATENAME(MM, TS.DATASCADENZA) AS MESESCAD,
                      { fn WEEK(TS.DATASCADENZA) } AS SETTSCAD,
                      ISNULL (TS .DATAPAGEFF, (select (CASE WHEN (datediff (dd, ts.datascadenza, getdate()) < 0) then ts.datascadenza else getdate() END))) AS DATAPAGEFF,
                       YEAR(( ISNULL (TS .DATAPAGEFF, (select (CASE WHEN (datediff (dd, ts.datascadenza, getdate()) < 0) then ts.datascadenza else getdate() END))))) AS ANNOPAGEFF,
                      STR(MONTH(( ISNULL (TS .DATAPAGEFF, (select (CASE WHEN (datediff (dd, ts.datascadenza, getdate()) < 0) then ts.datascadenza else getdate() END))))), 2, 0) + ' - ' + DATENAME(MM, ( ISNULL (TS .DATAPAGEFF, (select (CASE WHEN (datediff (dd, ts.datascadenza, getdate()) < 0) then ts.datascadenza else getdate() END))))) AS MESEPAGEFF,
                      { fn WEEK(( ISNULL (TS .DATAPAGEFF, (select (CASE WHEN (datediff (dd, ts.datascadenza, getdate()) < 0) then ts.datascadenza else getdate() END))))) } AS SETTPAGEFF,
                       TS .BANCAINC, TS .NRDISTINTA, TS .CODCLIFOR, TS .FLAGCONT, TS .CODCAMBIO, 
                          (SELECT     CODNAZIONE
                            FROM          ANAGRAFICACF
                            WHERE      ANAGRAFICACF.CODCONTO = TS .CODCLIFOR) AS NAZIONE,
                          (SELECT     CODSETTORE
                            FROM          ANAGRAFICARISERVATICF
                            WHERE      ANAGRAFICARISERVATICF.CODCONTO = TS .CODCLIFOR AND ESERCIZIO =
                                                       (SELECT     MAX(Codice)
                                                         FROM          TABEsercizi)) AS CODSETTORE,
                          (SELECT     CODZONA
                            FROM          ANAGRAFICARISERVATICF
                            WHERE      ANAGRAFICARISERVATICF.CODCONTO = TS .CODCLIFOR AND ESERCIZIO =
                                                       (SELECT     MAX(Codice)
                                                         FROM          TABEsercizi)) AS CODZONA,
                          (SELECT     CODCATEGORIA
                            FROM          ANAGRAFICARISERVATICF
                            WHERE      ANAGRAFICARISERVATICF.CODCONTO = TS .CODCLIFOR AND ESERCIZIO =
                                                       (SELECT     MAX(Codice)
                                                         FROM          TABEsercizi)) AS CODCATEGORIACF, TS .CODAGE1, TS .CODAGE2, TS .CODAGE3, (CASE WHEN ((TS .SCADATTPASS <> 0 AND
                       SUBSTRING(TS .CODCLIFOR, 1, 1) <> 'C') OR
                      (TS .SCADATTPASS = 0 AND SUBSTRING(TS .CODCLIFOR, 1, 1) = 'C')) THEN (TS .IMPPROVEURO1 * - 1) ELSE TS .IMPPROVEURO1 END) 
                      AS IMPPROVEURO1, (CASE WHEN ((TS .SCADATTPASS = 0 AND SUBSTRING(TS .CODCLIFOR, 1, 1) <> 'C') OR
                      (TS .SCADATTPASS = 0 AND SUBSTRING(TS .CODCLIFOR, 1, 1) = 'C')) THEN (TS .IMPPROVEURO2 * - 1) ELSE TS .IMPPROVEURO2 END) 
                      AS IMPPROVEURO2, (CASE WHEN ((TS .SCADATTPASS = 0 AND SUBSTRING(TS .CODCLIFOR, 1, 1) <> 'C') OR
                      (TS .SCADATTPASS = 0 AND SUBSTRING(TS .CODCLIFOR, 1, 1) = 'C')) THEN (TS .IMPPROVEURO3 * - 1) ELSE TS .IMPPROVEURO3 END) 
                      AS IMPPROVEURO3, (CASE WHEN ((TS .SCADATTPASS = 0 AND SUBSTRING(TS .CODCLIFOR, 1, 1) <> 'C') OR
                      (TS .SCADATTPASS = 0 AND SUBSTRING(TS .CODCLIFOR, 1, 1) = 'C')) THEN (TS .IMPORTOSCEURO * - 1) ELSE TS .IMPORTOSCEURO END) 
                      AS IMPORTOSCADEURO, (CASE WHEN ((TS .SCADATTPASS = 0 AND SUBSTRING(TS .CODCLIFOR, 1, 1) <> 'C') OR
                      (TS .SCADATTPASS = 0 AND SUBSTRING(TS .CODCLIFOR, 1, 1) = 'C')) THEN (TS .TOTFATTEURO * - 1) ELSE TS .TOTFATTEURO END) 
                      AS TOTFATTURAEURO,
                      (CASE WHEN ((TS .SCADATTPASS = 0 AND SUBSTRING(TS .CODCLIFOR, 1, 1) <> 'C') OR
                      (TS .SCADATTPASS = 0 AND SUBSTRING(TS .CODCLIFOR, 1, 1) = 'C')) THEN (TS .IMPORTOSCVAL * - 1) ELSE TS .IMPORTOSCVAL END) 
                      AS IMPORTOSCVAL,
                      (CASE WHEN ((TS .SCADATTPASS = 0 AND SUBSTRING(TS .CODCLIFOR, 1, 1) <> 'C') OR
                      (TS .SCADATTPASS = 0 AND SUBSTRING(TS .CODCLIFOR, 1, 1) = 'C')) THEN (TS .IMPFATTVAL *  - 1) ELSE TS .IMPFATTVAL END) 
                      AS IMPFATTVAL

FROM         TABSCADENZE TS
WHERE NUMSCAD<>-1
UNION ALL
SELECT     TIPOSCADENZA = 2, SP.ESERCIZIO, SP.ANNODOC, STR(MONTH(SP.DATAFATTURA), 2, 0) + ' - ' + DATENAME(MM, SP.DATAFATTURA) AS MESEDOC,{ fn WEEK(SP.DATAFATTURA) 
                      } AS SETTDOC, SP.TIPODOC, SP.NUMDOC, SP.NUMRIF, SP.DATAFATTURA, SP.NUMEROPROT, SP.TIPOEFFETTO, 
                      SP.ESITO, SUBSTRING('Attivi Passivi', (1 - SCADATTPASS) * 7 + 1, 7) AS DESSCADATTPASS, SP.DATASCADENZA, YEAR(SP.DATASCADENZA) AS ANNOSCAD, 
                       STR(MONTH(SP.DATASCADENZA), 2, 0) + ' - ' + DATENAME(MM, SP.DATASCADENZA) AS MESESCAD,
                      { fn WEEK(SP.DATASCADENZA) } AS SETTSCAD,
                      ISNULL (SP .DATAPAGEFF, (select (CASE WHEN (datediff (dd, SP.DATASCADENZA, getdate()) < 0) then SP.DATASCADENZA else getdate() END))) AS DATAPAGEFF,
                      YEAR(( ISNULL (SP .DATAPAGEFF, (select (CASE WHEN (datediff (dd, SP.DATASCADENZA, getdate()) < 0) then SP.DATASCADENZA else getdate() END))))) AS ANNOPAGEFF,
                      STR(MONTH(( ISNULL (SP .DATAPAGEFF, (select (CASE WHEN (datediff (dd, SP.DATASCADENZA, getdate()) < 0) then SP.DATASCADENZA else getdate() END))))), 2, 0) + ' - ' + DATENAME(MM, ( ISNULL (SP .DATAPAGEFF, (select (CASE WHEN (datediff (dd, SP.DATASCADENZA, getdate()) < 0) then SP.DATASCADENZA else getdate() END))))) AS MESEPAGEFF,
                      { fn WEEK(( ISNULL (SP .DATAPAGEFF, (select (CASE WHEN (datediff (dd, SP.DATASCADENZA, getdate()) < 0) then SP.DATASCADENZA else getdate() END))))) } AS SETTPAGEFF,
                      SP.BANCAINC, 
                      SP.NRDISTINTA, SP.CODCLIFOR, SP.FLAGCONT, SP.CODCAMBIO, 
                          (SELECT     CODNAZIONE
                            FROM          ANAGRAFICACF
                            WHERE      ANAGRAFICACF.CODCONTO = SP.CODCLIFOR) AS NAZIONE,
                          (SELECT     CODSETTORE
                            FROM          ANAGRAFICARISERVATICF
                            WHERE      ANAGRAFICARISERVATICF.CODCONTO = SP.CODCLIFOR AND ESERCIZIO =
                                                       (SELECT     MAX(Codice)
                                                         FROM          TABEsercizi)) AS CODSETTORE,
                          (SELECT     CODZONA
                            FROM          ANAGRAFICARISERVATICF
                            WHERE      ANAGRAFICARISERVATICF.CODCONTO = SP.CODCLIFOR AND ESERCIZIO =
                                                       (SELECT     MAX(Codice)
                                                         FROM          TABEsercizi)) AS CODZONA,
                          (SELECT     CODCATEGORIA
                            FROM          ANAGRAFICARISERVATICF
                            WHERE      ANAGRAFICARISERVATICF.CODCONTO = SP.CODCLIFOR AND ESERCIZIO =
                                                       (SELECT     MAX(Codice)
                                                         FROM          TABEsercizi)) AS CODCATEGORIACF, SP.CODAGE1, SP.CODAGE2, SP.CODAGE3, (CASE WHEN ((SP.SCADATTPASS <> 0 AND 
                      SUBSTRING(SP.CODCLIFOR, 1, 1) <> 'C') OR
                      (SP.SCADATTPASS = 0 AND SUBSTRING(SP.CODCLIFOR, 1, 1) = 'C')) THEN (SP.IMPPROVEURO1 * - 1) ELSE SP.IMPPROVEURO1 END) 
                      AS IMPPROVEURO1, (CASE WHEN ((SP.SCADATTPASS <> 0 AND SUBSTRING(SP.CODCLIFOR, 1, 1) <> 'C') OR
                      (SP.SCADATTPASS = 0 AND SUBSTRING(SP.CODCLIFOR, 1, 1) = 'C')) THEN (SP.IMPPROVEURO2 * - 1) ELSE SP.IMPPROVEURO2 END) 
                      AS IMPPROVEURO2, (CASE WHEN ((SP.SCADATTPASS <> 0 AND SUBSTRING(SP.CODCLIFOR, 1, 1) <> 'C') OR
                      (SP.SCADATTPASS = 0 AND SUBSTRING(SP.CODCLIFOR, 1, 1) = 'C')) THEN (SP.IMPPROVEURO3 * - 1) ELSE SP.IMPPROVEURO3 END) 
                      AS IMPPROVEURO3, (CASE WHEN ((SP.SCADATTPASS <> 0 AND SUBSTRING(SP.CODCLIFOR, 1, 1) <> 'C') OR
                      (SP.SCADATTPASS = 0 AND SUBSTRING(SP.CODCLIFOR, 1, 1) = 'C')) THEN (SP.IMPORTOSCEURO * - 1) ELSE SP.IMPORTOSCEURO END) 
                      AS IMPORTOSCADEURO, (CASE WHEN ((SP.SCADATTPASS <> 0 AND SUBSTRING(SP.CODCLIFOR, 1, 1) <> 'C') OR
                      (SP.SCADATTPASS = 0 AND SUBSTRING(SP.CODCLIFOR, 1, 1) = 'C')) THEN (SP.TOTFATTEURO * - 1) ELSE SP.TOTFATTEURO END) 
                      AS TOTFATTURAEURO,
                      (CASE WHEN ((SP.SCADATTPASS = 0 AND SUBSTRING(SP.CODCLIFOR, 1, 1) <> 'C') OR
                      (SP.SCADATTPASS = 0 AND SUBSTRING(SP.CODCLIFOR, 1, 1) = 'C')) THEN (SP.IMPORTOSCVAL * - 1) ELSE SP.IMPORTOSCVAL END) 
                      AS IMPORTOSCVAL,
                      (CASE WHEN ((SP.SCADATTPASS = 0 AND SUBSTRING(SP.CODCLIFOR, 1, 1) <> 'C') OR
                      (SP.SCADATTPASS = 0 AND SUBSTRING(SP.CODCLIFOR, 1, 1) = 'C')) THEN (SP.IMPFATTVAL *  - 1) ELSE SP.IMPFATTVAL  END) 
                      AS IMPFATTVAL
FROM         SCADENZEPREVISIONALI SP
WHERE NUMSCAD<>-1
GO
GRANT SELECT ON BRIOVISTASCADENZEALL TO METODO98
GO


IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOANAGRAFICADEPOSITI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOANAGRAFICADEPOSITI
GO
CREATE VIEW dbo.BRIOANAGRAFICADEPOSITI AS
SELECT
CODICE, DESCRIZIONE, CASE WHEN DISPONIBILE = 1 THEN 'Crea disponibilità' else 'Non crea disponibilità' end as DISPONIBILE
FROM ANAGRAFICADEPOSITI
GO
GRANT SELECT ON BRIOANAGRAFICADEPOSITI TO METODO98
GO 

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTASTORICOAVANZAMENTI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTASTORICOAVANZAMENTI
GO
CREATE VIEW dbo.BRIOVISTASTORICOAVANZAMENTI AS
SELECT *
FROM STORICOAVANZAMENTI
GO
GRANT SELECT ON BRIOVISTASTORICOAVANZAMENTI TO METODO98
GO 

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTADIPENDENTIMOVIMENTO') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTADIPENDENTIMOVIMENTO
GO
CREATE VIEW dbo.BRIOVISTADIPENDENTIMOVIMENTO AS
SELECT *
FROM DIPENDENTIMOVIMENTO
GO
GRANT SELECT ON BRIOVISTADIPENDENTIMOVIMENTO TO METODO98
GO 

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAGIACENZE') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAGIACENZE
GO
CREATE VIEW BRIOVISTAGIACENZE  AS 
SELECT STMAG.BIS,
    STMAG.CODART,
    STMAG.CODCAMBIO,
    STMAG.CODCAUSALE,    
    STMAG.CODCLIFOR,
    STMAG.CODCOMMESSA,
    STMAG.CODDEPOSITO,
    STMAG.CODPAG,
    STMAG.CODUBICAZIONE,
    STMAG.CONTOCDCMOV,
    STMAG.DATAMOV,
    STMAG.DATARIFDOC,
    STMAG.DESTDIV,
    STMAG.GENVENACQ,
    STMAG.IDDISTINTABASE,
    STMAG.IDTESTA,
    STMAG.IMPORTOTOTLORDO,
    STMAG.IMPORTOTOTLORDOEURO,
    STMAG.IMPORTOTOTLORDOVAL,
    STMAG.IMPORTOTOTNETTO,
    STMAG.IMPORTOTOTNETTOEURO,
    STMAG.IMPORTOTOTNETTOVAL,
    STMAG.LISTINO,
    STMAG.NRIFDOC,
    STMAG.NRIFPARTITA,
    STMAG.NUMERODOC,
    STMAG.PROGRCOLLEGATO,
    STMAG.PROGRESSIVO,
    STMAG.QTA1UM,
    STMAG.QTA2UM,
    STMAG.RIFERIMENTI,
    STMAG.RIGACOMP,
    STMAG.RIGADOC,
    STMAG.SCONTO,
    STMAG.TIPODOC,
    STMAG.TIPOMOV,
    STMAG.VALCAMBIO,
    STMAG.VARIANTE,
    STMAG.ESERCIZIO,
    STMAG.DATADISP,
    STMAG.RESO,
    (STMAG.QTA1UM*STMAG.ORDINATO) AS ORDINATO,
    (STMAG.QTA1UM*STMAG.IMPEGNATO) AS IMPEGNATO,
    (STMAG.QTA2UM*STMAG.ORDINATO2UM) AS ORDINATO2UM,
    (STMAG.QTA2UM*STMAG.IMPEGNATO2UM) AS IMPEGNATO2UM,
    (STMAG.QTA1UM*STMAG.QUANTITACARICO) AS QTACARICO,
    (STMAG.QTA1UM*STMAG.QUANTITASCARICO) AS QTASCARICO,
    (STMAG.QTA2UM*STMAG.QUANTITACARICO) AS QTACARICO2UM,
    (STMAG.QTA2UM*STMAG.QUANTITASCARICO) AS QTASCARICO2UM,
    (STMAG.IMPORTOTOTNETTO*STMAG.VALORECARICO) AS VALORECARICO,
    (STMAG.IMPORTOTOTNETTO*STMAG.VALORESCARICO) AS VALORESCARICO,
    (STMAG.IMPORTOTOTNETTOEURO*STMAG.VALORECARICO) AS VALORECARICOEURO,
    (STMAG.IMPORTOTOTNETTOEURO*STMAG.VALORESCARICO) AS VALORESCARICOEURO,
    (CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) AS CARICO,
    (CASE WHEN STMAG.GIACENZA2UM=1 and STMAG.RESO = 0 THEN STMAG.QTA2UM ELSE 0 END) AS CARICO2UM,
    (CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 0 THEN STMAG.QTA1UM ELSE 0 END) AS SCARICO,
    (CASE WHEN STMAG.GIACENZA2UM=-1 and STMAG.RESO = 0 THEN STMAG.QTA2UM ELSE 0 END) AS SCARICO2UM,
    (CASE WHEN STMAG.GIACENZA=-1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) AS RESODACARICO,
    (CASE WHEN STMAG.GIACENZA2UM=-1 and STMAG.RESO = 1 THEN STMAG.QTA2UM ELSE 0 END) AS RESODACARICO2UM,
    (CASE WHEN STMAG.GIACENZA=1 and STMAG.RESO = 1 THEN STMAG.QTA1UM ELSE 0 END) AS RESODASCARICO,
    (CASE WHEN STMAG.GIACENZA2UM=1 and STMAG.RESO = 1 THEN STMAG.QTA2UM ELSE 0 END) AS RESODASCARICO2UM,
    STMAG.QUANTITACARICO AS FLGQTACARICO,
    STMAG.ORDINATO AS FLGORDINATO,
    STMAG.IMPEGNATO AS FLGIMPEGNATO,
    STMAG.ORDINATO2UM AS FLGORDINATO2UM,
    STMAG.IMPEGNATO2UM AS FLGIMPEGNATO2UM
    FROM STORICOMAG AS STMAG
GO
GRANT SELECT ON BRIOVISTAGIACENZE TO METODO98
GO 


IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTALISTINI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTALISTINI
GO
CREATE VIEW BRIOVISTALISTINI
AS
SELECT
NRLISTINO, DESCRIZIONE
FROM TABLISTINI
GO
GRANT SELECT ON BRIOVISTALISTINI TO METODO98
GO 


IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTALISTINIRIGHE') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTALISTINIRIGHE
GO
CREATE VIEW BRIOVISTALISTINIRIGHE
AS
SELECT
LA.CODART, LA.NRLISTINO, LA.UM, LA.PREZZOEURO*FC.FATTORE AS PREZZOEURO, FC.FATTORE
FROM LISTINIARTICOLI LA
INNER JOIN ARTICOLIFATTORICONVERSIONE FC ON LA.CODART=FC.CODART AND FC.UM2=LA.UM
WHERE FC.UM1= (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = LA.CODART AND UMP.TIPOUM = 1)

GO
GRANT SELECT ON BRIOVISTALISTINIRIGHE TO METODO98
GO 


IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABREPARTI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABREPARTI
GO
CREATE VIEW dbo.BRIOVISTATABREPARTI
AS
SELECT     *
FROM         dbo.TABELLAREPARTI
GO
GRANT SELECT ON BRIOVISTATABREPARTI TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTATABTIPIOPERAZIONI') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTATABTIPIOPERAZIONI
GO
CREATE VIEW dbo.BRIOVISTATABTIPIOPERAZIONI
AS
SELECT     *
FROM         dbo.TABTIPIOPERAZIONI
GO
GRANT SELECT ON BRIOVISTATABTIPIOPERAZIONI TO METODO98
GO 

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTA_TMP_PROMOZIONI_DO') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTA_TMP_PROMOZIONI_DO
GO
CREATE VIEW dbo.BRIOVISTA_TMP_PROMOZIONI_DO AS
SELECT
TP.NUMEROPROMOZIONE, TP.NUMEROCAMPAGNA,TP.TIPO, TP.DESCPROMO,TP.DESCCAMPAGNA, 
(CASE WHEN(TP.TIPO=0) THEN TP.CODICE_DETT ELSE (TP.CODICE_COND)END) AS CODART,
(CASE WHEN(TP.TIPO=0) THEN TP.UM_M_DETT ELSE (CASE WHEN(TP.TIPO=1 AND TP.UM_M='')THEN UM_M_COND ELSE UM_M END)END) AS UM,
(CASE WHEN(TP.TIPO=0) THEN TP.QTABUDGET_DETT ELSE (CASE WHEN(TP.TIPO=1 AND TP.UM_M='')THEN QTABUDGET_COND ELSE TP.QTABUDGET END)END) AS BDG_QTA,
(CASE WHEN(TP.TIPO=0) THEN TP.VALOREBUDGET_DETT ELSE (CASE WHEN(TP.TIPO=1 AND TP.UM_M='')THEN VALOREBUDGET_COND ELSE TP.VALOREBUDGET END)END) AS BDG_VALORE
FROM TP_VISTAPROMOZIONI TP
GO
GRANT SELECT ON dbo.BRIOVISTA_TMP_PROMOZIONI_DO TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAFATTCLIENTE_DO') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAFATTCLIENTE_DO
GO
CREATE VIEW dbo.BRIOVISTAFATTCLIENTE_DO
AS
SELECT				  TD.ESERCIZIO,YEAR(TD.DATADOC) AS ANNODOC,MONTH(TD.DATADOC) AS MESE, STR(MONTH(TD.DATADOC), 2, 0) + ' - ' + DATENAME(MM, TD.DATADOC) AS MESEDOC, 
					  { fn WEEK(TD.DATADOC)} AS SETTDOC, DAY(TD.DATADOC) AS GIORNODOC, 
					  TD.TIPODOC + ' - ' + PARAMETRIDOC.DESCRIZIONE AS TIPODOC, TD.NUMERODOC, TD.DATADOC, TD.CODCLIFOR, TD.CODAGENTE1, TD.CODAGENTE2, TD.CODAGENTE3, 
					  TD.NUMDESTDIVERSAMERCI, TD.RAGSOCDDM, TD.PROVINCIADDM, TD.LOCALITADDM,
                      RD.IDRIGA AS PROGRIGADOC, RD.TIPORIGA, RD.CODART, RD.DATACONSEGNA, RD.RIFCOMMCLI, RD.NOMECOMMESSAPROD, 
                      RD.CODDEPOSITO, RD.QTAGEST * FC.FATTORE * TD.SEGNO AS QTASTAT, RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS QTASTATRES, 
					  CASE WHEN(RD.TIPORIGA='O') THEN 0 ELSE ( RD.QTAGEST * FC.FATTORE * TD.SEGNO) END AS QTASTAT_SENZAOMAGGI,
                      RD.TOTNETTORIGAEURO * TD.SEGNO AS TOTNETTORIGAEURO, RD.TOTLORDORIGAEURO*TD.SEGNO AS TOTLORDORIGAEURO,
					  RD.TOTNETTORIGA * TD.SEGNO AS TOTNETTORIGADIVISA,
					  RD.TOTNETTORIGAEURORES * TD.SEGNO AS TOTNETTORIGAEURORES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * (CAST(REPLACE(TD.PRCPROVVFINALEAG1,',','.') as decimal(9,4))) / 100 + RD.TOTPROVVAGEURO1 * TD.SEGNO AS TOTPROVVAG1EURO, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * (CAST(REPLACE(TD.PRCPROVVFINALEAG2,',','.') as decimal(9,4)))/ 100 + RD.TOTPROVVAGEURO2 * TD.SEGNO AS TOTPROVVAG2EURO, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO * (CAST(REPLACE(TD.PRCPROVVFINALEAG3,',','.') as decimal(9,4))) / 100 + RD.TOTPROVVAGEURO3 * TD.SEGNO AS TOTPROVVAG3EURO,
                          (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8) AS UMSTATART, TD.INCIDENZASCONTI, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END AS TOTNETTISSIMO, 
					  CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGA * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGA * TD.SEGNO END AS TOTNETTISSIMODIVISA,
					  TD.CODCAMBIO, 
                      CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END AS TOTNETTISSIMORES, 
					  dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGEST * FC.FATTORE * TD.SEGNO AS TOTCOSTOEURO, 
                      (CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURO * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURO * TD.SEGNO END) - dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGEST * FC.FATTORE * TD.SEGNO AS MARGNETTISSIMO, 
					  dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS TOTCOSTOEURORES, 
                      (CASE WHEN RD.TIPORIGA='O' THEN RD.TOTNETTORIGAEURORES * TD.SEGNO ELSE TD.INCIDENZASCONTI * RD.TOTNETTORIGAEURORES * TD.SEGNO END)- dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS MARGNETTISSIMORES, 
                      RD.TOTNETTORIGAEURO * TD.SEGNO - dbo.LEGGIULTIMOPREZZO(RD.CODART, TD.DATADOC)* RD.QTAGEST * FC.FATTORE * TD.SEGNO AS MARGNETTO, 
					  RD.TOTNETTORIGAEURORES * TD.SEGNO - dbo.LEGGIULTIMOPREZZO(RD.CODART,TD.DATADOC) * RD.QTAGESTRES * FC.FATTORE * TD.SEGNO AS MARGNETTORES,
					  dbo.LEGGICLIENTEINTESTATARIO(RD.IDTESTARP) AS CLIENTEBOLLA,
					  TE.NCAMPAGNA,TE.DESCCAMPAGNA, TE.NPROMOZIONE,TE.DESCPROMOZIONE,TE.RIGAPADRE, RD.IDRIGA, TD.PROGRESSIVO
FROM         dbo.TESTEDOCUMENTI TD INNER JOIN
                      dbo.RIGHEDOCUMENTI RD ON TD.PROGRESSIVO = RD.IDTESTA INNER JOIN
					  dbo.TP_EXTRARIGHEDOC TE ON TE.IDTESTA=RD.IDTESTA AND TE.IDRIGA=RD.IDRIGA INNER JOIN
                      dbo.PARAMETRIDOC ON dbo.PARAMETRIDOC.CODICE = TD.TIPODOC AND dbo.PARAMETRIDOC.TIPO IN ('F', 'N','O') AND 
                      dbo.PARAMETRIDOC.CLIFOR = 'C' INNER JOIN
                      dbo.ARTICOLIFATTORICONVERSIONE FC ON RD.CODART = FC.CODART AND FC.UM1 = RD.UMGEST
WHERE     (FC.UM2 =
                          (SELECT     UM
                            FROM          ARTICOLIUMPREFERITE UMP
                            WHERE      UMP.CODART = RD.CODART AND UMP.TIPOUM = 8))
GO
GRANT SELECT ON dbo.BRIOVISTAFATTCLIENTE_DO TO METODO98
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTAPROMOZIONI_DO') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTAPROMOZIONI_DO
GO
CREATE VIEW dbo.BRIOVISTAPROMOZIONI_DO AS
SELECT
LTRIM(STR(TP.NUMEROPROMOZIONE)) AS NUMEROPROMOZIONE, TP.NUMEROCAMPAGNA,TP.DESCPROMO,TP.DESCCAMPAGNA,TP.TIPO,TP.CODART,TP.UM, FC.UM1, FC.UM2 AS UMSTAT,
BDG_QTA*FC.FATTORE AS BDG_QTA_CONVERTITA,TP.BDG_QTA,TP.BDG_VALORE
FROM BRIOVISTA_TMP_PROMOZIONI_DO TP INNER JOIN
dbo.ARTICOLIFATTORICONVERSIONE FC ON TP.CODART = FC.CODART AND TP.UM = FC.UM1
WHERE
	FC.UM2 = (SELECT UM FROM ARTICOLIUMPREFERITE UMP WHERE UMP.CODART=TP.CODART AND UMP.TIPOUM = 8)
GO
GRANT SELECT ON dbo.BRIOVISTAPROMOZIONI_DO TO METODO98
GO



IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTA_MOVIMENTICDC') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTA_MOVIMENTICDC
GO
CREATE VIEW BRIOVISTA_MOVIMENTICDC AS 
SELECT

	MCDC.ANNO ANNOCOMP, MCDC.MESE AS MESECOMP, 
	YEAR(MCDC.DATAREG) AS ANNOREG, STR(MONTH(MCDC.DATAREG), 2, 0) + ' - ' + DATENAME(MM, MCDC.DATAREG) AS MESEREG,MCDC.DATAREG,
	AC.CLICOMMITT AS COMMITTENTE,AC.CLIFATT AS CLIENTEFATTURAZIONE, MCDC.CODCOMMESSA, 
	(CASE AC.STATOCOMMESSA WHEN 0 THEN 'IMMESSA' WHEN 1 THEN 'ATTIVA' WHEN 2 THEN 'SOSPESA' ELSE 'CHIUSA' END) AS STATOCOMMESSA,
	TC.CAUSALE, CC.DESCRIZIONE AS DESCRIZIONECAUSALE,
	CASE WHEN TC.PROVVISORIO=0 THEN 'Definitivo' ELSE 'Provvisorio' END AS STATOMOVIMENTO,
	MCDC.CODCONTOCC AS CODICECDC, CDC.DESCRIZIONE AS DESCRIZIONECDC,
	CFG.CODMASTRO, MST.DESCRIZIONE AS DESCRIZIONEMASTRO,
	MCDC.CODGENERICO AS CODICEGENERICO, CFG.DSCCONTO1 AS DESCRIZIONEGENERICO,
	CASE WHEN MCDC.SEGNO=0 THEN IMPORTORIPEURO ELSE 0 END AS IMPORTODARE,
	CASE WHEN MCDC.SEGNO=1 THEN IMPORTORIPEURO ELSE 0 END AS IMPORTOAVERE

FROM MOVIMENTICDC MCDC
	INNER JOIN TABCFG CFG ON MCDC.CODGENERICO=CFG.CODCONTO
	INNER JOIN TABMASTRI MST ON CFG.CODMASTRO=MST.CODICE
	LEFT OUTER JOIN ANAGRAFICACOMMESSE AC ON MCDC.CODCOMMESSA=AC.RIFCOMM
	LEFT OUTER JOIN TABCENTRICOSTO CDC ON MCDC.CODCONTOCC=CDC.CODICE
	LEFT OUTER JOIN TESTECONTABILITA TC ON MCDC.IDRIFERIMENTO=TC.PROGRESSIVO
	LEFT OUTER JOIN CAUSALICONTABILI CC ON TC.CAUSALE=CC.CODICECAUSALE
GO
GRANT SELECT ON BRIOVISTA_MOVIMENTICDC TO METODO98
GO


IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIOVISTA_CONTRATTI_COSTIFICAZIONERIGHE') AND TYPE = 'V')
    DROP VIEW dbo.BRIOVISTA_CONTRATTI_COSTIFICAZIONERIGHE
GO
CREATE VIEW BRIOVISTA_CONTRATTI_COSTIFICAZIONERIGHE AS
SELECT 
	CONTRATTO, IDTESTADOC, IDRIGADOC, DESCRIZIONECONTRATTO, 
	MAX(PERCTRASPORTO)AS PERCTRASPORTO, MAX(INCIDENZABUDGETINCOND)AS INCIDENZABUDGETINCOND, 
	MAX(INCIDENZAINCOND)AS INCIDENZAINCOND, MAX(INCIDENZABUDGETCOND)AS INCIDENZABUDGETCOND, 
	MAX(INCIDENZACOND)AS INCIDENZACOND, MAX(TOTALENETTOBUDGETINCOND)AS TOTALENETTOBUDGETINCOND, 
	MAX(TOTALENETTOINCOND)AS TOTALENETTOINCOND, MAX(TOTALENETTOBUDGETCOND)AS TOTALENETTOBUDGETCOND, 
	MAX(TOTALENETTOCOND)AS TOTALENETTOCOND, MAX(TOTALENETTOPROVVIGIONI)AS TOTALENETTOPROVVIGIONI,
	MAX(TOTALENETTOSCONTIMERCE)AS TOTALENETTOSCONTIMERCE,
	CODCLIFOR, CODCFFATT, NUMDIVERSAMERCI, 
	MAX(TOTALENETTOBUDGETINCONDVALORE)TOTALENETTOBUDGETINCONDVALORE, MAX(TOTALENETTOINCONDVALORE)AS TOTALENETTOINCONDVALORE,
	MAX(TOTALENETTOBUDGETCONDVALORE)AS TOTALENETTOBUDGETCONDVALORE, MAX(TOTALENETTOCONDVALORE)AS TOTALENETTOCONDVALORE, 
	MAX(PERC_VAL)AS PERC_VAL, MAX(INCIDENZABUDGETCONDRIGA)AS INCIDENZABUDGETCONDRIGA,
	MAX(INCIDENZACONDRIGA)AS INCIDENZACONDRIGA, MAX(INCIDENZAPREMIOMATURATO)AS INCIDENZAPREMIOMATURATO, 
	MAX(INCIDENZAPREMIOMATURATOBUDGET)AS INCIDENZAPREMIOMATURATOBUDGET, SUM(PREMIOCONDIZIONATO)AS PREMIOCONDIZIONATO,
	SUM(VALORERIGAPREMIO)AS VALORERIGAPREMIO
FROM CONTRATTI_COSTIFICAZIONERIGHE
GROUP BY CONTRATTO, IDTESTADOC, IDRIGADOC, DESCRIZIONECONTRATTO, CODCLIFOR, CODCFFATT, NUMDIVERSAMERCI

GO
GRANT SELECT ON BRIOVISTA_CONTRATTI_COSTIFICAZIONERIGHE TO METODO98
GO


IF NOT EXISTS (SELECT 1 FROM (SYSCOLUMNS INNER JOIN SYSOBJECTS ON SYSCOLUMNS.ID = SYSOBJECTS.ID) WHERE SYSOBJECTS.NAME = 'TabCategorie' AND SYSCOLUMNS.NAME='Budget')
	ALTER TABLE TabCategorie ADD Budget decimal(4, 2) DEFAULT 0
GO
UPDATE Tabcategorie SET Budget = 0 WHERE Budget IS NULL
GO

IF NOT EXISTS (SELECT 1 FROM (SYSCOLUMNS INNER JOIN SYSOBJECTS ON SYSCOLUMNS.ID = SYSOBJECTS.ID) WHERE SYSOBJECTS.NAME = 'TabCategorieStat' AND SYSCOLUMNS.NAME='Budget')
	ALTER TABLE TabCategorieStat ADD Budget decimal(4, 2) DEFAULT 0
GO
UPDATE TabCategorieStat SET Budget = 0 WHERE Budget IS NULL
GO


IF NOT EXISTS (SELECT 1 FROM (SYSCOLUMNS INNER JOIN SYSOBJECTS ON SYSCOLUMNS.ID = SYSOBJECTS.ID) WHERE SYSOBJECTS.NAME = 'CategorieCF' AND SYSCOLUMNS.NAME='Budget')
	ALTER TABLE CategorieCF ADD Budget decimal(4, 2) DEFAULT 0
GO
UPDATE CategorieCF SET Budget = 0 WHERE Budget IS NULL
GO

IF NOT EXISTS (SELECT 1 FROM (SYSCOLUMNS INNER JOIN SYSOBJECTS ON SYSCOLUMNS.ID = SYSOBJECTS.ID) WHERE SYSOBJECTS.NAME = 'TabSettori' AND SYSCOLUMNS.NAME='Budget')
	ALTER TABLE TabSettori ADD Budget decimal(4, 2) DEFAULT 0
GO
UPDATE TabSettori SET Budget = 0 WHERE Budget IS NULL
GO

IF NOT EXISTS (SELECT 1 FROM (SYSCOLUMNS INNER JOIN SYSOBJECTS ON SYSCOLUMNS.ID = SYSOBJECTS.ID) WHERE SYSOBJECTS.NAME = 'TabZone' AND SYSCOLUMNS.NAME='Budget')
	ALTER TABLE TabZone ADD Budget decimal(4, 2) DEFAULT 0
GO
UPDATE TabZone SET Budget = 0 WHERE Budget IS NULL
GO

IF NOT EXISTS (SELECT 1 FROM (SYSCOLUMNS INNER JOIN SYSOBJECTS ON SYSCOLUMNS.ID = SYSOBJECTS.ID) WHERE SYSOBJECTS.NAME = 'TabNazioni' AND SYSCOLUMNS.NAME='Budget')
	ALTER TABLE TabNazioni ADD Budget decimal(4, 2) DEFAULT 0
GO
UPDATE TabNazioni SET Budget = 0 WHERE Budget IS NULL
GO

------------------------------------------------------
IF NOT EXISTS (SELECT CODICE FROM TabCategorie WHERE CODICE = 0)
	INSERT INTO TabCategorie (Codice,Descrizione,UtenteModifica,DataModifica) VALUES (0,'Nessuna Catagoria','BrioBudget','2003/01/01')
GO

IF NOT EXISTS (SELECT CODICE FROM TabCategorieStat WHERE CODICE = 0)
	INSERT INTO TabCategorieStat (Codice,Descrizione,UtenteModifica,DataModifica) VALUES (0,'Nessuna Catagoria Statistica','BrioBudget','2003/01/01')
GO

IF NOT EXISTS (SELECT CodCategoria FROM CategorieCF WHERE CodCategoria = 0)
	INSERT INTO CategorieCF (CodCategoria,DscCategoria,UtenteModifica,DataModifica) VALUES (0,'Nessuna Catagoria CF','BrioBudget','2003/01/01')
GO
IF NOT EXISTS (SELECT CODICE FROM TabSettori WHERE CODICE = 0)
	INSERT INTO TabSettori (Codice,Descrizione,UtenteModifica,DataModifica) VALUES (0,'Nessun Settore','BrioBudget','2003/01/01')
GO

IF NOT EXISTS (SELECT CODICE FROM TabZone WHERE CODICE = 0)
	INSERT INTO TabZone (Codice,Descrizione,UtenteModifica,DataModifica) VALUES (0,'Nessuna Zona','BrioBudget','2003/01/01')
GO
IF NOT EXISTS (SELECT CODICE FROM TabNazioni WHERE CODICE = 0)
	INSERT INTO TabNazioni (Codice,Descrizione,UtenteModifica,DataModifica) VALUES (0,'Nessuna Nazione','BrioBudget','2003/01/01')
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.BRIO_VISTACARICHIANNOMESE') AND TYPE = 'V')
    DROP VIEW dbo.BRIO_VISTACARICHIANNOMESE
GO
CREATE VIEW BRIO_VISTACARICHIANNOMESE AS
SELECT VG.CODART,FC.UM1 AS UM_BASE, FC.UM2 AS UM_STAT, FC.FATTORE, VG.ESERCIZIO AS ANNO,MONTH(VG.DATAMOV)AS MESE, SUM(VG.QTACARICO*FC.FATTORE) AS QTA, SUM(VALORECARICOEURO) AS IMPORTOEURO
FROM VISTAGIACENZE VG 
INNER JOIN ARTICOLIFATTORICONVERSIONE FC ON VG.CODART=FC.CODART AND FC.UM1=(SELECT UM
																			FROM ARTICOLIUMPREFERITE UMP
																			WHERE UMP.CODART = VG.CODART AND UMP.TIPOUM = 1)
WHERE FC.UM2= (SELECT UM
               FROM ARTICOLIUMPREFERITE UMP
               WHERE UMP.CODART = VG.CODART AND UMP.TIPOUM = 8)
GROUP BY VG.CODART, VG.ESERCIZIO, MONTH(VG.DATAMOV), FC.FATTORE, FC.UM1, FC.UM2
GO
GRANT SELECT ON BRIO_VISTACARICHIANNOMESE TO METODO98
GO


if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BRIO_PREZZIARTICOLIMP]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[BRIO_PREZZIARTICOLIMP]
GO

CREATE TABLE [dbo].[BRIO_PREZZIARTICOLIMP](
	[CODART] [varchar](50) NULL,
	[ANNO] [smallint] NOT NULL,
	[MESE] [smallint] NOT NULL,
	[QTATOT] [decimal](19, 6) NULL,
	[IMPORTOTOTEURO] [decimal](19, 6) NULL,
	[QTASCAR] [decimal](19, 6) NULL,
	[IMPSCAR] [decimal](19, 6) NULL,
	[QTAMESEP] [decimal](19, 6) NULL,
	[IMPORTOMESEP] [decimal](19, 6) NULL,
	[PREZZOMEDIO]  AS (case when [QTAMESEP]=(0) then (0) else [IMPORTOMESEP]/[QTAMESEP] end)
) ON [PRIMARY]

GO
GRANT SELECT ON BRIO_PREZZIARTICOLIMP TO METODO98
GO




if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BRIO_CALCOLAPREZZOMPARTICOLI_2]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[BRIO_CALCOLAPREZZOMPARTICOLI_2]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE PROCEDURE [dbo].[BRIO_CALCOLAPREZZOMPARTICOLI_2] AS
 -----------------------------------------------------------------------------------
 -- ELIMINO TUTTI I VALORI PRECEDENTEMENTE SALVATI
 -----------------------------------------------------------------------------------
begin tran	    
	DELETE FROM BRIO_PREZZIARTICOLIMP
commit tran	
 -----------------------------------------------------------------------------------
 -- GENERO 12 MESI PER OGNI ESERCIZIO.. PER OGNI ARTICOLI IN STORICO MAG
 -----------------------------------------------------------------------------------
begin tran	    
	INSERT INTO BRIO_PREZZIARTICOLIMP(CODART,ANNO,MESE,QTATOT,IMPORTOTOTEURO,QTASCAR,IMPSCAR,QTAMESEP,IMPORTOMESEP)
    (SELECT DISTINCT SM.CODART,ES.CODICE,NR.NUMERO,0,0,0,0,0,0
    FROM STORICOMAG AS SM, TABESERCIZI ES, NUMERI NR
    WHERE NR.NUMERO<13)
commit tran	
 -----------------------------------------------------------------------------------
 -- SCRIVO QTA E VALORE CARICHI PER ANNO MESE ARTICOLO
 -----------------------------------------------------------------------------------
begin tran	   		
	UPDATE BRIO_PREZZIARTICOLIMP
		SET BRIO_PREZZIARTICOLIMP.QTATOT=BRIO_VISTACARICHIANNOMESE.QTA,
			BRIO_PREZZIARTICOLIMP.IMPORTOTOTEURO=BRIO_VISTACARICHIANNOMESE.IMPORTOEURO
		FROM BRIO_PREZZIARTICOLIMP INNER JOIN BRIO_VISTACARICHIANNOMESE ON
		BRIO_PREZZIARTICOLIMP.CODART=BRIO_VISTACARICHIANNOMESE.CODART AND
		BRIO_PREZZIARTICOLIMP.ANNO=BRIO_VISTACARICHIANNOMESE.ANNO AND
		BRIO_PREZZIARTICOLIMP.MESE=BRIO_VISTACARICHIANNOMESE.MESE
commit tran	
 -----------------------------------------------------------------------------------
 -- CALCOLO E SCRIVO QTA PROGRESSIVA E VALORE PROGRESSIVO CARICHI PER ANNO MESE ARTICOLO
 -----------------------------------------------------------------------------------
begin tran	
		UPDATE BRIO_PREZZIARTICOLIMP 
		SET BRIO_PREZZIARTICOLIMP.QTAMESEP=(SELECT SUM(BPPR.QTATOT) FROM BRIO_PREZZIARTICOLIMP BPPR WHERE BPPR.ANNO=BRIO_PREZZIARTICOLIMP.ANNO AND BPPR.CODART=BRIO_PREZZIARTICOLIMP.CODART AND BPPR.MESE <=BRIO_PREZZIARTICOLIMP.MESE)
commit tran	
begin tran	
		UPDATE BRIO_PREZZIARTICOLIMP 
		SET BRIO_PREZZIARTICOLIMP.IMPORTOMESEP=(SELECT SUM(BPPR.IMPORTOTOTEURO) FROM BRIO_PREZZIARTICOLIMP BPPR WHERE BPPR.ANNO=BRIO_PREZZIARTICOLIMP.ANNO AND BPPR.CODART=BRIO_PREZZIARTICOLIMP.CODART AND BPPR.MESE <=BRIO_PREZZIARTICOLIMP.MESE)
commit tran	
GO
GRANT EXECUTE ON BRIO_CALCOLAPREZZOMPARTICOLI_2 TO METODO98
GO

-- SCRIPT CREAZIONE UTENTE OLAP
IF NOT EXISTS(SELECT 1 FROM MASTER.DBO.SYSLOGINS WHERE LOGINNAME ='olap')
	CREATE LOGIN [olap] WITH PASSWORD=N'analisi', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
IF NOT EXISTS(SELECT 1 FROM DBO.SYSUSERS WHERE NAME ='Metodo98' AND ISSQLROLE=1)
EXEC sp_addrole N'Metodo98'


EXEC sp_revokedbaccess N'olap'
EXEC sp_grantdbaccess N'olap', N'olap'
EXEC sp_addrolemember N'Metodo98', N'olap'
GO