-- **********************************************************
-- * ARTICOLI PRESENTI IN ORDINE RICAMBI MA NON LANCIATI IN PRODUZIONE *
-- * Verifica se ci sono articoli ordinati come ricambi che per*
-- * qualche motivo non sono stati messi in produzione      *
-- * G. Ragazzo - 20/11/2009


SELECT rd.codart, AA.DESCRIZIONE, convert(real,RD.QTAGEST) as QTA, convert(real,RD.QTAGESTRES) as QTARES, RD.QTA1MAG, RD.QTA1MAGRES, RD.RIGACHIUSA, 
       RD.ESERCIZIO, RD.TIPODOC, RD.NUMERODOC, CONVERT(VARCHAR,TD.DATADOC,105) AS DATA_DOC, AC.DSCCONTO1, convert(varchar,RD.DATACONSEGNA,105) as DATA_CONSEGNA
FROM RIGHEDOCUMENTI RD
	LEFT JOIN TESTEDOCUMENTI TD ON RD.IDTESTA = TD.PROGRESSIVO
	LEFT JOIN ANAGRAFICACF AC ON TD.CODCLIFOR = AC.CODCONTO
LEFT JOIN ANAGRAFICAARTICOLI AA ON AA.CODICE = RD.CODART
WHERE RD.TIPODOC IN ('OR1', 'OR2')
	AND RD.QTA1MAGRES<>0										-- VERIFICA CHE CI SIANO QUANTITA' RESIDUA DA GESTIRE
	AND RD.CODART <>''											-- NON CONSIDERA LE RIGHE DESCRITTIVE
	AND RIGACHIUSA = 0											-- VERIFICA SOLO LE RIGHE APERTE
	AND (SELECT COUNT(PROGRESSIVO) 
		FROM STORICOMAG 
		WHERE IDTESTA=RD.IDTESTA AND RIGADOC=RD.IDRIGA)=0		--CONTROLLA CHE NON CI SIANO STATI MOVIMENTI
ORDER BY RD.CODART ASC
