--************************************************************
--* STAMPA DICHIARAZIONI OFFICINA DI TIPO "RIPRESA" CON NOTE *
--*		AMADI FEBBRAIO 2011
--************************************************************
set dateformat dmy
SELECT      TC.CODCICLO AS COMMESSA, CONVERT (VARCHAR,SA.DATAMOV, 105) AS DATA, OP.DESCRIZIONE AS FASE_CICLO,  
            CONVERT(FLOAT,SA.OREMACCHINA) AS ORE, replace(replace(EA.NOTELAV, char(13),' '), char(10),'') as NOTE_LAVORAZIONE,
			TD.COGNOME, TD.NOME, RO.OPERAZIONE, SA.PROGRESSIVO AS NUMERO_MOV, SA.NUMEROBOLLA
--SA.PROGRESSIVO, SA.ANNOBOLLA, SA.MACCHINA,DM.DIPENDENTE,SA.ESERCIZIO
FROM       STORICOAVANZAMENTI SA
			LEFT JOIN EXTRAAVANZAMENTI EA ON SA.PROGRESSIVO = EA.RIFPROGRESSIVO
			LEFT JOIN DIPENDENTIMOVIMENTO DM ON SA.PROGRESSIVO = DM.RIFPROGRESSIVO
			LEFT JOIN TABELLADIPENDENTI TD ON DM.DIPENDENTE = TD.CODICE
			LEFT JOIN RIGHECICLOORDINE RO ON SA.ANNOBOLLA = RO.ANNOBOLLA AND SA.NUMEROBOLLA = RO.NUMEROBOLLA
			INNER JOIN TESTACICLOORDINE TC ON RO.PROGRESSIVO = TC.PROGRESSIVO
			LEFT JOIN TABELLAOPERAZIONI OP ON RO.OPERAZIONE = OP.CODICE
WHERE     
(SA.CODCAUSALE = '110')  -- 110 = riprese 200=ATTIVITA' INDIRETTE VARIE
--AND (SA.NUMEROBOLLA = '6597')
--AND SA.DATAMOV = '22/04/2011'
and SA.DATAMOV >= '25/06/2017' AND SA.DATAMOV <= '30/07/2017'
--AND TC.CODCICLO = '00Y1038-P01'
ORDER BY SA.DATAMOV,TC.CODCICLO


--************************************************************
--* STAMPA DICHIARAZIONI OFFICINA DI TIPO "RIPRESA" CON NOTE *
--*		PER DATI CRISTINA
--************************************************************
--set dateformat dmy
--SELECT      TC.CODCICLO, CONVERT (VARCHAR,SA.DATAMOV, 105) AS DATA, OP.DESCRIZIONE AS DESC_OPERAZIONE,  
--            CONVERT(FLOAT,SA.OREMACCHINA) AS ORE, SA.CODCAUSALE, EA.NOTELAV, 
--			(TD.COGNOME+' '+TD.NOME) AS DIPENDENTE, RO.OPERAZIONE, SA.PROGRESSIVO AS NUMERO_MOV, SA.NUMEROBOLLA
----SA.PROGRESSIVO, SA.ANNOBOLLA, SA.MACCHINA,DM.DIPENDENTE,SA.ESERCIZIO
--FROM       STORICOAVANZAMENTI SA
--			LEFT JOIN EXTRAAVANZAMENTI EA ON SA.PROGRESSIVO = EA.RIFPROGRESSIVO
--			LEFT JOIN DIPENDENTIMOVIMENTO DM ON SA.PROGRESSIVO = DM.RIFPROGRESSIVO
--			LEFT JOIN TABELLADIPENDENTI TD ON DM.DIPENDENTE = TD.CODICE
--			LEFT JOIN RIGHECICLOORDINE RO ON SA.ANNOBOLLA = RO.ANNOBOLLA AND SA.NUMEROBOLLA = RO.NUMEROBOLLA
--			INNER JOIN TESTACICLOORDINE TC ON RO.PROGRESSIVO = TC.PROGRESSIVO
--			LEFT JOIN TABELLAOPERAZIONI OP ON RO.OPERAZIONE = OP.CODICE
--WHERE
--EA.NOTELAV <>''     
----(SA.CODCAUSALE = '110')  -- 110 = riprese 200 = ATTIVITA' INDIRETTE VARIE
----AND (SA.NUMEROBOLLA = '6597')
----AND SA.DATAMOV = '22/04/2011'
--and SA.DATAMOV >= '01/01/2012' AND SA.DATAMOV <= '31/12/2012'
----AND TC.CODCICLO = '00Y1038-P01'
--ORDER BY SA.DATAMOV, TC.CODCICLO