/*VERIFICA QUALI DOCUMENTI CONTENGANO IL DEPOSITO SPECIFICATO*/
SELECT *
FROM PARAMETRIDOC
WHERE CODDEPOSITO = '013'
OR CODDEPOSITOCOLL = '013'
OR CODDEPCOMP = '013'
OR CODDEPCOMPCOLL = '013'

/*VERIFICA QUALI DOCUMENTI CONTENGANO LA CAUSALE SPECIFICATA*/
SELECT *
FROM PARAMETRIDOC
WHERE CAUSALEMAG = '012'
OR CAUSALEMAGCOLL = '012'
OR CAUSALEMAGCOMP = '012'
OR CAUSALEMAGCOMPCOLL = '012'


-- verifica le abilitazioni nei vari documenti
select coddocumento, nomeutente, tiporighe, tipopiede, flagabilita, flagvisualizza, flagpreleva 
from accessidocumenti 
where nomeutente='a.norbiato'


-- STAMPA TABELLA MAGAZZINI E CAUSALI ASSOCIATI AI VARI TIPI DOCUMENTI
-- IMERIO MARZO 2010
select pd.codice, pd.descrizione, pd.tipo, pd.coddeposito, pd.causalemag, cm.descrizione,  
       pd.coddepositocoll, pd.causalemagcoll, tc.descrizione  
from parametridoc pd
left join tabcausalimag cm on cm.codice = pd.causalemag 
left join tabcausalimag tc on tc.codice = pd.causalemagcoll
where tipo not in ('B', 'O')
order by pd.codice


-- STAMPA CAUSALI NON USATE IN NESSUN PARAMETRO DOCUMENTO
-- IMERIO MARZO 2009
SELECT CM.CODICE, CM.DESCRIZIONE FROM TABCAUSALIMAG CM
WHERE (SELECT COUNT (PD.CODICE) FROM PARAMETRIDOC PD WHERE (CM.CODICE=PD.CAUSALEMAG OR CM.CODICE=PD.CAUSALEMAGCOLL))=0


-- STAMPA CAUSALI MAI USATE IN NESSUN MOVIMENTO
-- IMERIO MARZO 2009
SELECT CM.CODICE, CM.DESCRIZIONE FROM TABCAUSALIMAG CM
WHERE (SELECT COUNT(PROGRESSIVO) FROM STORICOMAG WHERE CODCAUSALE=CM.CODICE)=0 
order by codice


--STAMPA CONTATORI MAI USATI INDICANDO ANCHE I DOCUMENTI CHE NE PREVEDONO L'USO
-- IMERIO MAGGIO 2010
SELECT TC.ESERCIZIO, TC.CODICE AS CODCONTATORE, TC.DESCRIZIONE AS DESCCONTATORE, PD.CODICE AS TIPODOC, PD.DESCRIZIONE AS DESCRIZIONEDOC
FROM TABCONTATORI TC
LEFT JOIN PARAMETRIDOC PD ON PD.CODICETAPPO = TC.CODICE
WHERE TC.PROGR = '0'
AND TC.ESERCIZIO IN('2010')
ORDER BY TC.CODICE

-- DATO UN CONTATORE VERIFICA I DOCUMENTI CHE LO USANO
-- IMERIO MAGGIO 2010
SELECT TC.ESERCIZIO, TC.CODICE AS CODCONTATORE, TC.DESCRIZIONE AS DESCCONTATORE, PD.CODICE AS TIPODOC, PD.DESCRIZIONE AS DESCRIZIONEDOC
FROM TABCONTATORI TC
LEFT JOIN PARAMETRIDOC PD ON PD.CODICETAPPO = TC.CODICE
WHERE TC.CODICE = '141'
AND TC.ESERCIZIO IN('2009', '2010')
ORDER BY TC.CODICE