--***********************************
--* Vista standard export solo documenti tipo 6 (solo CAM)

IF EXISTS(SELECT 1 FROM SYSOBJECTS WHERE SYSOBJECTS.ID=OBJECT_ID('MET_LISTACOMM_EXPORTRADAR') AND SYSOBJECTS.TYPE='V')
	DROP VIEW MET_LISTACOMM_EXPORTRADAR
GO
CREATE VIEW MET_LISTACOMM_EXPORTRADAR AS
SELECT DISTINCT 
	1 AS FLGSEL,
	MSE.IDTESTADOC,
	MSE.IDRIGADOC,
	MSE.RIFERIMENTI,
	MSE.TIPO,
	''AS NOTE,
	'IMPORT' AS UTENTEMODIFICA,
	GETDATE() AS DATAMODIFICA 
FROM 
	MET_SEL_EXPORTRADAR MSE
WHERE 
	MSE.STATOORDINE<>3 AND MSE.TIPOCOM='CAM'
	--	(STATOORDINE <> 3) AND (TIPOCOM = 'CAM') AND (TIPO = 6) AND (LEFT(RIFERIMENTI, 3) <> '\\\') OR
    --                     (STATOORDINE <> 3) AND (TIPO = 3) AND (LEFT(RIFERIMENTI, 3) <> '\\\')	--daniele r.29/03/2017 per inserire anche EM1
GO
GRANT SELECT ON MET_LISTACOMM_EXPORTRADAR TO METODO98
GO
